### ISSUE TITLE
Something wrong with sacrifice rune

### ISSUE THREAD

**Issue by Pyko1** [HippieStationCode/HippieStation13#1009]
Observers/dead get this confirmations screen.
![capture](https://cloud.githubusercontent.com/assets/12048747/10696683/f7ee2c6c-79b1-11e5-86f7-5a7ca0b45c7a.PNG)
When you get picked your name changed in to Shade of someone who was sacrificed.
But yet you are jsut a normal white ghost with no abilities.

Traitor panel says you are a shade, even tho you are just a ghost.
![capture](https://cloud.githubusercontent.com/assets/12048747/10696754/637ac012-79b2-11e5-8054-3e9e0351efd9.PNG)

![capture](https://cloud.githubusercontent.com/assets/12048747/10696777/84436ca4-79b2-11e5-9007-3891d5ff0dd0.PNG)

**Comment by Carbonhell** [comment]
Will test now

**Comment by Pyko1** [comment]
well could be the issue is not exsactly on sacrifice rune, but at least the guy whos shade i was had all of his stuff on a sacrifice rune, and i did get the pop up at least once on the exact moment someone was sacrificed.

**Comment by Carbonhell** [comment]
Found the issue,you pratically spawn dead. fixing it.
