### ISSUE TITLE
Kitchen Setup looks extremely weird 

### ISSUE THREAD

**Issue by Spacedong** [HippieStationCode/HippieStation13#1015]
http://vgy.me/UrpyTK.png notice how the deep fryer is like inside the table, I liked it pre-rebase when we had the one tile long table and the deep fryer in front, also, the chef vendor looks kinda queer being stuck in the wall like that

**Comment by Chronitonity** [comment]
Use the fourms for this stuff, use the bug tracker for actual bugs.

**Comment by Spacedong** [comment]
link me to the fucking suggestion box where IS IT aaaaaaaaaaaaa
