### ISSUE TITLE
Dream Seeker Crash

### ISSUE THREAD

**Issue by Pyko1** [HippieStationCode/HippieStation13#1031]
![capture](https://cloud.githubusercontent.com/assets/12048747/10716194/5595a25e-7b39-11e5-8331-6170d11809d9.PNG)
Examined the deepfried clown twice, crashed both times.

**Comment by Carbonhell** [comment]
You sure it was caused by that?I get random crashes sometimes too

**Comment by Pyko1** [comment]
happened twice, when i examined the clown

**Comment by Carbonhell** [comment]
Asked other people the round immediately after and noone noticed this bug even after examining this guy. I'll try to reproduce it tomorrow.

**Comment by Carbonhell** [comment]
Close this,the issue made now is more detailed
