### ISSUE TITLE
Research Scanner can still be toggled on/off even when taking off the science goggles.

### ISSUE THREAD

**Issue by Spacedong** [HippieStationCode/HippieStation13#1038]
Just as what the title says, the tooltip to research scan still stays without the science goggles being on your person.

**Comment by GunHog** [comment]
I created a fix for this on /tg/: https://github.com/tgstation/-tg-station/pull/12762 Consider having one of your coders test and port it!

**Comment by Chronitonity** [comment]
Fuck thanks @GunHog

**Comment by Memendia** [comment]
A @Spacedong issue that is actually a bug?

is the world ending!?
