### ISSUE TITLE
Deepfried deepfried deepfried crash

### ISSUE THREAD

**Issue by Pyko1** [HippieStationCode/HippieStation13#1044]
![capture](https://cloud.githubusercontent.com/assets/12048747/10739521/92eef942-7c25-11e5-8ad0-e8a232d6760e.PNG)
The game crashed for me every time after i looked at him.

**Comment by Carbonhell** [comment]
If possible i'd need some more info about the bug. Can you try to remove all those items and examine them?To see if a specify one crashes. Also can you try to deepfry an item countless times and see if it crashes too?It'd be rad

**Comment by Pyko1** [comment]
crashing stopped after I renamed him back to determination

**Comment by Pyko1** [comment]
![capture](https://cloud.githubusercontent.com/assets/12048747/10739993/5c7ce556-7c28-11e5-9852-91fbe2b2e5f3.PNG)
Crashing stopped after i stripped him, and would not start happening again when i put the clothes back on to him.
Also the icons seem to be broken on all the items.

**Comment by TDcoolguy300** [comment]
The fix for this is having issues with Travis right now, need Carbon to fix his shit.
