### ISSUE TITLE
PA is unable to be emagged, turned up to level 3, or hacked at all.

### ISSUE THREAD

**Issue by Spacedong** [HippieStationCode/HippieStation13#1051]
As the title says, the PA can not be emagged, hitting it does nothing, cutting wires just gives a message: ERROR: Request timed out. Check wire contacts. and nothing happens.

**Comment by Pyko1** [comment]
It worked just a while ago tho.

**Comment by Pyko1** [comment]
Seems to work as intended, there are both cut and pulse functions.

No comment on emagging tho

**Comment by Spacedong** [comment]
still not able to be emagged

**Comment by danhibiki** [comment]
I don't think this is the case, anymore?
