### ISSUE TITLE
Gun lockers in Armory spawn with guns on top of them for no (?) reason.

### ISSUE THREAD

**Issue by Spacedong** [HippieStationCode/HippieStation13#1053]
So every round its like this, http://vgy.me/47io31.png, for some reason, I can't tell if its a bug and the guns just don't fit in the actual gun closets or something, or its supposed to be mapped like that, (looks strange) whatever, the case, it looked really like a bug.

**Comment by Pyko1** [comment]
The gun cabins can only hold 4 guns, so the extra ones are just spawned in top of em. Also the cabins have other issues as well such as a bug that allows teleporting of guns.

**Comment by Spacedong** [comment]
wow thats fuckin stupid gun cabins increase when

**Comment by Carbonhell** [comment]
doing this right now too cuck
