### ISSUE TITLE
Invisible c4

### ISSUE THREAD

**Issue by Pyko1** [HippieStationCode/HippieStation13#1060]
You can plant a c4 on pizza box and open/close it to make it disapear.
Most likely works with any item that changes its icon same way.

**Comment by lcass** [comment]
I can make this c4 dis-appear ... tada!

**Comment by Crystalwarrior** [comment]
Can you confirm this actually deletes the C4 item? Or does it just remove the C4 overlay?

**Comment by Pyko1** [comment]
It just makes the overlay disappear. The C4 is still there and counting.
Also I recall that at least at some point the C4 on people used to disappear when they were stunned, but that might not be the case anymore.

**Comment by Pyko1** [comment]
Still there due to:
```
/obj/item/pizzabox/update_icon()
	overlays = list()
```
Removing `image_overlay = image('icons/obj/assemblies.dmi', "plastic-explosive2")` set by c4
