### ISSUE TITLE
Can't grind people with chitin shells/ling shells

### ISSUE THREAD

**Issue by Spacedong** [HippieStationCode/HippieStation13#1066]
Since the chitin armor or shells count as clothing, you can't deep fry them.

**Comment by Carbonhell** [comment]
You can't deepfry them?You mean GIB?Most likely intended,not 100% sure thro

**Comment by JustinBNewton** [comment]
Feature, you have to burn people in this state.

**Comment by Chronitonity** [comment]
Feature
