### ISSUE TITLE
Broken disposals 

### ISSUE THREAD

**Issue by Pyko1** [HippieStationCode/HippieStation13#109]
There is unneeded straight pipe in top of junction at X-133 Y-166 that causes half of the stations disposals to loop back.
![spot](https://cloud.githubusercontent.com/assets/12048747/7364417/ee2ee022-ed8e-11e4-8559-9c4f7a119e1c.jpg)

**Comment by WitheredGryphon** [comment]
I'll take a look at the loop tomorrow. Should be an easy fix.
