### ISSUE TITLE
Can't move around with a cardboard box in low grav, even when sticking to a wall.

### ISSUE THREAD

**Issue by Spacedong** [HippieStationCode/HippieStation13#1092]
see title :^(

**Comment by Memendia** [comment]
not a bug :+1:

**Comment by Spacedong** [comment]
thats stupid

**Comment by Chronitonity** [comment]
Its a crate, sorry buddy. If you want an actual reason its that you're pushing off the wall when in 0 gravity, while in a box the only thing you can push off of is the interior.

**Comment by Spacedong** [comment]
ok now I understand
