### ISSUE TITLE
Broken floor tiles at pool

### ISSUE THREAD

**Issue by Pyko1** [HippieStationCode/HippieStation13#110]
The tiles at pool room cant be removed with crowbar. Maybe just change the tile type around the pool to /turf/simulated/floor/plasteel and and toss the pool tile icons there as icon_state?

**Comment by Cairo283** [comment]
It's the same with the floor tiles in the wrasslin' ring

**Comment by WitheredGryphon** [comment]
I'll fix this this tomorrow. Gotta rehook up my computer since I unhooked it for my PS4

**Comment by WitheredGryphon** [comment]
Scratch that I'm not touching this. The guys who made the pool and boxing ring were lazy as hell and didn't write any tile code whatsoever, and the code they did use is ported from a far obsolete turf file (which by the way NEEDS TO BE NUKED).

**Comment by HoaxIT** [comment]
ugh.. will fix
