### ISSUE TITLE
Lots of inconsistencies while drilling things as Ripley

### ISSUE THREAD

**Issue by Spacedong** [HippieStationCode/HippieStation13#1104]
For example, some consoles, when drilled, will delete themselves, some will break, and some just aren't able to be drilled. Reinforced tables surrounding the comms console cannot be drilled either, but the ones on the side of the bridge can. I'm assuming it's something to do with mapping. This may happen with other things around station as well. A ripley can't drill another ripley either.

**Comment by Memendia** [comment]
Are you sure you just didn't drill the table enough?

**Comment by Spacedong** [comment]
I drilled it like 10 times nig

**Comment by Carbonhell** [comment]
It's supposed to be like this. Normal drills have a limit on what they can drill,for example reinforced walls. Diamond drills can also drill reinf walls but there are some items that cannot be drilled for balance purposes or some stuff. Also tables break correctly,so no clue what you're speakin about
