### ISSUE TITLE
shoulder holster can only go on belt slot

### ISSUE THREAD

**Issue by Spacedong** [HippieStationCode/HippieStation13#1144]
why

**Comment by Chronitonity** [comment]
where else would it go

**Comment by Chronitonity** [comment]
also this isn't a bug so

**Comment by Spacedong** [comment]
but it goes on your shoulder what the fuck >goes on shoulder >not on shoulder?!?!?!?!

**Comment by Chronitonity** [comment]
Design a shoulder slot and then make a feature request on the fourms, stop using the git bug tracker for shit that isnt a bug

**Comment by oprayx73** [comment]
fucker that shit is geared on your waist with straps over your shoulder, the pistols are stored right above your waist, therefore a belt slot wouldn't be terrible + means you cant wear a toolbelt at the same time, (which makes fucking sense) dong is DUMB
