### ISSUE TITLE
can't change transfer rate on backpack water tank

### ISSUE THREAD

**Issue by Spacedong** [HippieStationCode/HippieStation13#1153]
as the title says, you could change it like right after we rebased but now you can't, fix this ASAP botany is fucking ruined because I can't evenly distribute now

**Comment by Chronitonity** [comment]
Use the sprayer in your hand, use the backpack in your hand

**Comment by Spacedong** [comment]
doesn't work.

**Comment by danhibiki** [comment]
Can confirm, untoggleable. There is no right click context menu as well.

**Comment by Spacedong** [comment]
wow fuck you chron i told you

**Comment by oprayx73** [comment]
Spacedong commented 37 seconds ago

wow fuck you chron i told you

**Comment by Spacedong** [comment]
AGAGAGA!!
