### ISSUE TITLE
Stands can still be alive when their master dies in some cases.

### ISSUE THREAD

**Issue by Spacedong** [HippieStationCode/HippieStation13#1163]
There was this one incident where me and some other guys killed a miner on the asteroid with a stand, his stand continued to be alive even after he died, kept punching us until after 2 minutes the guy's body gibbed and he disappeared, what gives?

**Comment by danhibiki** [comment]
anyone else notice this?

**Comment by Chronitonity** [comment]
probably the MC locking up

**Comment by danhibiki** [comment]
Gonna close it since it might not be a direct issue, lets keep this in mind if it keeps showing up and keep an eye on our MC when it does.
