### ISSUE TITLE
Lings are broken 

### ISSUE THREAD

**Issue by Spacedong** [HippieStationCode/HippieStation13#1167]
They can be unstoppable killing machines which isn't even what the gamemode is supposed to be, just get armblade and chitin armor and you're done. A ling with chitin armor can survive an admin clusterbomb, I SAW IT HAPPEN. Please god just nerf changelings into oblivion its horrible

**Comment by Chronitonity** [comment]
I agree but stop posting feedback and suggestions on this damn bug tracker. Seriously we have a feedback and suggestion fourm. Stop.

**Comment by Spacedong** [comment]
No one fucking uses the dead forums can't you see this christ

**Comment by Chronitonity** [comment]
Cool. Stop using the bug tracker for things that arent bugs, thanks.
