### ISSUE TITLE
Trying to put a shard in a pneumatic cannon when its full gives you damage by cutting ur hand

### ISSUE THREAD

**Issue by Spacedong** [HippieStationCode/HippieStation13#1296]
^^^^^^^^

**Comment by Spacedong** [comment]
really annoying

**Comment by danhibiki** [comment]
solution: have someone else do it for you, preferably the person you are shooting

**Comment by oprayx73** [comment]
lmao

**Comment by Crystalwarrior** [comment]
Happens to a lot of things, actually.
Clicking on WALLS with a shard will make it cut into your hand, and I'm pretty sure it does so for clicking on pipes and other things as well.

**Comment by Spacedong** [comment]
is this intended

**Comment by Crystalwarrior** [comment]
probably
not.

**Comment by Chronitonity** [comment]
iirc its intended.
