### ISSUE TITLE
DAKIMAKURAS (chron's fuckpillows) CAN HAVE INFINITELY LONG NAMES (holy fuck) 

### ISSUE THREAD

**Issue by Spacedong** [HippieStationCode/HippieStation13#1298]
http://vgy.me/mTCPKa.png 

HOLY SHIT

**Comment by Spacedong** [comment]
it also goes on forever, it took up literally 3 spaces of text and almost crashed my game, holy shit

**Comment by Spacedong** [comment]
leave it 2 chron 2 fuck shit up ag

**Comment by Spacedong** [comment]
habbening

**Comment by TDcoolguy300** [comment]
I am fixing it you NERD

**Comment by Spacedong** [comment]
ag fujk

**Comment by TDcoolguy300** [comment]
Didnt even last 15 minutes
