### ISSUE TITLE
HOS knows krav magooda

### ISSUE THREAD

**Issue by Spacedong** [HippieStationCode/HippieStation13#1307]
not sure if this is intended but HOS starts the round knowing krav magooda, can instantly disarm anyone of their weapon and put it in his hand, if it was intended, its pretty fucking OP, then again it may be a glitch due to retard coders +who knows

**Comment by calibraptor** [comment]
All security start the round knowing krav maga, have you been living under a rock?

**Comment by Spacedong** [comment]
thats so fucking overpowered are you kidding me they can instantly take anyone's weapon, think about it

**Comment by Chronitonity** [comment]
Intended.

**Comment by Spacedong** [comment]
>they can take anyone's weapon
>not overpowered
>intended

yeah ok

**Comment by Memendia** [comment]
gitgud

**Comment by danhibiki** [comment]
>waaah security boned me halp plz halp

**Comment by Memendia** [comment]
:salt:

**Comment by danhibiki** [comment]
:ok_hand:

**Comment by Memendia** [comment]
:salt:
![image](https://cloud.githubusercontent.com/assets/11639828/11448752/5169e0ba-9514-11e5-8541-e549047f6132.png)

**Comment by Spacedong** [comment]
salt is a baseless argument faggot try harder atleast hibiki has better memes than you nexendia
