### ISSUE TITLE
Teleporter on derelict doesn't work at all. 

### ISSUE THREAD

**Issue by Spacedong** [HippieStationCode/HippieStation13#1313]
can't be linked or anything, broken af

**Comment by doobiedoo23** [comment]
i think you're just dumb, did you use wirecutters on the middle thingy

**Comment by Spacedong** [comment]
yes

**Comment by Carbonhell** [comment]
Did you screwdrive the middle thing and THEN apply wirecutter and THEN screwdrive it again and try to use it; also was the thing powered

**Comment by Chronitonity** [comment]
obviously he did now as its closed
