### ISSUE TITLE
Canvas are broken

### ISSUE THREAD

**Issue by Spacedong** [HippieStationCode/HippieStation13#1320]
Turn invisible when clicked on, when you try to draw on them you start drawing a letter on the floor under them, buggy piece of shit etc.

**Comment by Spacedong** [comment]
also you cant even draw anything or drag your mouse to draw, tbh it should work like a paper where you shift click it THEN start drawing on it i.e. microsoft paint like html papers ag

**Comment by Crystalwarrior** [comment]
port my Atlas canvases already JEZZZZ
Atlas-Station canvases are an expanded and fixed up version of /tg/ canvases

**Comment by Crystalwarrior** [comment]
this issue is duplicate of https://github.com/HippieStationCode/HippieStation13/issues/1239
