### ISSUE TITLE
ALL storage boxes look weird/changeling boxes

### ISSUE THREAD

**Issue by Spacedong** [HippieStationCode/HippieStation13#1333]
http://vgy.me/l8KMjK.png 

wtf is this ?!?!?!

**Comment by DerptheStewpidGoat** [comment]
Well now we fucked up

**Comment by Spacedong** [comment]
fuck you http://vgy.me/LXqbuv.png

**Comment by Spacedong** [comment]
wow doobie told me it was a known bug but he didn't even put it up on the Issues page what a fucking c o c k
