### ISSUE TITLE
things revived by staff of animation have default human sprites 

### ISSUE THREAD

**Issue by Spacedong** [HippieStationCode/HippieStation13#1335]
![wx9svf](https://cloud.githubusercontent.com/assets/12958054/11488973/0c6393ee-9799-11e5-94e9-bdb84ef607b2.png)
oh fuck

**Comment by TDcoolguy300** [comment]
Someone fucked up the sprite holder for mimics, gr8

**Comment by Spacedong** [comment]
i bet it was the slav aka crystalmemer

**Comment by Spacedong** [comment]
ag

**Comment by Chronitonity** [comment]
As do vending machines that become mobs.
