### ISSUE TITLE
gateway isn't actually enterable by humans but ghosts can enter 

### ISSUE THREAD

**Issue by Spacedong** [HippieStationCode/HippieStation13#1336]
i blame immigrants and lazy fucking coders

**Comment by account-name** [comment]
ah yes great code mmmmmmmmm

**Comment by Spacedong** [comment]
gagsa

**Comment by oprayx73** [comment]
g

**Comment by account-name** [comment]
ag!!

**Comment by oprayx73** [comment]
https://i.gyazo.com/e93a47c648c0c346ff0823e832049d95.gif

**Comment by DerptheStewpidGoat** [comment]
We believe we know the fix to this but there's only a few staff with access to the box itself and the problem seems to be related to a config setting there.
