### ISSUE TITLE
robotics starts with 5 metal stacks but only one glass stack

### ISSUE THREAD

**Issue by Spacedong** [HippieStationCode/HippieStation13#1342]
this obviously has to be a bug because no fucking person would be THIS retarded to give robotics 5 metal stacks but only one glass stack like COME THE FUCK on

**Comment by Spacedong** [comment]
change this you hotheads

**Comment by Chronitonity** [comment]
Feeaaaaaaaatuuuuuuureeeeee requeeeeeeesssssst. If mining does their jobs they get more anyway.

Or just steal some from eva/the storage near eva.
