### ISSUE TITLE
borgs can be killed via noose 

### ISSUE THREAD

**Issue by Spacedong** [HippieStationCode/HippieStation13#1351]
Borgs can be hung and killed by nooses 

Additionally using the right click verb to make nooses is terrible, should be using the crafting menu that cable coils have.

If someone else unties the noose around you then it tells you that YOU, the person hanging, are untying it.

Nooses give no cable coils back when cut with wirecutters.

**Comment by danhibiki** [comment]
god damnit crystal

**Comment by Spacedong** [comment]
reverse noose update remove slav

**Comment by Spacedong** [comment]
no more lifeweb

**Comment by Chronitonity** [comment]
I'm just gonna make this Noose broken general

**Comment by oprayx73** [comment]
noose code runs on bodka

**Comment by Crystalwarrior** [comment]
oh no
I'll fix it in a jiffy.
