### ISSUE TITLE
pirate coat is the only exosuit clothing sprite (and maybe the only clothing sprite) to face backwards

### ISSUE THREAD

**Issue by Spacedong** [HippieStationCode/HippieStation13#1360]
http://vgy.me/iT71Zc.png

not sure if this is a visual error or im blind but this shit is backwards

**Comment by SgtFragg** [comment]
Can confirm, sprite is using north facing on-mob instead of south facing. Assets already available so just needs a coder to remedy when able.

**Comment by danhibiki** [comment]
Such a minor issue, could we get someone on this?

**Comment by danhibiki** [comment]
https://github.com/HippieStationCode/HippieStation13/blob/18849f50aa5220193933fd250deb1b83c31c310c/code/modules/clothing/suits/miscellaneous.dm#L34 This is the relevant code for pirate suits
