### ISSUE TITLE
ID card sprite glitched up (not sure how to reproduce)

### ISSUE THREAD

**Issue by Spacedong** [HippieStationCode/HippieStation13#1361]
so this "thing" or something or whatever it is looks like a gumball ,but its actually my ID 

http://vgy.me/aeISRY.png

**Comment by TDcoolguy300** [comment]
Glorious, no idea how your ID card somehow changed it's default icons file without admin intervention to a bloody rainbow slime extract

**Comment by Spacedong** [comment]
top kek

**Comment by TDcoolguy300** [comment]
With this being unable to reproduce, i am going to close it.
