### ISSUE TITLE
UNBEARABLE lag spikes hit the server constantly 

### ISSUE THREAD

**Issue by Spacedong** [HippieStationCode/HippieStation13#1363]
It's been happening for 3 days now and OOC is always filled with "FUCK THIS LAG" because of it, its either the gateway or this shitty new box I'm not sure

**Comment by oprayx73** [comment]
yeah dude no way no one picked up on it
thanks for this super handy issue report
we havent been thinking of this at all

**Comment by Spacedong** [comment]
well maybe if you got to fixing it fucker

**Comment by oprayx73** [comment]
maybe you should fix it

**Comment by Spacedong** [comment]
ok
