### ISSUE TITLE
The fedora tipping action has no cooldown, allowing it to be spammed indefinitely 

### ISSUE THREAD

**Issue by Spacedong** [HippieStationCode/HippieStation13#1365]
fucking hell lads

**Comment by Chronitonity** [comment]
Make your titles clear, concise, and polite thanks.

**Comment by Spacedong** [comment]
s0rry

**Comment by DerptheStewpidGoat** [comment]
You're punished in a sense if you tip it too much.

**Comment by oprayx73** [comment]
punished " venom " snake

**Comment by Chronitonity** [comment]
Still should have some sort of cooldown because it spams messages to everyone in the vicinity

**Comment by Spacedong** [comment]
^^^ this
