### ISSUE TITLE
Attack messages for birbs are misspelled

### ISSUE THREAD

**Issue by Spacedong** [HippieStationCode/HippieStation13#1373]
http://vgy.me/YSQevX.png

http://vgy.me/PLAgM5.png

clawsd

**Comment by Chronitonity** [comment]
idk what ya talking about clawsed is a perfectly fine english word somewhere in backwater Britain im sure

**Comment by Nebyab** [comment]
Its a feature

**Comment by Spacedong** [comment]
no its not a feature stop meming

**Comment by Spacedong** [comment]
i looked up "clawsed" on google and got no results u prick

**Comment by Spacedong** [comment]
look at THIS!! http://vgy.me/SsO7UQ.png

**Comment by Spacedong** [comment]
please someone fix it my OCD is destroying me

**Comment by oprayx73** [comment]
AGAGAGAG clawsed wtf

**Comment by Spacedong** [comment]
exactly

**Comment by Crystalwarrior** [comment]
Retarded, pls fix.
