### ISSUE TITLE
security lobby doors cannot be seen when opened

### ISSUE THREAD

**Issue by Spacedong** [HippieStationCode/HippieStation13#1376]
http://vgy.me/KDHMkg.png

ten out of fucking ten will we ever see a good update

**Comment by Crystalwarrior** [comment]
That's because the firelock frame's layer is higher than the opened doors, hiding them behind firelocks.

**Comment by Kilmannan** [comment]
My first ever attempt at a map. Will fix along with the lack of floor under window and brig door access.

**Comment by Spacedong** [comment]
tenouttaten
