### ISSUE TITLE
Ventcrawl & broken pipes.

### ISSUE THREAD

**Issue by Pyko1** [HippieStationCode/HippieStation13#138]
Not only you can ventcrawl as human using the cryopods.
The update also broke the pipes them self somehow.
Occasionally when you wrench a pipe to floor, it just vanishes.
Also I have seen gasses somehow pass over filters that are not on, and pipes just stopping transferring air until you manually delete part of it, and replace. When this happens the meters show error, like the pipes are empty and trying to wrench them does nothing, not even the message it has too much pressure.

**Comment by Cairo283** [comment]
Pipes vanishing when you wrench them down some times is a fairly long-standing bug. It seems to happen fairly regularly when attempting to place a pipe in an un-zoned area.

**Comment by HoaxIT** [comment]
Resolved.
