### ISSUE TITLE
spacecarp can somehow die in space

### ISSUE THREAD

**Issue by Spacedong** [HippieStationCode/HippieStation13#1389]
haven't seen this happen but around the white ship in arrivals there were some space carp just sitting there, instantly died out of the blue, no idea but I think it  can happen but rarely

the space carp weren't being attacked or anything, nobody was even in arrivals, they just fell over dead.

**Comment by Chronitonity** [comment]
Sounds like the ship hit them

**Comment by Spacedong** [comment]
nah they died after the ship docked they were just near it
