### ISSUE TITLE
some food recipes don't even work

### ISSUE THREAD

**Issue by Spacedong** [HippieStationCode/HippieStation13#1393]
what the fuck, try making margherita pizza or rice and pork or eggplant parmigaaaahn and it doesnt work at all, atleast according to our wiki

**Comment by oprayx73** [comment]
you can make custom pizzas by making dough,rolling it, microwaving THAT then adding items on that.. which might form into the rght pizzas if you add the ingredients that way

**Comment by Spacedong** [comment]
but its still broken with the microwave so its still a bug

**Comment by Spacedong** [comment]
also sausage doesn't work either, atleast according to tg.org wiki

**Comment by Chronitonity** [comment]
you use table crafting for recipes

**Comment by Spacedong** [comment]
then what the fuck is the point of hte microwave you gotta cook stuff not fucking use ur hands to heat up the food on a table

**Comment by Spacedong** [comment]
some stuff works and some stuff doesn't work at all its still a bug stop neglecting this

**Comment by Chronitonity** [comment]
for microwaving shit.


anyway not a bug

**Comment by Spacedong** [comment]
it is a bug look in the code its supposed to be microwavable

**Comment by oprayx73** [comment]
look at my fickign cock its supposed to be suckable but it just doesnt WORK

**Comment by Spacedong** [comment]
you can't make sausage at all either, via tablecrafting or microwave

**Comment by Spacedong** [comment]
its a fucking bug

**Comment by oprayx73** [comment]
get good at coding and fix it nig

**Comment by danhibiki** [comment]
https://github.com/HippieStationCode/HippieStation13/blob/e3a8f28255557e4afcabf2d53df64aca8e599a42/code/modules/food%26drinks/recipes/tablecraft/recipes_meat.dm#L184

**Comment by oprayx73** [comment]
rekt fuckinfag

**Comment by Spacedong** [comment]
I USED THAT AND IT DIDNT WORK stfu opray nigger olo

**Comment by Chronitonity** [comment]
Unless you wanna contribute to the disccusion, don't comment, don't shitpost.

http://puu.sh/lNd69/89a9e33cb5.png

http://puu.sh/lNdct/20e66df021.png

Anyway spacedong ya wrong, its not a big.

**Comment by danhibiki** [comment]
http://i.imgur.com/Hu50iH7.png u fukkin suk at chef m8

**Comment by afausnett** [comment]
please fix eggplant parmesiainan
