### ISSUE TITLE
teeth can embed

### ISSUE THREAD

**Issue by Spacedong** [HippieStationCode/HippieStation13#1397]
punched a catbeast out and his teeth embedded into me, is this fuckin intended

**Comment by Chronitonity** [comment]
Almost 100% sure its intended

**Comment by Spacedong** [comment]
wot teeth arent sharp

**Comment by Memendia** [comment]
cats have sharp teeth

**Comment by Memendia** [comment]
have you ever been bit by one?

**Comment by Spacedong** [comment]
no because I don't own a cat you fuckin weeb

**Comment by danhibiki** [comment]
>teeth arent sharp

Are you aware of the purpose of teeth?
