### ISSUE TITLE
bartender's shotgun can fit on his armor, negating the use of having to saw it off

### ISSUE THREAD

**Issue by Spacedong** [HippieStationCode/HippieStation13#1417]
pretty OP and unbalanced if you ask me, he can just whip it out and you're dead opposed to having to convince a doctor or cargo to saw it off

**Comment by Chronitonity** [comment]
thiiiiiiiiiiiiiis isnt a bug ahhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh

**Comment by doobiedoo23** [comment]
use the fucking git for BUGS, not things that piss you off spacedick

**Comment by Spacedong** [comment]
this is fucking dumb

**Comment by doobiedoo23** [comment]
i could say the same about you
