### ISSUE TITLE
Two Brig APC's start unwired, leading to power loss in the brig each round

### ISSUE THREAD

**Issue by Uqualm** [HippieStationCode/HippieStation13#1436]
Whoever made the new brig design forgot to place a few wires. Both the Brig Control APC and Brig APC are unwired. 

This is obviously a big issue. It makes playing the Warden impossible because a good 30 minutes into the round your base of operations is without power. It also disables every single recharger in the brig except for the one in the HoS office and the Gulag station.

**Comment by Spacedong** [comment]
fix this oh christ its horrible

**Comment by Kilmannan** [comment]
Fixed last PR.

**Comment by Uqualm** [comment]
I'm not sure you fixed the Warden's office APC, it seems like it's always red as well. Will double check. The Brig APC is fixed though.

**Comment by Uqualm** [comment]
Yep, Warden's APC is still unwired.
