### ISSUE TITLE
Light tiles are very bugged

### ISSUE THREAD

**Issue by Spacedong** [HippieStationCode/HippieStation13#1467]
Sometimes change to dark grey when clicked, sometimes don't change at all, etc.

**Comment by TDcoolguy300** [comment]
It's a function, and they were always buggy as fuck

**Comment by Carbonhell** [comment]
Dark grey means they're off..you can turn them on and off by clicking them with an empty hand

**Comment by Pyko1** [comment]
So, this was feature, right?

**Comment by TDcoolguy300** [comment]
It's pretty much a feature.

**Comment by Pyko1** [comment]
Closing since its a feature.
