### ISSUE TITLE
every now and then, a butt sprite will appear to the left of your screen

### ISSUE THREAD

**Issue by Spacedong** [HippieStationCode/HippieStation13#1478]
http://vgy.me/0R5Gp0.png

this has been happening since fucking rebase, please fix whatever's causing it

**Comment by Crystalwarrior** [comment]
Seems like it happens because of the fact that you can wear the butt on your head. Might have to do with that.

**Comment by Spacedong** [comment]
idk man

**Comment by DerptheStewpidGoat** [comment]
Ghost butt is watching.

**Comment by Carbonhell** [comment]
Did it happen again?

**Comment by Carbonhell** [comment]
If it happens again make another issue,i've not seen it since december.
