### ISSUE TITLE
You can't observe the nuke disk or singularity anymore.

### ISSUE THREAD

**Issue by Spacedong** [HippieStationCode/HippieStation13#1484]
The observe menu is the same as the jump-to menu, so its useless and you can't use it for observing singularity, supermatter, or the nuke disk, etc.

**Comment by Crystalwarrior** [comment]
Perhaps it can be brought back as Observe-object?

**Comment by Spacedong** [comment]
i support this ^

**Comment by Spacedong** [comment]
gonna close this cuz not a bug
