### ISSUE TITLE
blobs completely ignore armor

### ISSUE THREAD

**Issue by blobbernaut** [HippieStationCode/HippieStation13#1509]
https://github.com/HippieStationCode/HippieStation13/blob/7e8e4e70be2bf67c1be5800ef7fd0f66ff50efd6/code/modules/reagents/Chemistry-Reagents/Blob-Reagents.dm

you can see m.apply damage

for example
datum/reagent/blob/ripping_tendrils/reaction_mob(mob/living/M, method=TOUCH, reac_volume)
	reac_volume = ..()
	M.apply_damage(0.6*reac_volume, BRUTE)

it should be M.apply_damage(0.6*reac_volume, BRUTE, armor_block) or something similar.

Reason is because the blob's automatic attacks use that and base it on melee armor, but the controlled attacks completely ignore armor because they use a different formula entirely. Why the hell does one use biological protection and one use melee protection? it's inconsistent

**Comment by Carbonhell** [comment]
From what i see, this is one of the reagents the blob can use. It's the reagent causing brute damage to you,from inside your blood, so the armory isn't really supposed to help you anyhow. Regarding normal attacking, armor already applies i believe

**Comment by danhibiki** [comment]
This is less of a bug and more of a balancing thing, making the blob take armor values in account would weaken them ultimately when they can already have a bad time with a semi-decent crew. I'm not in favor of adding an armor check personally.

**Comment by Pyko1** [comment]
balance/feature not a bug
