### ISSUE TITLE
Not dying in crit

### ISSUE THREAD

**Issue by Pyko1** [HippieStationCode/HippieStation13#151]
For some reason, people don't seem to get enough oxygen damage to kill them when in crit.
They stop taking oxygen damage after they have 51, and then just lay there gasping.

**Comment by Crystalwarrior** [comment]
Yeah, I noticed this bug as well.
Honestly I have no idea why this happens, you should check the life(), handle_breath() and other procs.
I have suspicions that it's related to newcrit... However I remember it still happening before I even implemented that so.

Wait... I think I know why. Handle_breath() increases lose_breath by 1 when you're in crit, and instantly decreases it again. And if you're not conscious it won't decrease oxyloss in newcrit functions.
That's my suspicion, anyway.

**Comment by collinxchu** [comment]
This actually creates a funny effect wherein if you sleep while in incapacitated, you'll actually heal enough health to eventually come out of crit, but it reads you as actually in crit while sleeping, despite not taking the oxygen damage you should be to kill you.

**Comment by Cairo283** [comment]
Aye, I discovered the sleep thing the other day after getting into crit from Russians. Sleeping before you pass out automatically will heal you just enough to get up for about two steps before passing out again.

**Comment by Pyko1** [comment]
This bug seems to still be there.

**Comment by lcass** [comment]
The oxygen damage stop occuring when they hit -160 health , well that's atleast from what I've experienced.
