### ISSUE TITLE
Can't connect to the server.

### ISSUE THREAD

**Issue by KebabRemoval** [HippieStationCode/HippieStation13#1510]
Bug details:
As of the new hippie station update, my byond client cannot connect to the server as it get stuck on the, "Your game will begin shortly," screen. I haven't had this issue with any other servers and I have already tried everything including, running as admin, re installing, and turning off my firewall.

How to reproduce:
Joining the server.

Notes:
------

**Comment by danhibiki** [comment]
I dunno mate, this sounds particular specific but I'd like to try to help, is this still happening

**Comment by KebabRemoval** [comment]
Yep, still. I tried re installing, rebooting, and tinkering with byond settings. Nothing seems to work. Its only hippie station oddly enough.

**Comment by TDcoolguy300** [comment]
I have no idea on what could be preventing you from joining.

**Comment by KebabRemoval** [comment]
I'm thinking its the new update, but I could be wrong. I have never had this problem until now.

**Comment by TDcoolguy300** [comment]
I could link you to a Zipped older version of BYOND if you like

**Comment by nalarmg** [comment]
I highly doubt this is a code bug. It very much sounds like byond itself acting up for you.
