### ISSUE TITLE
Strained muscles keeps you fatigued forever.

### ISSUE THREAD

**Issue by Spacedong** [HippieStationCode/HippieStation13#1511]
You can't even get up, it just spams you with exhaustion messages.

**Comment by TDcoolguy300** [comment]
I need more info man, what caused strained muscles in the first place

**Comment by Spacedong** [comment]
It's a changeling ability.....

**Comment by Carbonhello** [comment]
It's a toggleable ability,you can toggle it on and off,if you leave it off you'll be fatigued forever

**Comment by Spacedong** [comment]
well can we get something that indicates that?

**Comment by danhibiki** [comment]
I mean... I think thats fairly obvious, doesn't it say as much in the description?

**Comment by Spacedong** [comment]
ok whatever
