### ISSUE TITLE
Nanomed Vending machine in the Brig is completely broken

### ISSUE THREAD

**Issue by Kierany9** [HippieStationCode/HippieStation13#1516]
I've heard people complain about it being broken before since it only let the security officer staffed at medbay use it but I've been unable to use it at all as the captain.

Coders please fix.

**Comment by TDcoolguy300** [comment]
This is a mapping issue, so i'll go ahead and report it to the mapper

**Comment by Kilmannan** [comment]
Where is this exactly? I've not touched any nanomeds just in case anyone's thinking I borked it during my brig redesign. Which would be a solid assumption given past performance.

**Comment by Kierany9** [comment]
It's in the brig's small medbay.

**Comment by doobiedoo23** [comment]
Fixed in #1533
