### ISSUE TITLE
Reinforced Hidden Door

### ISSUE THREAD

**Issue by Pyko1** [HippieStationCode/HippieStation13#153]
Reinforced Hidden Doors wont properly connect to reinforced walls, only to the normal ones.

**Comment by Cairo283** [comment]
The same happens with non-reinforced false-walls next to reinforced walls; They don't connect and look dumb.

**Comment by JustinBNewton** [comment]
Can confirm.
![](http://i.gyazo.com/88cd9ec636b93e8f067a70e65379c703.gif)

But oddly enough, they reinforced false walls connect to other reinforced false walls....

![](http://i.gyazo.com/47856e66a43af2176af3ffafe6d04b9b.gif)

**Comment by Pyko1** [comment]
So the r_walls are just not considered as walls by the false walls then.

**Comment by Carbonhell** [comment]
Fixed,can be closed
