### ISSUE TITLE
Glowshrooms light up when they are in a plant tray.

### ISSUE THREAD

**Issue by Spacedong** [HippieStationCode/HippieStation13#1535]
Being mushrooms, they need darkness to thrive, yet apparently this will halt their growth since they light up the tray tile a lot. I'm not sure how this works or if its intended but yeah.

**Comment by TDcoolguy300** [comment]
Well, nothing in the code states they need darkness, i've had no issues with growing mushrooms in bright light

**Comment by Spacedong** [comment]
Really? The wiki says they need darkness.

**Comment by danhibiki** [comment]
From the wiki 
http://i.imgur.com/1UGtDnJ.png

Please stop shitposting
