### ISSUE TITLE
Lings not flagged as antags when made with gold slime headslugs

### ISSUE THREAD

**Issue by Pyko1** [HippieStationCode/HippieStation13#1542]
I was dead, then.

The slime extract begins to vibrate violently !
Unforunate Luke has thrown the used slime extract.
The headslug plants something in Bix Nood's flesh!

After a while i was revived as monkey ling, but according to admins I was not flagged properly as an antag, and neither i had objectives. But i was still full fledged ling according to my skills.
So apparently goldslime spawned headslugs make non-antag lings from corpses,

![capture](https://cloud.githubusercontent.com/assets/12048747/12012377/dddb5a72-acf9-11e5-9ae9-fd79c657c681.PNG)

The round type was Traitorling, if that matters.

**Comment by banthebantz** [comment]
I've done this before and it isn't a glitch, the lings are just non antag.
