### ISSUE TITLE
Throwing someone into an electrified grille will not shock them.

### ISSUE THREAD

**Issue by Spacedong** [HippieStationCode/HippieStation13#1551]
Wow I tried to fucking do an execution move on a guy and the it just broke the grille and he got away. 

also the grille was electrified and POWERED , don't give me no bullshet

**Comment by Kokojos** [comment]
This happens only if the grille was going to break soon anyway. Not sure if issue.

**Comment by Kokojos** [comment]
Deemed non issue long ago. Reopen if I am wrong
