### ISSUE TITLE
DNA scanners (for genetics research) do not upgrade properly.

### ISSUE THREAD

**Issue by Spacedong** [HippieStationCode/HippieStation13#1569]
Taking them apart (as opposed to RPED) to put new parts in causes them to not register with the console next to them. There's no button to link the scanner back to the console. Multitooling/wirecutting did not work either. None of the mentors knew how either.

**Comment by TDcoolguy300** [comment]
I'll look into it, but on a cursory glace at the code, there's nothing to reassign the connected pods

**Comment by Pyko1** [comment]
partially dismantling and reconstructing the computer will most likely relink tho.

**Comment by TDcoolguy300** [comment]
Checked it out, it should be updating when you interact with the Computer itself
