### ISSUE TITLE
Tachyon doppler-array doesn't work.

### ISSUE THREAD

**Issue by Spacedong** [HippieStationCode/HippieStation13#1570]
Doesn't measure bomb size or say anything.

**Comment by TDcoolguy300** [comment]
Is it facing the right direction?

**Comment by Spacedong** [comment]
yep it faces the direction it spawns in

**Comment by Spacedong** [comment]
this still doesn't work

**Comment by TDcoolguy300** [comment]
Shrug

**Comment by Kokojos** [comment]
Probably using it wrong then since it worked in every of my tests.
