### ISSUE TITLE
Arivals security apc x2

### ISSUE THREAD

**Issue by Pyko1** [HippieStationCode/HippieStation13#1574]
There is 2 Security Checkpoint APC's at arrivals area.
![capture](https://cloud.githubusercontent.com/assets/12048747/12064787/aae5bb5c-afd4-11e5-8d7e-3d0e4bb5505d.PNG)
and 
![capture2](https://cloud.githubusercontent.com/assets/12048747/12064789/b4e0672e-afd4-11e5-8e59-18539af90241.PNG)

**Comment by Pyko1** [comment]
Also would be probably better if the arrivals checkpoint and arrivals hallway had their own apc's since there are lots of lamps and conveyor belts hogging power.

**Comment by Kilmannan** [comment]
Will do. Cheers for the spot.

**Comment by Kilmannan** [comment]
Fixed.
