### ISSUE TITLE
Prison Monitor in HOP Office doesn't have any cameras to jump to.

### ISSUE THREAD

**Issue by Spacedong** [HippieStationCode/HippieStation13#1590]
http://vgy.me/LM0ZeO.png

**Comment by XeonFaux** [comment]
Just tested this, works perfectly. Not a issue.

**Comment by danhibiki** [comment]
Well, that really asks how this specific bug happened then for sure.

**Comment by XeonFaux** [comment]
Possibly camera's were disabled? Or EMP'd?

**Comment by Kokojos** [comment]
Unable to reproduce, closing.
