### ISSUE TITLE
Wrong Door Access

### ISSUE THREAD

**Issue by Pyko1** [HippieStationCode/HippieStation13#1662]
These doors seem to have their required access set to none.

Eva maint
![eva](https://cloud.githubusercontent.com/assets/12048747/12376767/48657698-bd0d-11e5-8665-48beb9108618.PNG)
Law office
![lawoffice](https://cloud.githubusercontent.com/assets/12048747/12376766/4864996c-bd0d-11e5-9cd4-89ed3e8a353b.PNG)
Law office maint
![lawofficemaint](https://cloud.githubusercontent.com/assets/12048747/12376768/4866b8fa-bd0d-11e5-8d8b-587a1b995933.PNG)

Also not really sure if brig entrance sec room is really supposed to be accessible to lawyers.

**Comment by Nokington** [comment]
https://github.com/HippieStationCode/HippieStation13/pull/1635 This was supposed to fix this problem. God damnit

**Comment by Pyko1** [comment]
Sounds like someone is resolving conflicts by overwriting everything.

**Comment by Pyko1** [comment]
Fixed: https://github.com/HippieStationCode/HippieStation13/pull/1679
