### ISSUE TITLE
Genetics Skin color

### ISSUE THREAD

**Issue by Pyko1** [HippieStationCode/HippieStation13#1663]
Skin color does not seem to be carried over UI-Injectors, only hair style.
![bix](https://cloud.githubusercontent.com/assets/12048747/12378737/6e54f9e4-bd50-11e5-8802-14985c309c19.PNG)

**Comment by Spacedong** [comment]
lol no blacks allowed

**Comment by Pyko1** [comment]
Appears to be fixed with the revert.
