### ISSUE TITLE
Full body augmented people

### ISSUE THREAD

**Issue by Pyko1** [HippieStationCode/HippieStation13#1668]
Don't have butts, we need cybernetic butt augments!
This is a massive issue, while we are on it, make them loadable with chems that are ejected as smoke cloud on fart.

**Comment by danhibiki** [comment]
cmon bb you know this isn't for ideas

**Comment by danhibiki** [comment]
also bluespace butts are already in

**Comment by Pyko1** [comment]
Was more of questioning whether or not its an intended feature that you don't have butt if you get torso augment. Also it apparently also prevents you from getting cloned.

**Comment by danhibiki** [comment]
Ah I see, I misunderstood your issue. So torso implants removes butt.

**Comment by Carbonhell** [comment]
What the fuck,can anyone confirm this,because butt are different than chest,huh

**Comment by Spacedong** [comment]
this is probably fixed considering it was over a month ago, close this

**Comment by Gandalf2k15** [comment]
Its not
