### ISSUE TITLE
Traitor lings can't use holoparasites

### ISSUE THREAD

**Issue by Spacedong** [HippieStationCode/HippieStation13#1674]
but they can still buy them, fuck you

**Comment by Memendia** [comment]
Not a bug :^)

**Comment by Nebyab** [comment]
I can unironically say, that:
Its a feature

**Comment by Spacedong** [comment]
are you fucking kidding me, add a disclaimer, why can't they buy it

**Comment by Dragonbeon** [comment]
I agree, you guys should add a disclaimer. There's no way for traitor lings to know  they can't have holoparasites before it's too late, it's just a bother.

**Comment by XeonFaux** [comment]
Fixed, please close.
