### ISSUE TITLE
Area issue at genetics

### ISSUE THREAD

**Issue by Pyko1** [HippieStationCode/HippieStation13#1687]
Upper left corner of genetics is actually set as medbay area on the map.
Who even made the change forgot to set the areas properly.

![capture](https://cloud.githubusercontent.com/assets/12048747/12492060/0d4863e0-c087-11e5-9067-8497a924b58a.PNG)

**Comment by Nokington** [comment]
Question is, which mapper is to blame

**Comment by Pyko1** [comment]
Ill be making a fix tho once i get gitshit to update.

**Comment by Carbonhell** [comment]
Fix got merged,close
