### ISSUE TITLE
major map issue

### ISSUE THREAD

**Issue by Pyko1** [HippieStationCode/HippieStation13#1694]
While i cant seem to connect, the server itself. But it seems that something horrible has happened to the map.

![capture](https://cloud.githubusercontent.com/assets/12048747/12497507/d736a35c-c0a4-11e5-868b-79ef4af7fec7.PNG)
Anyone able to connect to confirm this is happening on live?

**Comment by XeonFaux** [comment]
Dan just fixed it I think
