### ISSUE TITLE
freezers use obscene amounts of power when upgraded

### ISSUE THREAD

**Issue by blobbernaut** [HippieStationCode/HippieStation13#1710]
how to reporoduce: put in super matter bins in a freezer and set the temperature to like 73, which is the mininum without even upgrading the lasers. 

It now uses power faster than the grid can actually add it to the APC. I suggest making freezers use power from the grid, like emitters. It'd give aspiring saboteurs a way to ghetto powersink the station, as well as not fuck medbay over when it's upgraded. 

Also, using tier 4 parts (quad ultra micro lasers, bluespace matter bins) it can take the gas temperature to below zero kelvin.

**Comment by TDcoolguy300** [comment]
WE HAVE GONE PAST ABSOLUTES IN THE WORLD OF SPACE STATION.

If we want to have it draw from the power grid we will need to modify some shit.

**Comment by neersighted** [comment]
If you're interested, I rewrote heaters and freezers as thermomachines over at TG; fixes the TCMB problem and a lot of the power consumption.

**Comment by coecoo** [comment]
Oh yeah, I noticed this as well. When upgraded with high power lasers, a heater went from absorbing around 500W to about 70000w.

Had to change cells about 2-3 times to get one canister with decent heat.

**Comment by Pyko1** [comment]
a feature I think, but should it be changed?

**Comment by blobbernaut** [comment]
Sure, got a link to the PR, neersighted?

**Comment by Gandalf2k15** [comment]
More of a balancing thing.

**Comment by Gandalf2k15** [comment]
Christ old, closing as its not an issue.

**Comment by blobbernaut** [comment]
No this is literally a bug. Nothing should consume more power than the rate
the grid can recharge the cell with. Don't close this.

**Comment by TDcoolguy300** [comment]
As this is a bug with SOMEONE forgetting to limit power consumption rates on upgraded equipment, i'm reopening it

**Comment by blobbernaut** [comment]
A guy mentioned thermomachines earlier, what are those and should we consider porting them?

**Comment by ArcLumin** [comment]
I noticed someone had upgraded a freezer, and it was acting like a powersink. You can literally use it as a powersink if wired up properly and upgrade it, and it will actually drain power FASTER than a sink. we're talking 250k + power usage, all with no TC cost

**Comment by GeneralGoose** [comment]
lol

**Comment by banthebantz** [comment]
I like how you can use them to break the game and stick infinite amounts of gas inside one canister with negative pressure.

**Comment by GeneralGoose** [comment]
i have a set up for atmos that uses broken pipes to fill canisters infinitely

**Comment by Pyko1** [comment]
You can also use filters to bypass pressure limits.

I once had 1/3 Plasma-Oxygen Mix around 10 GPa in a tank, I presume that could had prettymuch burned the whole station if released.

**Comment by ArcLumin** [comment]
For a game that was based on an atmospherics sim, atmos sure is broken

**Comment by Pyko1** [comment]
Sure is, back on nox days I was actually able to abuse atmos so hard that it would crash the mastercontroller. But since then, the atmos code has gotten at least slightly better.

**Comment by GeneralGoose** [comment]
its an feature

**Comment by Pyko1** [comment]
a bad feature or a coding oversight that equals to bug.
