### ISSUE TITLE
Your butt is full!

### ISSUE THREAD

**Issue by Pyko1** [HippieStationCode/HippieStation13#1714]
If you put food in your butt it seems to get consumed, but your butt is still full.

Bix Nood stuffs the donut into his own butt.
Bix Nood stuffs the donut into his own butt.
You start inspecting your ass!
There's nothing in here!
Your butt is full!

**Comment by Pyko1** [comment]
Also according to my butt vars.

Admin PM from-Kokojo: contents = /list (0)

**Comment by Crystalwarrior** [comment]
Happened to me as well when I stuffed a butt into my butt.

**Comment by JohnGinnane** [comment]
I'm going to look at this now

**Comment by JohnGinnane** [comment]
Okay so if you stick food items up your butt should they be consumed?

**Comment by JohnGinnane** [comment]
After a little testing I found that pills you stick up your ass are also consumed. I might leave this as is because rectal insertion is a valid way to consume medication

**Comment by JohnGinnane** [comment]
I've spent some time on this and what I have so far is a "is_metabolisable" flag present in /datum/reagent. The plan was that the reagents in the item in your ass are set to not metabolise so when on_mob_life procs it won't "digest" the items. This flag is set to true by default and when you put a food type item in your ass it would set the reagents to false effectively making the food stay the same until you remove the item.

I've having some difficulty with when the item is placed in your butt at the moment though.
