### ISSUE TITLE
Auto admin for test server

### ISSUE THREAD

**Issue by Pyko1** [HippieStationCode/HippieStation13#1717]
Seems to need you to copy admin ranks to config folder for it to work.

**Comment by danhibiki** [comment]
i don't think this is an issue, its always been that you've had to copy the config files in.

**Comment by XeonFaux** [comment]
Not an issue, can't become a rank that isn't defined. Close please.

**Comment by Pyko1** [comment]
Yeah I meant its silly that the ranks arent there to begin with if we have a system that is supposed to make you automatically admin on test server, but yet it requires you to copy around files.

**Comment by nalarmg** [comment]
Non-issue. Intended. Just copy the files over before starting the server.
