### ISSUE TITLE
Broken Powernet in Templates

### ISSUE THREAD

**Issue by Pyko1** [HippieStationCode/HippieStation13#1720]
It seems the Powernet is completely broken on templates when you upload em.

Maybe the way they are created does not properly build powernets?
Also the plating under tiles seem to be vacuum for some reason.

**Comment by TDcoolguy300** [comment]
I'll look into it

**Comment by Pyko1** [comment]
I assume its fixed now?

**Comment by TDcoolguy300** [comment]
It isnt exactly fixed, but it's working better than before

**Comment by Pyko1** [comment]
any better now?

**Comment by Carbonhell** [comment]
Fixed in some pr, cables had no powernet
