### ISSUE TITLE
Cant open Air alarm wires GUI?

### ISSUE THREAD

**Issue by Pyko1** [HippieStationCode/HippieStation13#1731]
at least i seem to be unable.

**Comment by TDcoolguy300** [comment]
I was able to open it, not sure whats your problem

**Comment by ArcLumin** [comment]
tgUI a shit. Why can't we use unfancy, simple UI?

**Comment by Pyko1** [comment]
Well at least for me nothing happens if i try to click air alarm with wirecutters when I have opened it with screwdriver.

**Comment by ArcLumin** [comment]
Try clicking on it with an open hand first. Works fine for me

**Comment by Pyko1** [comment]
nope, nothing, I can only see the normal ui, even tried relogging.

**Comment by ArcLumin** [comment]
Can you specify which exact air alarm? I'll test it out later. I've seen issues like this pop up when two air alarms are stacked on each other

**Comment by Pyko1** [comment]
so far any air alarm i have tested this round.

**Comment by ArcLumin** [comment]
Gotcha, I'll try to replicate it later

**Comment by Pyko1** [comment]
and does not seem like window out of screen as the main screen keeps focus.

**Comment by ArcLumin** [comment]
Okay, been trying all day to see what I could possibly do to replicate this issue, and I can't seem to. Each time, the wiring shows up

**Comment by ArcLumin** [comment]
Seems to be a non-issue now with the revert. Close?
