### ISSUE TITLE
oocbanning is severely broken

### ISSUE THREAD

**Issue by Spacedong** [HippieStationCode/HippieStation13#1774]
oocbanning for a minute, 2 minutes, whatever, it doesn't matter, its always permanent and broken, admins have trouble unbanning from it and its just a mess, DO NOT OOCBAN

**Comment by Nokington** [comment]
Its because unban don't happen until the next round.

**Comment by Spacedong** [comment]
it does that for no matter how long you set it, you can't unban either.

**Comment by Nokington** [comment]
Because unbans don't go through until next round as I said

**Comment by Spacedong** [comment]
maybe you could tell limed00d that since he banned me for 1 minute yet it lasted THE ENTIRE ROUND >:^(

**Comment by nalarmg** [comment]
Not a bug. This has been a part of the jobban system for a very, very long time.
