### ISSUE TITLE
Sterile masks cannot be used as internals.

### ISSUE THREAD

**Issue by Spacedong** [HippieStationCode/HippieStation13#1793]
I remember this being a feature where you could use it as internals, does this make it impossible to gain 100% immunity to a virus?

**Comment by Pyko1** [comment]
I believe it does indeed protect from airborne viruses.

**Comment by Kokojos** [comment]
They are not meant to be used as internal, and AFAIK, never have been.

**Comment by Nokington** [comment]
Pretty sure this is working as intended

**Comment by Nebyab** [comment]
They aren't internals. Its a surgical mask, not an O2mask or a Gas Mask. This is working as intended and not a bug.
