### ISSUE TITLE
Brig Nanomed is still nonfunctional.

### ISSUE THREAD

**Issue by Spacedong** [HippieStationCode/HippieStation13#1799]
Sec officers can't use it at all.

**Comment by Pyko1** [comment]
If you have medbay access you should be able to use it, it was more of meant to be a place where you can have medic treat prisoners without taking them to medbay. (Like anyone ever gives prisoners any kind of medical care.)

**Comment by Carbonhell** [comment]
Should sorta have sec officers in access list too,so they can take the meds out of it, it's supposed to be an emergency nanomed which holds less healing things

**Comment by Pyko1** [comment]
Last time I checked it was full stocked with all the things as medbay venders have.
For emergency there is first aid-kit.

**Comment by Spacedong** [comment]
yeah but medical doctors dont have access to brig, and officers don't have access to the nanomed, makes no sense, also the box of hugs in perma has nothing in it, not sure if intentional?

**Comment by Pyko1** [comment]
Don't know about the hug box, But when I mapped the prison medbay, my intention was to make it  more of an extension of medbay where a doctor can be invited, if the sec needs one. Never really wanted to make sec too independent of medbay.

**Comment by blobbernaut** [comment]
HOS can access it.

**Comment by TDcoolguy300** [comment]
Thats because the HoS spawns with Medbay access

**Comment by blobbernaut** [comment]
I know that's why but he can access it. Just ask him if you need it.

**Comment by Spacedong** [comment]
except hos is always out powergaming and revelling in the fact everyone hates him to notice you doing your job

**Comment by JustinBNewton** [comment]
I personally would like to see sec officers allowed to use it, but having it fully stocked would be a mistake... Leaves generally no reason for sec officers to even deal with medbay ever.

**Comment by Pyko1** [comment]
feature
