### ISSUE TITLE
Shadowling Abilites & Balance

### ISSUE THREAD

**Issue by Pyko1** [HippieStationCode/HippieStation13#1808]
This is not a bug, more of a balance issue.

Currently shadowlings seem to be able to shadow walk to full bright areas, paralyze, use the freeze ability, and shadow walk away before you can really do anything, and then rinse and repeat until you are dead.

I'm not sure if some abilities should check for darkness or, of lights should slowdown cooldowns. But currently it seems as long as you know how to use your skills as shadowling, its almost impossible to die, unless you get mobbed right at the start.

Also atleast according to my observation its extremely rare for shadowlings to lose.

**Comment by danhibiki** [comment]
Don't use the issue track for balance discussion, we have three other mediums you could use, the slack, forums, or the trello.
