### ISSUE TITLE
Templates and special transparent turfs

### ISSUE THREAD

**Issue by Pyko1** [HippieStationCode/HippieStation13#1812]
Special partially transparent turfs that have different turf below them seem to break on templates.

![capture](https://cloud.githubusercontent.com/assets/12048747/12853423/b242dcac-cc3c-11e5-8189-b93438dd0d7d.PNG)

**Comment by Kokojos** [comment]
@TDcoolguy300

**Comment by TDcoolguy300** [comment]
Will look into it

**Comment by Spacedong** [comment]
is this fixed please check

**Comment by Gandalf2k15** [comment]
@TDcoolguy300 any progress?

**Comment by Spacedong** [comment]
this is from february what is going on with this @tdcoolguy300

**Comment by Carbonhell** [comment]
@TDcoolguy300 pls
i think the issue might be because Instantiate doesn't get called?It's a proc called only when an atom is spawned in the map by the mapmaker,idk

**Comment by Pyko1** [comment]
Still happening?

**Comment by Spacedong** [comment]
this was fixed, close.
