### ISSUE TITLE
Templates & Machinery Power

### ISSUE THREAD

**Issue by Pyko1** [HippieStationCode/HippieStation13#1813]
Pasted teleporters seem to spawn unpowered, manually deconstructing and reconstructing them fixes it. Also some other machiner also seem to be unpowered when pasted with templates.

Manually doing Atom ProcCall "power_change" seems to fix them.
Maybe automatically do it for all machinery after everything has been pasted?

**Comment by Kokojos** [comment]
@TDcoolguy300

**Comment by TDcoolguy300** [comment]
I believe it may be because it's not generating them in the correct order, i'll go ahead and make machinery spawn last

**Comment by Carbonhell** [comment]
issue found,powernet is not being generated, just need to call makepowernets()

**Comment by Carbonhell** [comment]
Fixed
