### ISSUE TITLE
Riot armor does not impair movement.

### ISSUE THREAD

**Issue by Spacedong** [HippieStationCode/HippieStation13#1824]
http://vgy.me/P2Zf65.png

rip, so much for that

**Comment by Pyko1** [comment]
I believe it was removed since no one used them because of slowdown.

**Comment by Spacedong** [comment]
nah I'm pretty sure this was /tg/'s changes from rebase but I could be wrong

**Comment by Pyko1** [comment]
The amount of protection it provides is quite a damn lot for no drawbacks.

**Comment by blobbernaut** [comment]
it has almost no protection from anything but melee

**Comment by Spacedong** [comment]
yeah but it has 90% protection from melee which is pretty much the entire station's weapons besides the armory

**Comment by blobbernaut** [comment]
riot armor is pretty much the only counter to horror form changelings though

**Comment by Spacedong** [comment]
ye but riot armor should be slow its not like you need to be fast to fight horror form changelings, besides walking away

**Comment by Nebyab** [comment]
it should be impairing movement honestly

at the very least it incongruous with the examine text

**Comment by Nokington** [comment]
Fix it

**Comment by Carbonhell** [comment]
close
