### ISSUE TITLE
The crusher doesn't recycle small items into metal/glass

### ISSUE THREAD

**Issue by Spacedong** [HippieStationCode/HippieStation13#1831]
things get destroyed but nothing comes out, is this a bug?

**Comment by Carbonhell** [comment]
if whoever coded crusher did it well it should base the amount and the choice of materials on the item's materials list, so i guess the issue is that said items had no materials set

**Comment by Spacedong** [comment]
yeah but it doesn't make any metal/glass no matter what item you put in

**Comment by Pyko1** [comment]
We should add some basic recycle crap. 
Ie. 
Toolbox/tools 0.5 metal
Empty bottles/shards 0.5 glass,
Paper 0,1 cartboard
Ian 1 corgi pelt
Admin 1 sheet of Cuck

**Comment by ArcLumin** [comment]
>Admin 1 sheet of Cuck
Can we make chron mechs with these?

**Comment by TDcoolguy300** [comment]
If i recall correctly, it doesnt give a shit about the material it's made out of, it will just make some glass and metal when you feed it.

**Comment by Pyko1** [comment]
So a feature?

**Comment by Spacedong** [comment]
not a feature, i've honestly never seen it produce metal/glass after rebase even after feeding it hundreds of shit
