### ISSUE TITLE
syndicate shuttle walls are deconstructable

### ISSUE THREAD

**Issue by blobbernaut** [HippieStationCode/HippieStation13#1837]
apply welder to syndicate shuttle

congratulations it's easier to get into than the armory, captain's office, etc.

**Comment by Nokington** [comment]
This should be fixed imo because its pretty shit to have your nuke stolen the moment you hit the station.

**Comment by ArcLumin** [comment]
Or, you can have a nuke op protect the nuke. Or not put the ship in such an obvious location as below the singulo or above the armory

Still, it's a balancing issue. Putting one nuke op on guard duty does lower the effectiveness of the team as a whole. But the best way to counteract this? Just bring the nuke with you. OR put it's bolts down, it has bolts, in case you didn't know.

**Comment by Pyko1** [comment]
Or you can pull the tile in to shuttle bridge where its in between of 4 turrets.

**Comment by JustinBNewton** [comment]
Its already up in the shuttle bridge as of a few hours ago. At least I think it is at round start...

Regardless, thats a quick fix..

**Comment by Nebyab** [comment]
dumb and stupid

walls used to be indestructible for a reason
though not a bug

**Comment by JustinBNewton** [comment]
not a bug according to heads
