### ISSUE TITLE
shadowling cold air power gives you enough frost oil to crit

### ISSUE THREAD

**Issue by blobbernaut** [HippieStationCode/HippieStation13#1838]
it should be CC, not a death sting. It will even crit a person after you convert them. They already have AOE damage in the form of the drain life ability.

Even worse, hardsuits/spacesuits do not protect against it, because even though "a wave of shockingly cold air engulfs you" it is actually frost oil injection. Why? Shitty coding, that's why. 

An easy fix would be a new chemical where their body temperature is floored to just above the threshold for burn damage, rather than just lowering it forever until it's gone, and dealing a fixed, instant amount of burn damage, say, 40, reduced to 20 if you're wearing winter coat / winter boots, and reduced to 0 if you're wearing a spacesuit / hardsuit. 

It can also be used while the shadowling is stunned.

**Comment by Pyko1** [comment]
Yeah this fucks you up so hard, even if you manage to fight off the shadowling, and he never even managed to touch you.

**Comment by trifornt-tinfornt** [comment]
Most sec officers who wear armor don't know that being affected by frost oil would end up killing you as the armor has cold tempering that actually makes cold linger. It's why Cyrosting is always referred to as "OP" by sec players.
If you want to survive, take it off. Besides that I haven't gotten a single kill with the frost oil as a Shadowling.

**Comment by Pyko1** [comment]
It's pretty deadly even without anything that protects from cold, if they just shadow walk in, paralyze, freeze and shadow walk out. And then rinse & repeat. Even if you had all the guns and flares in the world, there is nothing you can really do.

**Comment by Nebyab** [comment]
It does inject a bit too much frost oil, but this is more of a balance issue than a bug

**Comment by Pyko1** [comment]
not a bug
