### ISSUE TITLE
Poster object in mapping has no distinction between nanotrasen and contraband.

### ISSUE THREAD

**Issue by Spacedong** [HippieStationCode/HippieStation13#1848]
Poster objects only roll contraband posters when placed on the map. All the posters in Security and Arrivals are thus syndicate posters and look terrible.

**Comment by Cherkir** [comment]
I can check this out

**Comment by Cherkir** [comment]
nevermind I can't even find where the fuck posters are in the code, apparently the text "poster" is neverused lmao

**Comment by Cherkir** [comment]
Nevermind again, do you know if the correct names and descriptions show up in examine fam?

**Comment by TDcoolguy300** [comment]
The idea is that all posters uses the same object, but with overlays and shit. The default poster is an empty variant and will randomize on spawn. All we need to do is create a new object for /obj/structure/sign/poster with official = 1

**Comment by TDcoolguy300** [comment]
Oh, and the code is located in contraband.dm somewhere near line 150

**Comment by Cherkir** [comment]
`/obj/structure/sign/poster/New(serial,rolled_official)
	var/stored_location = loc
	serial_number = serial
	official = rolled_official
	if(stored_location == loc)
		if(!official)
			serial_number = rand(1, NUM_OF_POSTER_DESIGNS)	//This is for the mappers that want individual posters without having to use rolled posters.
		if(official)
			serial_number = rand(1, NUM_OF_POSTER_DESIGNS_LEGIT)
	if(!official)
		icon_state = "poster[serial_number]"
		name += contrabandposters[serial_number][POSTERNAME]
		desc += contrabandposters[serial_number][POSTERDESC]
	else if (official)
		icon_state = "poster[serial_number]_legit"
		name += legitposters[serial_number][POSTERNAME]
		desc += legitposters[serial_number][POSTERDESC]
	..()`

I made this but I have no fucking idea if it works

**Comment by TDcoolguy300** [comment]
Just compile it and look at it in the map editor

**Comment by Cherkir** [comment]
Also I think I misread this issue, I was under the impression that contraband posters only rolled syndicate icons

**Comment by TDcoolguy300** [comment]
Ah no, he's complaining that Contraband posters occasionally spawn in place in some of the official ones at Security

**Comment by Cherkir** [comment]
Alright then this is an easy fix, I'll PR it after eating food if you aren't going to.

**Comment by Spacedong** [comment]
no, there are no official ones at security, it always rolls contraband to my knowledge

**Comment by Cherkir** [comment]
addressed in #1849

**Comment by JustinBNewton** [comment]
Fixed according to @Cherkir
