### ISSUE TITLE
Handcuffs and owl hardsuit?

### ISSUE THREAD

**Issue by Pyko1** [HippieStationCode/HippieStation13#1855]
This is   Peter Harison!
He is wearing   an engineering hardsuit helmet on his head.
He is wearing   an engineering hardsuit.
He is carrying   an air tank on his engineering hardsuit.
He has   a satchel on his back.
**He is holding   an owl hardsuit in his left hand.**
**He is   handcuffed!**
He has   a toolbelt about his waist.
He is wearing   Peter Harison's ID Card (Cargo Technician).
He has minor bruising.
He is severely malnourished.

**Comment by Pyko1** [comment]
He got stunned, and cuffed, yet he is somehow still carrying that thing around on his hand.

**Comment by Pyko1** [comment]
Apparently cursed. Even tho that makes this a balancing issue when worn really, since that pretty much means you can only remove backpack from him, while he should be still able to swap his own gear as he wishes, besides the  owl hardsuit.

**Comment by ArcLumin** [comment]
That's the tradeoff the hardsuit has; you can't equip anything else but the owl hardsuit, but nobody can strip you or check your pockets. Another disadvantage being it's impossible to have surgery done, or for someone to cryo you if you're in travel mode. I think that the cursed nature of the item makes it balance out nicely.
