### ISSUE TITLE
Empty tasers display 1 shot left on the player's sprite.

### ISSUE THREAD

**Issue by Spacedong** [HippieStationCode/HippieStation13#1859]
http://vgy.me/cyKIu6.png

**Comment by yacobm8** [comment]
Working on it now and it also seems to only bug out when you have 2 shots in the taser.

When charged to 2 shots it sometimes only fires 1 shot. (Possibly if you only just charge it to 2 shots instead of towards the end of the charge of 2 shots).

It leaves the taser empty in your hand but, on your character in game it appears to have 1 shot left.
Here's a video of the bug
https://www.youtube.com/watch?v=liWhm5ouSv0&feature=youtube_gdata

**Comment by yacobm8** [comment]
This bug also affects all other energy weapons in that when they are emptied of ammo they wont flash to show they are out of ammo I should have a pull request up tomorrow for this

**Comment by Kokojos** [comment]
I think it's mostly their powercell not being exactly 0, but between 1 and the energy neeeded to shoot (100)

**Comment by yacobm8** [comment]
Hey Kokojos, I've fixed the problem it was a problem with overlays. I'm unable to get github to work though on my desktop. I've tried to upload my new files to my forked version but I don't know why it's not working. Could i give you the files I've changed and you take a look?

**Comment by Kokojos** [comment]
If you give me the correct files plus a changelog, I could PR it for you by tomorrow.

Otherwise sure I can take a look but Im no expert, especially in github.

**Comment by yacobm8** [comment]
Okay, no problem I'll write a changelog now. How do you want me to send you the files?

**Comment by Kokojos** [comment]
My email is in my profile.

**Comment by yacobm8** [comment]
So I just got emailed back from github support who told me how to get around the issue I was having (great timing). I've uploaded the change to mine now and will write a change log and do the PR :) Thanks for offering to help me out

**Comment by yacobm8** [comment]
I've proposed a fix for this in pull request #1878

**Comment by Carbonhell** [comment]
Tasers are fuckingly weird, a guy's taser's cell got its charge reduced to 50 causing it to show up as with 1 charge left but not being able to shoot,tasers are weird

**Comment by Carbonhell** [comment]
@Spacedong try this

**Comment by Gandalf2k15** [comment]
This bug was apparently fixed. http://i.imgur.com/wxA8a25.png

**Comment by Kierany9** [comment]
This bug was fixed
