### ISSUE TITLE
Coloring items just changes the fucking RGB and keeps the name

### ISSUE THREAD

**Issue by Spacedong** [HippieStationCode/HippieStation13#1873]
for example white shoes will still be called white shoes the fucking overlay wiill just be colored red, it looks like fucking shit I hate /tg/ jesus christ why this is so broken

**Comment by Pyko1** [comment]
More of a feature, a bad feature.

Someone should probably change icon_state of basic shoes and uniforms and other things that have wide array of differently colored icons.
Instead of just changing color var.
