### ISSUE TITLE
Emitters stop working after the engineer SMES units are destroyed.

### ISSUE THREAD

**Issue by Spacedong** [HippieStationCode/HippieStation13#1884]
I think this is the case since emitters don't seem to be able to work even when they're connected to wires coming from an APC with power. Anyone know why this is?

**Comment by Pyko1** [comment]
They need a powered wire to work, and APC's don't power wires, they only drain.
You need to have SMES or some kind of generator powering the wire the emitter is connected.

As far as I know, this is working as intended.

**Comment by TDcoolguy300** [comment]
This is why Engineering has a PACMAN generator, to kickstart the whole network. The collectors should be throwing out enough juice to maintain the emitters
