### ISSUE TITLE
drying rack has a weird description

### ISSUE THREAD

**Issue by Spacedong** [HippieStationCode/HippieStation13#1898]
http://vgy.me/771tSG.png

ya ok fam drying racks keep things cold gotcha

**Comment by Pyko1** [comment]
I guess i could change this in to something more proper, something like "*Used to dry plants, and to tell everyone that spacedong is a cuck."

**Comment by Spacedong** [comment]
id do it myself if i werent doing something else my man

**Comment by Pyko1** [comment]
forks!

**Comment by Spacedong** [comment]
no I mean im just too fucking lazyyyyy

**Comment by Pyko1** [comment]
hence "Used to dry plants, and to tell everyone that spacedong is a cuck." is proper.

**Comment by Nokington** [comment]
yes change it to: spacedong is a cuck
