### ISSUE TITLE
Cant close GUI of destroyed container

### ISSUE THREAD

**Issue by Spacedong** [HippieStationCode/HippieStation13#1903]
having the backpack or toolbox HUD open and having your stuff burned then regenerating as a changeling will leave it permanently there

http://vgy.me/bkho0B.png

EDIT: in theory this could also be if you were regenned with a healing staff too but im not sure

**Comment by Earthykiller127** [comment]
This shit happens so many times to me, and it doesn't even matter if you're a changeling.

**Comment by Pyko1** [comment]
Should be an easy fix to add a check/force close if the container is destroyed.
