### ISSUE TITLE
cable restraints sprites are colored weird

### ISSUE THREAD

**Issue by Spacedong** [HippieStationCode/HippieStation13#1908]
http://vgy.me/0RCCXp.png

happens with every color, same sprite for all

**Comment by Spacedong** [comment]
what is going on can someone provide an explanation why this is happening

**Comment by Pyko1** [comment]
I have a hunch, checking it now.

**Comment by Pyko1** [comment]
You used the cables from the youtool vender, right?
Not the ones from art storage?

**Comment by Spacedong** [comment]
nope, those are from art storage, it doesn't matter what kind of cables or where they come from

**Comment by Pyko1** [comment]
![capture](https://cloud.githubusercontent.com/assets/12048747/13232506/19aa629c-d9b8-11e5-90f6-c314fad12ab9.PNG)
For some reason this is the icon for red cable cuffs, and the other issue is the code seems to usually fail transferring the color from cable coil to the cuffs.

**Comment by Spacedong** [comment]
why did this happen all of a sudden? it wasnt like this a few days ago and nobody changed the sprite

**Comment by Pyko1** [comment]
Looks like it somehow got messed up when HoG icons were updated to the file.

**Comment by Pyko1** [comment]
But that still does not solve the issue that cable ties color picker seems to fail most of the time.

**Comment by Carbonhell** [comment]
i'll check
