### ISSUE TITLE
trying to pump a canister into virology's systems doesn't work

### ISSUE THREAD

**Issue by Spacedong** [HippieStationCode/HippieStation13#1910]
title

**Comment by Pyko1** [comment]
Seems to work perfectly fine.

![capture](https://cloud.githubusercontent.com/assets/12048747/13205372/69fbe046-d8ef-11e5-8bd6-ee95aca956c2.PNG)

**Comment by Spacedong** [comment]
this did not work on my end, I pumped N2O and did the valve, nothing. no pipes were broken either.

**Comment by McBawbaggings** [comment]
You didn't forget to sabotage the air alarm right?

**Comment by Pyko1** [comment]
Close the upper valve, open lower valve, connect canister and sabotage the alarm inside virology, as that air alarm in the atmos closet is not for virology.

**Comment by Spacedong** [comment]
damn I thought the air alarm in there was for virology, whats it there for anyway?
