### ISSUE TITLE
you can strip defib from someones back, but the paddles stay.

### ISSUE THREAD

**Issue by Pyko1** [HippieStationCode/HippieStation13#1911]
![capture](https://cloud.githubusercontent.com/assets/12048747/13206337/b6798300-d904-11e5-8726-326f0b59d286.PNG)

**Comment by trifornt-tinfornt** [comment]
bloody bone jones
Also yes, as the victim of this I can confirm.

**Comment by Pyko1** [comment]
Also it seems that he has also lost the paddle on his left hand while right one is still wielded.
So this might be https://github.com/HippieStationCode/HippieStation13/issues/908 which was fixed before rebase.

**Comment by Carbonhell** [comment]
Easy fix @Spacedong fix it

**Comment by Carbonhell** [comment]
oh john already took it
