### ISSUE TITLE
going to the derelict with the nuke op ship counts for Total Annihilation and not nuke op victory

### ISSUE THREAD

**Issue by Spacedong** [HippieStationCode/HippieStation13#1912]
title, they apparently still die there with the crew

**Comment by Pyko1** [comment]
Seems like a feature.

Blowing off the nuke on outside of Z1 makes it a draw.
`ticker.mode.station_was_nuked = (off_station<2)	//offstation==1 is a draw. the station becomes irradiated and needs to be evacuated.`

So, I assume the syndies also get radiated if they loiter around.
At least the code seems to do perfectly fine what it was intended to do.
`ticker.mode:syndies_didnt_escape = (Shuttle && Shuttle.z == ZLEVEL_CENTCOM) ? 0 : 1`
