### ISSUE TITLE
Brain rot

### ISSUE THREAD

**Issue by Pyko1** [HippieStationCode/HippieStation13#1915]
It keeps making braindamage even after cured?

**Comment by Pyko1** [comment]
Confirmed by admin, braindamage keeps ticking even when the brain rot is cured from me.

**Comment by McBawbaggings** [comment]
Ling panacea wasn't curing disease either properly it seems.

**Comment by Pyko1** [comment]
seems like datum/disease/brainrot/stage_act() does not properly stop even if its cured.

**Comment by Kokojos** [comment]
Unable to reproduce at all. Gave it to myself three times, cured it three times with manitol, and it fixed it the three times, braindamage in full.

Closing

**Comment by Pyko1** [comment]
was that normal brain rot or advanced disease?

If I recall correctly we had normal brain rot going, and some advanced disease as well.
