### ISSUE TITLE
syndie cyborg lmg is always stuck on semi-automatic

### ISSUE THREAD

**Issue by Spacedong** [HippieStationCode/HippieStation13#1916]
no UI button to turn it to a different fire rate or anything

**Comment by Pyko1** [comment]
maybe it does not have any other firing modes?

**Comment by Spacedong** [comment]
it should because you need to rapidly clickclickclickclickclickclickclickclickclickclick and it hurts your fingers just have an automatic option button jeeez

**Comment by Pyko1** [comment]
Still, not really a bug. But should be easy to do, even tho then the damage should probably be lowered if the gun is changed to fire bursts.
