### ISSUE TITLE
Motivational posters spawn in contraband posters when placed on a wall

### ISSUE THREAD

**Issue by Spacedong** [HippieStationCode/HippieStation13#1990]
title

**Comment by carlarc** [comment]
you mean when you use wirecutters on a poster?

**Comment by carlarc** [comment]
i don't think so, i distinctly remember putting up syndigun and esword posters.

**Comment by Spacedong** [comment]
if you cut down the motivational posters in security and put them back up again they appear as contraband posters

**Comment by Pyko1** [comment]
So they just give you wrong poster type when you cut them down?

**Comment by Kierany9** [comment]
Cannot replicate.

https://www.dropbox.com/s/o9h0bxs97vbx8tq/Desktop%2006.18.2016%20-%2013.11.17.02.mp4?dl=0
