### ISSUE TITLE
botany bottles can have a transfer rate of 1 and 2

### ISSUE THREAD

**Issue by Spacedong** [HippieStationCode/HippieStation13#1998]
pretty sure the dropper is meant to be used for minute measurements and bottles shouldn't have transfer rates of 1, they're usually 5.

**Comment by Pyko1** [comment]
Feature, maybe it is somekind of measuring bottle.

**Comment by Pyko1** [comment]
At least codewise it is working perfectly fine.

**Comment by Pyko1** [comment]
not a bug
