### ISSUE TITLE
ambrosia deus rollies do not contain the healing contents of it

### ISSUE THREAD

**Issue by Spacedong** [HippieStationCode/HippieStation13#1999]
only nicotine and space drugs

seriously fix this fucking cigar/cigarrete transfer and shit its so bugged 

also, eating ambrosia deus gives you the healing chems

**Comment by Pyko1** [comment]
I recall they do contain the reagents, but the transfer amount on cigs is just so small that it does not do anything.

**Comment by Spacedong** [comment]
exactly this is a problem for cigars/cigarretes, make the transfer amount way bigger

**Comment by Kierany9** [comment]
The transfer ammount for cigs is absolutely tiny. You need 15u of chems in the cigar for a 0.2u dose IIRC, making injecting them with anything mostly useless.

**Comment by Spacedong** [comment]
increase it by tenfold please, maybe even higher, cigars should have a massive transfer rate tbh

**Comment by Spacedong** [comment]
newer issue is up about this
