### ISSUE TITLE
Drones can be massively spammed with power alarms.

### ISSUE THREAD

**Issue by Spacedong** [HippieStationCode/HippieStation13#2025]
They also have no options to turn the alerts off and so it leads to massive chat spam.

**Comment by Carbonhell** [comment]
power alarms?What do you exactly mean

**Comment by Pyko1** [comment]
I assume he means the alerts that silicons gets when power failures happen.

**Comment by Pyko1** [comment]
half tempted to call this a feature as its the same for ai/borgs as far as i know

**Comment by Spacedong** [comment]
cant we have an option to turn it off tho
