### ISSUE TITLE
Turrets still stay on even after being shut off via turret control.

### ISSUE THREAD

**Issue by Spacedong** [HippieStationCode/HippieStation13#2027]
never seen this bug before

**Comment by Spacedong** [comment]
trying to turn them off manually doesn't work either

**Comment by doobiedoo23** [comment]
Last time I saw this it was a traitor AI immediately turning them on once they were turned off and a guy ahelped complaining about it, so maybe you had the same problem?

**Comment by Spacedong** [comment]
I was an AI one round and I tried turning the stun turrets off in my upload and they didn't turn off. Clicking the on button manually on them didn't do anything either. It didn't even switch to off.

**Comment by Pyko1** [comment]
would be neat if someone could confirm this is a thing on the server.

**Comment by Spacedong** [comment]
I tried it on the server lad

**Comment by Pyko1** [comment]
I cant reproduce it at least.

**Comment by Kokojos** [comment]
Can't reproduce it either.

**Comment by carlarc** [comment]
i remember this happening 3 rounds ago

**Comment by Pyko1** [comment]
still gotta be able to reproduce it to confirm and to fix

**Comment by trifornt-tinfornt** [comment]
"not confirmed"
It just happened last round, which was a malf. He set his turrets on lethal yet they acted like they were shot with an ion gun (which they never were) and the turrets endlessly shot stun shots. When he turned them off, they still shot.
This is a real bug.

**Comment by Pyko1** [comment]
Been testing around, only way I have so far been able to make this happen is to emp the turrent.

Are you guys 100% sure that no one used emp nades/ion/singularity/etc near it?

**Comment by Spacedong** [comment]
this is still a major bug and still happening, what the fuck?

**Comment by Pyko1** [comment]
possibly not even bug.

So far only way to cause this that I have found causign this has been EMPing the turret control in a way or an another.

**Comment by Spacedong** [comment]
this is still happening on the server daily, fix it

**Comment by Pyko1** [comment]
For some reason turret controls dont always have, or they lose the area reference.

(E) (C) (M) control_area = "ÿAI Satellite Antechamber" 
(E) (C) (M) control_area [0x4000047] = /area/turret_protected/ai_upload

**Comment by Spacedong** [comment]
fixd
