### ISSUE TITLE
[FUCK] Ripley drill doesn't stop drilling you when you back away

### ISSUE THREAD

**Issue by blobbernaut** [HippieStationCode/HippieStation13#2037]
Step 1: Ripley clicks you 
Step 2: Run away
Step 3: get hit anyway, instantly crit and unconscious

it doesn't seem to cancel the progress bar if somebody runs away and goes back into range, considering it's a one-shot kill, this is not ok, nor is it intuitive or consistent with the rest of the game

the clamp is plenty robust anyway

**Comment by ArcLumin** [comment]
I can't replicate this. Are you sure they didn't drill the floor?

**Comment by ArcLumin** [comment]
This has been fixed at some point
