### ISSUE TITLE
Wheelchairs

### ISSUE THREAD

**Issue by Pyko1** [HippieStationCode/HippieStation13#2060]
Wheelschairs are moving backwards now.
Also they seem to be slow as fuck.

**Comment by Spacedong** [comment]
I mean they're wheelchairs they're supposed to be slow.

**Comment by Pyko1** [comment]
They used to be faster when they were going to different direction, something broke them.

**Comment by JohnGinnane** [comment]
Fixed in https://github.com/HippieStationCode/HippieStation13/pull/2062
