### ISSUE TITLE
Infinite ID card glitch

### ISSUE THREAD

**Issue by Kierany9** [HippieStationCode/HippieStation13#2070]
So I was a security officer one round and accidentally incinerated myself in a ridiculously hot plasma fire(Went from 100 to crit in 2 seconds). Once I got cloned and all my old gear back, I had an ID in that I could put in and remove from my PDA an infinite number of times, essentially allowing me to duplicate the ID. No idea how it happened.

**Comment by JohnGinnane** [comment]
What state was your body in after you died?

**Comment by JohnGinnane** [comment]
And was the ID in the PDA when you died?

**Comment by Kierany9** [comment]
I was mostly husked but still cloneable, and I don't think the ID was in the PDA.

**Comment by Kokojos** [comment]
I have not been able to reproduce this via killing myself with a open PDA menu and  then cloning myself to be able to pull out the ID.

**Comment by carlarc** [comment]
This happened to me twice, though I don't remember the details.

**Comment by Carbonhell** [comment]
Needs more info, the only known bug that i noticed is that when a backpack burns the contents don't lose mouse opacity thing, but it should not cause this so i'm confus

**Comment by Kokojos** [comment]
Have not been able to reproduce ever since, re-open if issue.
