### ISSUE TITLE
Captain cannot get his laser gun without setting off the alarm

### ISSUE THREAD

**Issue by Sarcalogo** [HippieStationCode/HippieStation13#2081]
Pretty annoying bug... you can't use an ID on it to unlock it or anything like that, you have to break it open.

**Comment by blobbernaut** [comment]
intended imo, the gun is supposed to be a traitor objective / antique anyway, not something you just break out and carry at the start of the round

**Comment by Spacedong** [comment]
intended, its an antique you plebian, its not supposed to be touched by mortal hands

**Comment by Sarcalogo** [comment]
It's a burglar alarm. It's to stop burglars. THe captain aint a burglar. Also isn't there a snippet in the code that says it can be unlocked with an ID? It's non functional but still.

**Comment by Pyko1** [comment]
Would not probably had been placed in a display case, if it was meant to be carried around all day long.

**Comment by Crystalwarrior** [comment]
I say no, honestly it feels like antique laser gun is not even intended to be "used" per se.
Captain put it in 'ere so nobody can touch it, not even himself. :^)

**Comment by McBawbaggings** [comment]
Are you certain this is intended?
https://github.com/HippieStationCode/HippieStation13/blob/ec09b5ccb6aea25ee747f4529044f79e650ce62c/code/game/objects/structures/displaycase.dm#L111
It looks to me as if there is a check for unlocking the thing but I've never seen it work.

**Comment by blobbernaut** [comment]
nO, Sarc, there is a code for unlocking, but only if there is no alarm attached. The captain's display case explicity spawns with the 'alarm' value set to 1, so it cannot be crowbarred open.

**Comment by Sarcalogo** [comment]
It isn't intentional.

https://github.com/tgstation/-tg-station/commit/a668109c3d1f198c1eebb13a143da253cf462768

**Comment by Pyko1** [comment]
That's for constructing new cases, and we have that in our own code as well.

**Comment by Pyko1** [comment]
But ultimately not a bug, feel free to make a PR to try to get this changed tho.
