### ISSUE TITLE
puttiing a dog collar on ian does not show up on his sprite

### ISSUE THREAD

**Issue by Spacedong** [HippieStationCode/HippieStation13#2082]
its also irretrievable after you put it on him

**Comment by Pyko1** [comment]
also cant put the collar on so tight that  it chokes the doge!

**Comment by carlarc** [comment]
super hard to get doggo collars, put some in maint

**Comment by Carbonhell** [comment]
It's more of a shittily implemented feature which pratically does nothing, but i'll consider it as a bug
