### ISSUE TITLE
Borgs can become cultists.

### ISSUE THREAD

**Issue by Spacedong** [HippieStationCode/HippieStation13#2086]
Happened one time to a borg whose dead body was converted to the cult and then revived, making him a cultist. I don't think this is intended.

**Comment by TDcoolguy300** [comment]
Intended, as cyborgs can be any antag should they be one before borging. However to compensate for this AI laws come before objectives.

**Comment by Carbonhell** [comment]
Definitely a bug imo. It can either let the borg just spoil all the cultists' names due to the visible HUD, or cause the borg player to be really confused on what takes preference. Should be patched to only convert carbons and up(i still think xenos should be convertable,so)

**Comment by Spacedong** [comment]
yeah the borg was confused to all fuck and kept ahelping about what he should do

**Comment by carlarc** [comment]
I'd just say to make it give some sort of message that Nar-Sie scrambles your laws or something honestly. After all, borgs still have their brain.

**Comment by TDcoolguy300** [comment]
Then someone has to make a method to de-antag the cyborg while he's in the bloody body then.

**Comment by carlarc** [comment]
Just kill it, like a construct?

**Comment by carlarc** [comment]
OR, make it temporary, like 10-20 minutes. Also make that obvious to the general cult.

**Comment by trifornt-tinfornt** [comment]
Cyborgs should not be able to be converted to the Cult, all it does is lead to some confusing "gameplay laws come before rules" idea and you're not even a real antag until you get subverted or get a Cult law.  If an AI gets converted to cult then he will be counted as dead for the rest of the round, unable to talk or interact with the world but still be able to move his camera around.

This is very obviously a bug.

**Comment by Crystalwarrior** [comment]
This is definitely 100% not intended lol.
It's also a rather easy fix, just check if the culted thing is carbon.
