### ISSUE TITLE
Getting debrained in your old body causes you to ghost permanently

### ISSUE THREAD

**Issue by Sarcalogo** [HippieStationCode/HippieStation13#2140]
Let's say you get killed and then after ghosting, roll a ghost offered role like Abductor. If your old body is found and debrained, you immediately get ghosted and cannot enter your old body again. You are forced to be the brain.

This caused a Syndicate Cyborg to be permanently ghosted and killed.

**Comment by TDcoolguy300** [comment]
Best guess is that when you get a new antag type via being a ghost, your old brain is still associated with you

**Comment by Crystalwarrior** [comment]
First discovered this issue via enabling respawn on test server and gibbing/debraining my old body via plasma fist/ei nath. Definitely something to do with brain creation.

**Comment by JohnGinnane** [comment]
Should we unlink brains from players if the play respawns in any form that also has a brain (e.g. abductor, but not pAI)

**Comment by Crystalwarrior** [comment]
Absolutely, I mean it makes sense. We could even give old brains a message like "This brain looks completely dull and lifeless, it's impossible for it to be used."
