### ISSUE TITLE
Frightbots and Screambots drop nothing on death.

### ISSUE THREAD

**Issue by Spacedong** [HippieStationCode/HippieStation13#2147]
title, it's kinda shitty since every other bot drops something, crystal told me to make this so he doesn't forgit

**Comment by JohnGinnane** [comment]
Should they drop their base components like others? If so should there be a chance for one/two of them to be destroyed?

**Comment by Carbonhell** [comment]
they have a probability to drop,respectively, a robot arm and a radio,but it's a probability, if i remember correctly

**Comment by Crystalwarrior** [comment]
Pretty sure it's the same as how medibot has a probability to drop an arm. Not an issue IMO
