### ISSUE TITLE
Nuke op gun implants not imported yet

### ISSUE THREAD

**Issue by blobbernaut** [HippieStationCode/HippieStation13#2150]
crew should not be able to use nuke op guns without doing the gun firing pin removal first and putting a new one in. Why? Because every single time I am on a nuke op team, this issue means it's more likely for me to win if I murder all of my teammates at the start than allow them to give out free gear to the crew. 

If not for every gun, at the VERY least, this should work for the grenade launchers. 

The procedure to replace the pin doesn't even have to be difficult. It just needs to be limited. If it was literally taking one of the pins from the box in the armory and clicking the gun to let it work, that'd be fine. 

Some people say this would discourage people from going after nuke ops because they won't have any loot. That's entirely not true at all. 1: You can't remove nuke op hardsuits anyway, they're supposed to be unlootable 2: Why do explosive implants even exist then? Your goal for killing a nuke op shouldn't be to get guns, it should be to kill the god damn nuke op so you don't die.

Another idea is to include nodrop implants in the blastco lockers.

**Comment by trifornt-tinfornt** [comment]
Firing Pins are a stupid idea, no the crew shouldn't be restricted from using your guns against you.

**Comment by Crystalwarrior** [comment]
No. Just no. Please forget the existance of firing pins, if the nuke op is literally braindead the crew deserves to get their sweet loot or at least a fraction of it.
If the nukies are a competent team the crew almost stands no chance anyway. We shouldn't balance nuke ops to be "noob-friendly".

**Comment by TDcoolguy300** [comment]
I only kept the stupid gun pin code so we could still maintain the hilarious firepin and the other self-destructing pins.

**Comment by carlarc** [comment]
I'd think that SUPER strong instakill guns should have them. like the AK or a grenade launcher. Not the c20 or c60. Of course that's never gonna happen

**Comment by blobbernaut** [comment]
at least have it on the grenade launcher and the SAW

**Comment by doobiedoo23** [comment]
This isn't an issue. Git is for legitimate bugs, not shit like this

**Comment by TDcoolguy300** [comment]
Non-issue, talk about this shit on the forums
