### ISSUE TITLE
[FUCK][SHIT][JESUS] TELEPORT RUNES CAN BE USED TO GET TO CENTRAL COMMAND Z-LEVEL

### ISSUE THREAD

**Issue by Spacedong** [HippieStationCode/HippieStation13#2157]
place teleport rune on cargo shuttle
send it back
teleport there and get every centcomm weapon and godmin shit 

FUCK

**Comment by Nokington** [comment]
Can't get into the armory on centcom the one door into has a wall under it

**Comment by Spacedong** [comment]
they did though

**Comment by carlarc** [comment]
no problem on this, gib them if they try to go back with gun

if they go in CC and don't do anything that impacts the station WHO GIVES A FUCK

**Comment by Nokington** [comment]
that shouldnt be possible as you cant use anything like handteles on CC. So there is no way they got in the armory

**Comment by Pyko1** [comment]
There should be no way to get in to centcomm besides escape shuttle.

**Comment by Carbonhell** [comment]
Iunno,it sounds like a nice thing, plus the centcom doors are resprited walls so even if they get in there there will be no problem,really

**Comment by banthebantz** [comment]
Pretty nice trick really

**Comment by TDcoolguy300** [comment]
B&'d

**Comment by Memendia** [comment]
Fixed it

**Comment by Spacedong** [comment]
fix this reeeeeeee
