### ISSUE TITLE
laser tag helmets don't cover your hair

### ISSUE THREAD

**Issue by Spacedong** [HippieStationCode/HippieStation13#2167]
should be an easy fix

**Comment by Carbonhell** [comment]
iunno, they're not like sec helmets, i think it's ok for them to show the hair..?

**Comment by Spacedong** [comment]
their sprite implies they cover the hair, also hair literally sticks out on top of them, looks really bad 

they're also pretty much almost the same design as the sec helmets too

**Comment by Pyko1** [comment]
Easy to change, but is this really a bug?

**Comment by TheOneAndOnlyCreeperJoe** [comment]
This has been fixed, close pl0x.
