### ISSUE TITLE
security escape pod is utterly garbage jesus chriist why

### ISSUE THREAD

**Issue by Spacedong** [HippieStationCode/HippieStation13#2183]
https://vgy.me/w6WXVD.png

I feel like this is a pretty big issue. The prisoners are apparently supposed to sit in the front while the officers are supposed to sit in the back??? The officers wouldn't have a view of the prisoners either and the prisoners can just break the window. Not to mention, the pepperspray and flash button is in that section too. The brig section should be in the back while the upper section should be where security sits, with full view of prisoners (maybe a window sort of thing).

**Comment by trifornt-tinfornt** [comment]
Mentioned this a long time ago in a topic of mine. http://hippiestation.com/viewtopic.php?f=19&t=3384
Sec Pod is terribly mapped and needs fixing.
