### ISSUE TITLE
Upgrading the microwaves/gibber no longer increases the amount of food you receive.

### ISSUE THREAD

**Issue by blobbernaut** [HippieStationCode/HippieStation13#2189]
pls fix i want to make the super big bite burgers

**Comment by carlarc** [comment]
Gimme a burg

**Comment by ArcLumin** [comment]
Wasn't this removed from /tg/ code years ago because people were cloning donk pockets and letting them cool, then re microwaving them, then grinding them down for infinite tricord?

**Comment by 2Dollarbill** [comment]
I mean you can technically make infinite Omnizine using botany, while this requires science research and someone actually bothering to upgrade your microwaves. I'm fine with putting it back.

**Comment by Gandalf2k15** [comment]
I'll get putting this back then

**Comment by Spacedong** [comment]
this isn't a bug its from shitty tablecrafting, close this

**Comment by Gandalf2k15** [comment]
Not a bug, bad feature.
