### ISSUE TITLE
chaplain bible can't heal anymore

### ISSUE THREAD

**Issue by blobbernaut** [HippieStationCode/HippieStation13#2192]
i get this "Chaplain Deity refuses to heal this metallic taint!" 100% of the time instead of healing somebody.

**Comment by carlarc** [comment]
SHITTY CARBONHELL CODING

**Comment by Pyko1** [comment]
is this still a thing?

**Comment by Spacedong** [comment]
works, close it

**Comment by Gandalf2k15** [comment]
Fixed, closing
