### ISSUE TITLE
you can't grab a person to do any wrestling moves after you backhand chop them

### ISSUE THREAD

**Issue by Spacedong** [HippieStationCode/HippieStation13#2199]
it basically makes wrestling useless as fuck

**Comment by Crystalwarrior** [comment]
......aaaaaaaaaaaaa?
AAAAAAAAAAAAAAAAAAAA?!!!
FFFFFFFFFFFFFFUCKING HELL!
Alright uh, I'll look into it.
There goes my attempt to make wrestling less useless, fuckin christ.

**Comment by Crystalwarrior** [comment]
https://github.com/HippieStationCode/HippieStation13/pull/2217

**Comment by Pyko1** [comment]
Fixed, I guess
