### ISSUE TITLE
The Control Room in Telecomms can't be accessed by Engineers but they can still access the consoles inside it.

### ISSUE THREAD

**Issue by Spacedong** [HippieStationCode/HippieStation13#2201]
kinda dumb, just set it to telecomms access because whats the point in having a door blocking access to something you actually have access to

**Comment by TDcoolguy300** [comment]
Balancing issue, only the CE has proper access to the door.

**Comment by Spacedong** [comment]
dumb

**Comment by Memendia** [comment]
This is a dumb, Engineers have access but need permission to use it.
_or they can just break the windows down_

**Comment by carlarc** [comment]
LITERALLY UNPLAYABLE

**Comment by blobbernaut** [comment]
Seems like the kind of inept security features NT would have. I say leave it in as a feature.

**Comment by TDcoolguy300** [comment]
Non-issue

**Comment by blobbernaut** [comment]
wait what td where are you going
