### ISSUE TITLE
Missing atmos pipe under the reinforced table leading to the vault

### ISSUE THREAD

**Issue by blobbernaut** [HippieStationCode/HippieStation13#2206]
http://i.imgur.com/7HKhdrX.png

directly under where my drone is standing there is a missing pipe that feeds the captain's office and bridge.

**Comment by Nokington** [comment]
@Pyko1

**Comment by blobbernaut** [comment]
@Spacedong

**Comment by Spacedong** [comment]
i did naht do this i did nawt
