### ISSUE TITLE
Borg RCD can break Rwalls

### ISSUE THREAD

**Issue by blobbernaut** [HippieStationCode/HippieStation13#2211]
no.

enough with engiborgs having literally every conceivable utility tool. If this ability exists, it shouldn't be on the engi borg. They have the tools to break the wall anyway, but they should have to spend the 20 seconds deconstructing it.

**Comment by trifornt-tinfornt** [comment]
Normal RCDs can't even break Rwalls.
That's broken.

**Comment by blobbernaut** [comment]
either both should one neither should, that's the bug

**Comment by Pyko1** [comment]
Intended.

```
/obj/item/weapon/rcd/borg/New()
	..()
	desc = "A device used to rapidly build walls and floors."
	canRturf = 1
```
