### ISSUE TITLE
weird shit going on with skin color caucasian3

### ISSUE THREAD

**Issue by Spacedong** [HippieStationCode/HippieStation13#2248]
before update: 
https://vgy.me/7Ly1E2.png

after update:
https://vgy.me/6odR4N.png

CRYSTAL IS A RACE TRAITOR, RACE WAR NOW

**Comment by Crystalwarrior** [comment]
fucking shithead you realise dismemberment is using grayscaling right
ofcourse they will be minor color differences

**Comment by Spacedong** [comment]
fix it cunt

**Comment by Crystalwarrior** [comment]
Get me a right #hex color that resembles that skin color ON A GRAYSCALE MOB and I'll think about it.

**Comment by Spacedong** [comment]
i dunno what you're talking about, do it yourself

**Comment by Crystalwarrior** [comment]
Fuck off

**Comment by Spacedong** [comment]
open it back cunt
