### ISSUE TITLE
people can apparently walk through mega-hot plasma fires unscathed

### ISSUE THREAD

**Issue by Spacedong** [HippieStationCode/HippieStation13#2250]
crystal stop breaking literally everything

**Comment by TDcoolguy300** [comment]
This literally has nothing to do with crystal

**Comment by TDcoolguy300** [comment]
Also, this is more likely based on how ticks are updated, if you run through the fire fast enough it wont have time to damage you.

**Comment by Crystalwarrior** [comment]
Spacedong I thought I talked to you about coder-blaming.

**Comment by Pyko1** [comment]
could be lag, could be the no damage from being set on fire thing.

**Comment by Sarcalogo** [comment]
It is confirmed. I just lit myself on fire when there was absolutely no lag and took no damage. Did it just now.

**Comment by Sarcalogo** [comment]
L O L

https://u.pomf.is/pyvujz.webm

**Comment by TDcoolguy300** [comment]
Refer to Sarcalogo's issue

**Comment by TDcoolguy300** [comment]
#2253
