### ISSUE TITLE
Bent pipes turn into straight pipes when picked up. 

### ISSUE THREAD

**Issue by Spacedong** [HippieStationCode/HippieStation13#2251]
gas pipes that is

**Comment by Pyko1** [comment]
something must have broken how the dir is handled on these, as they are actually same as straight pipes, and the bending is handled by dir.

**Comment by Virtual-Balboa** [comment]
Hi Baby I wanna fix this for you

**Comment by Spacedong** [comment]
this happens to pumps and regular pipes that are horizontal too, they keep pointing straight up when you pick them up

**Comment by JohnGinnane** [comment]
Gonna look at this now, however as a work around you can drag the bent pipes and alt click them into place.

**Comment by JohnGinnane** [comment]
I believe the cause is: https://github.com/HippieStationCode/HippieStation13/commit/569438d98fe30e90711c1f4e0ad356dd784fc5d4#diff-ac3b89e91ad083b3cb3fdb669006158c
