### ISSUE TITLE
You no longer take damage from being on fire

### ISSUE THREAD

**Issue by Sarcalogo** [HippieStationCode/HippieStation13#2253]
Seems like a Critical bug for me. Try it out yourself. Compile your own server and light yourself on fire. No damage at all.

**Comment by Sarcalogo** [comment]
https://u.pomf.is/pyvujz.webm

**Comment by TDcoolguy300** [comment]
Your issue is far more descriptive than Spacedongs, as he effectively only started with "FUCK CRYSTAL"

**Comment by Crystalwarrior** [comment]
Thank you, I'll look into it now.

**Comment by JohnGinnane** [comment]
Damn, this means I can no longer roleplay as the human torch

**Comment by TDcoolguy300** [comment]
Fixed in #2254
