### ISSUE TITLE
Deepfried limbs are invisible

### ISSUE THREAD

**Issue by Pyko1** [HippieStationCode/HippieStation13#2257]
see the title.

**Comment by Pyko1** [comment]
also no flavour text on at least eating deepfried heads.

**Comment by Crystalwarrior** [comment]
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA FUCK
i'll fix it maybe.

**Comment by trifornt-tinfornt** [comment]
skeleton limbs are invisible too..

**Comment by Spacedong** [comment]
pretty sure this was fixareedoo'd

**Comment by Spacedong** [comment]
fixed
