### ISSUE TITLE
dismemberment

### ISSUE THREAD

**Issue by Pyko1** [HippieStationCode/HippieStation13#2266]
has stabbed Unknown in the 0 with the butcher's cleaver!
![capture](https://cloud.githubusercontent.com/assets/12048747/14998073/aef697c6-118a-11e6-8d02-6a5fdc290149.PNG)
I think he was missing a head to begin with.

**Comment by Crystalwarrior** [comment]
What limbs was he missing exactly?

**Comment by JohnGinnane** [comment]
@Crystalwarrior I think someone was missing all of his limbs and this was happening. I suspect that if you target someone's left arm and they're missing that limb, you get this message. Perhaps if the limb is missing direct the attack zone to the chest? Or perhaps a miss chance?

**Comment by Crystalwarrior** [comment]
It actually DOES have a miss chance, something went extremely odd. Did they get their chest dismembered by any chance?

**Comment by JohnGinnane** [comment]
In a slightly unrelated note:
![image](https://cloud.githubusercontent.com/assets/3355198/15022066/ce903f28-1221-11e6-9e3b-2cd822892d23.png)

**Comment by JohnGinnane** [comment]
I couldn't tell you, I think he may have been beheaded!

**Comment by JohnGinnane** [comment]
Just saw another example: Suspect was targeting eyes, victim was beheaded and the text "...in the 0 with the..." was appearing after victim was beheaded

**Comment by JohnGinnane** [comment]
Here you go 
![image](https://cloud.githubusercontent.com/assets/3355198/15024067/28bae756-122b-11e6-8a09-2decd0e6f80a.png)

**Comment by Crystalwarrior** [comment]
Seems like there's a missing check_zone :v
