### ISSUE TITLE
Shadowlings can use Glare, Veil, etc while in Jaunt.

### ISSUE THREAD

**Issue by Sarcalogo** [HippieStationCode/HippieStation13#2269]
1. Use shadow walk
2. Jaunt over to a guy who is alone
3. While still in jaunt, glare, then veil.
4. Watch as he sits defenseless unable to stop you.
5. Cuff enthrall
6. ????
7. Ascend!

Not sure if intentional or not, but needs to be changed. Hackole abused this to kill 30 something people as a shadowling with a fire axe.

**Comment by JohnGinnane** [comment]
Can wizard use similar abilities while he/she is jaunting? And should they be allowed?

**Comment by Sarcalogo** [comment]
It's weird, wizard can use some spells while in jaunt, the robeless ones, but not all of them. Ascended shadowlings can't use any spells while in jaunt.

**Comment by JohnGinnane** [comment]
Should anybody be able to use any items/abilities while in jaunt form?
