### ISSUE TITLE
You cannot ghost as an MMI if you were a cyborg that detonated

### ISSUE THREAD

**Issue by Sarcalogo** [HippieStationCode/HippieStation13#2273]
If you're in an MMI, you can no longer ghost. This leads to scenarios where you are blown up in space, unable to be found, and will have to stay there the whole round. Obviously not intended and worked prior to dismemberment.

Works if you got MMI'd but never borged tho.

**Comment by Crystalwarrior** [comment]
Are you sure about this? Because when people screamed "YOU CAN'T GHOST WHEN DECAPITATED" you could actually ghost but it would remove you from the round.

Also, being able to ghost as an MMI without any reprecussions is a terrible idea because then you could abuse MMI's for intel.

**Comment by Sarcalogo** [comment]
I am 100 percent sure.

>Also, being able to ghost as an MMI without any reprecussions is a terrible idea because then you could abuse MMI's for intel.

What the fuck are you even talking about? If you ghost you can't go back into your brain, and even if you could that's blatant metagaming and against the rules. If you cannot ghost as an MMI you are literally STUCK in the round. If you are blown up in a shitty area, say, an empty Space Z level. You are FUCKED and forced to either close the game or stay there. Why not play as a borg once in a while... It's a bug. 100 sure.

**Comment by Crystalwarrior** [comment]
So you can't ghost period. That's pretty odd.

**Comment by Sarcalogo** [comment]
Yes it's odd. It's also a pretty bad bug!

**Comment by Crystalwarrior** [comment]
Okay I tested it live on server and you absolutely CAN ghost as an MMI, albeit you'll be removed from the round if you do.

This is a non-issue and is intended.

**Comment by Sarcalogo** [comment]
Try again. Log in with two accounts. Set one on Cyborg to High, the other on RD to High. 
Blow yourself up with the RD console. 
Try to ghost as the cyborg brain.
You cannot.
