### ISSUE TITLE
beheaded kamikaze are horrid

### ISSUE THREAD

**Issue by Spacedong** [HippieStationCode/HippieStation13#2288]
they explode before they even get close to you and the explosion barely does damage

everytime they move they go AAAAAAAAA and it cuts off so if you have a group of them its so choppy and horrible, they should only yell AAAAAAAA when theres a target in sight.

**Comment by Zadeon** [comment]
Do you WANT me to buff these guys? I can try working on fixing the explosion range but I think they can delimb people. 

I'll also look into fixing up the sound as well.

**Comment by Crystalwarrior** [comment]
Make the "idle" AAAAAA low-pitched like in the games
Also, make them explode only on contact, not on range.

**Comment by Spacedong** [comment]
this isnt fucking balancing its legitimately a bug holy fuck stop

**Comment by Gandalf2k15** [comment]
This does not really seem like an issue.

**Comment by Gandalf2k15** [comment]
Remove this.
