### ISSUE TITLE
Headslug is OP

### ISSUE THREAD

**Issue by Sarcalogo** [HippieStationCode/HippieStation13#2305]
So we get a ling downed on a 3 v 1 fight. It headslugs, whatever, fine. So when it bursts, it instantly stuns and explodes anyone nearby. Either stunning them or knocking them unconscious, and knocking a limb off. Most likely putting the person in crit. So all the headslug has to do at this point is drag the person knocked into crit by the explosion, and spam click on them until they are dead. Then they implant their egg into the person, and instantly get all of their genomes back + 1. Very easily abused. We killed this guy 3 separate times but he still kept coming back from this.

You should probably remove the ability to Headslug whenever you want as a ROUND START POWER. Last resort was a tier 3 power for a reason. You can keep the ability to headslug when you are decapitated at any time, just not at any time period.

**Comment by Hackole** [comment]
But hold on here sarca, I thought the trick to beating instantkill melee range changeling powers was to GET GOOD ?

**Comment by Sarcalogo** [comment]
It's AOE though, not melee.

**Comment by Crystalwarrior** [comment]
Hold the fuck on, what? Knocking ANY limbs off is a very unintended effect. I'll have to look into it.

**Comment by calibraptor** [comment]
HAHAHA yeah nerf it. Maybe only stun people.

**Comment by Crystalwarrior** [comment]
it's SUPPOSEd to only stun people AAAAAAAAAAAAAAA
Worst case scenario, it's probably the MMI explosion that causes dismemberment.

**Comment by Sarcalogo** [comment]
Any time you are caught in an explosion, you lose a limb.

**Comment by JohnGinnane** [comment]
Will be fixed by https://github.com/HippieStationCode/HippieStation13/pull/2441 if merged

**Comment by blobbernaut** [comment]
Would also be fixed by the armor rework pr too as i nerf explosions chance to dismember but that pr doesn't look like itll get merged very soon
