### ISSUE TITLE
There are floor tiles and lattices underneath the sand on the outpost.

### ISSUE THREAD

**Issue by Spacedong** [HippieStationCode/HippieStation13#2309]
https://vgy.me/eEExIV.png
GOVERNMENT CONSPIRACY!?

**Comment by JohnGinnane** [comment]
Not gonna lie, that is actually kinda cool, even if unintentional

**Comment by Spacedong** [comment]
controversy erupts as nanotrasen-brand asteroids are found to be built out of synthetic rocks, more information tonight at 9

**Comment by Gandalf2k15** [comment]
This is dead too

**Comment by Kokojos** [comment]
Outpost is dead
