### ISSUE TITLE
Regenerative Stasis broken?

### ISSUE THREAD

**Issue by yobob591** [HippieStationCode/HippieStation13#2328]
Basically I was a ling, I went to the gateway, I was crit by a syndicate operative, and while i was crit i hit regenerative stasis. Nothing. I just died normally and never came back. I had full chems at the time

**Comment by blobbernaut** [comment]
I actually think lings shouldn't be able to regenerate on away missions. This could be a good balance decision but we'd need to make sure we understand why it happens too.

**Comment by yobob591** [comment]
I dont think it really makes sense for them to not regen on away missions, but i dont think me being in the away mission is what caused it

**Comment by blobbernaut** [comment]
of course it does otherwise they'd be able to just come back with a ton of guns while having absolutely no danger of being there

**Comment by yobob591** [comment]
yeah but think of how this could be gamed

ling round = camping inside gateway for immunity

**Comment by Pyko1** [comment]
there was a revert, not an issue
