### ISSUE TITLE
you butt flies off into the galaxy broken

### ISSUE THREAD

**Issue by blobbernaut** [HippieStationCode/HippieStation13#2367]
it's supposed to make an immoveable butt rod that cuts through the station in a random direction from you but it doesn't actually do this it just gibs you

**Comment by McHatters** [comment]
Was this ever a thing?

**Comment by McBawbaggings** [comment]
Yes it's a 0.4% chance to fire IIRC.

**Comment by Kierany9** [comment]
IIRC there's a chance to gib and there's also a chance to spawn a rod.

**Comment by blobbernaut** [comment]
yeah but the rod bit doesn't work actually

**Comment by PKPenguin321** [comment]
going off of just the title of this issue here:
what the fuck?

**Comment by Carbonhell** [comment]
oh come on,haven't you ever seen a butt flying off into the galaxy and returning to smash everything down due to you superfarting
where do you live,even

**Comment by blobbernaut** [comment]
Still broke

**Comment by JohnGinnane** [comment]
Might look at fixing in rebase
