### ISSUE TITLE
Stunprod charge bug

### ISSUE THREAD

**Issue by Kierany9** [HippieStationCode/HippieStation13#2371]
Stunprods made with normal powercells show up with 100% charge when inspected but say that the cell is empty when turned on. IIRC stunprods are only supposed to be useable with higher quality powercells.

**Comment by McBawbaggings** [comment]
Stunprods should only be high capacity+.

**Comment by Kierany9** [comment]
Yes but you can craft one with a normal cell(which is the problem) and upon inspection it will say it's fully charged but when turning it on it says it's empty. You can't put the cell back in if you take it out.

**Comment by McBawbaggings** [comment]
Did you table craft it?

**Comment by Kierany9** [comment]
Yes, IIRC.

**Comment by Gandalf2k15** [comment]
Unable to recreate.
http://i.imgur.com/bekc6ZO.png

**Comment by Kierany9** [comment]
Replicated here, am currently fixing

https://www.dropbox.com/s/o9h0bxs97vbx8tq/Desktop%2006.18.2016%20-%2013.11.17.02.mp4

**Comment by TDcoolguy300** [comment]
Whoops
