### ISSUE TITLE
Throwing animation for eguns and tasers is broken

### ISSUE THREAD

**Issue by Kierany9** [HippieStationCode/HippieStation13#2381]
The main sprite spins but none of the charge overlay sprites do. I suspect the same thing happens with ion rifles, stun batons and any other object with multiple sprites.

**Comment by carlarc** [comment]
Also clipping a knife or seclite to them, uhh, makes them weird when thrown?

**Comment by Gandalf2k15** [comment]
This only happens to tasers/eguns/old tasers. This is caused due to the fact they have overlaying sprites. This should really be changed. The sprites should be solid. I'll see about fixing this.
