### ISSUE TITLE
Armless people's sleeves magically float in the air.

### ISSUE THREAD

**Issue by Sarcalogo** [HippieStationCode/HippieStation13#2421]
As if there is still a shoulder or forearm, when in reality there is nothing to hold the sleeves up.

**Comment by Kokojos** [comment]
That's more of a sprite issue, not sure we can ever fix this. Magical spaceman fabric?

**Comment by Sarcalogo** [comment]
I don't know maybe somehow make part of the sprite invisible? No idea how to do that.

**Comment by Spacedong** [comment]
this is the same thing like goon's and bay's, it will never be fixed and is pretty low on the priority list, close this, stop being so nitpicky, jesus

**Comment by doobiedoo23** [comment]
Spacedong you can't say shit about being 'nitpicky' lmao

**Comment by Kokojos** [comment]
Thou it is true, we'll never fix this unless we change everything or have instant pixel manipulation on our caracthers, and shit no one will.
