### ISSUE TITLE
Headslug egg bug

### ISSUE THREAD

**Issue by Sarcalogo** [HippieStationCode/HippieStation13#2425]
If two headslugs egg the same corpse, the headslug that eggs the corpse after the first person does gets the body. This caused me to be gibbed, even though I did all the hard work finding and killing a person to egg.

**Comment by calibraptor** [comment]
I kinda like the idea of a ling poaching another ling's hard earned corpse tbh.

It's a feature, not a bug. :^)

**Comment by Mithrandalf** [comment]
Okay but what happens if the first ling uses last resort as soon as he bursts from the body?

**Comment by LuisReyesX** [comment]
the other ling gets dunked on

**Comment by Kokojos** [comment]
headslugs are so bugged right now that even this bug dosen't work anymore.
