### ISSUE TITLE
HONK mech starts with an access restriction

### ISSUE THREAD

**Issue by blobbernaut** [HippieStationCode/HippieStation13#2434]
why?

if you build it you should get it

**Comment by carlarc** [comment]
odysseus too

**Comment by carlarc** [comment]
fun fact: mime can get in honkmech too since he has theatre access

**Comment by Carbonhell** [comment]
only clowns should drive honk mechs tbh,and it's not a bug but a feature so it shouldn't even be here but rather on the forum,closing
