### ISSUE TITLE
Monkeys scream like a human

### ISSUE THREAD

**Issue by Sarcalogo** [HippieStationCode/HippieStation13#2449]
It seems pretty silly to me. Maybe replace with an ook ook ahh ahh sort of thing?

**Comment by TDcoolguy300** [comment]
Find the sounds for it

**Comment by Sarcalogo** [comment]
How about the first one here?

http://www.soundboard.com/sb/Monkey_Sounds_audio

**Comment by Spacedong** [comment]
is this even being worked on?

**Comment by GeneralGoose** [comment]
we can use those meme sounds of chimps 
https://www.youtube.com/watch?v=jG83e101QbI
