### ISSUE TITLE
You can hang headless corpses

### ISSUE THREAD

**Issue by Sarcalogo** [HippieStationCode/HippieStation13#2453]
You can also hang a corpse, cut off its head, and it's still hanging.

**Comment by TheOneAndOnlyCreeperJoe** [comment]
Muh immersion.

**Comment by Sarcalogo** [comment]
Yeah dismemberment is buggy. This should be standard stuff.

**Comment by Mithrandalf** [comment]
Not really worth its own issue, but headless corpses keep their masks on too.

Dismemberment is buggy.

**Comment by Gandalf2k15** [comment]
Fixed

**Comment by Gandalf2k15** [comment]
https://github.com/HippieStationCode/HippieStation13/pull/2491
