### ISSUE TITLE
Nuke ops ship isn't entirely indestructable

### ISSUE THREAD

**Issue by Sarcalogo** [HippieStationCode/HippieStation13#2454]
The engine parts of the ship can still be blown open with c4 or any kind of bomb meaning the nuke can be stolen.

**Comment by TheOneAndOnlyCreeperJoe** [comment]
It was never meant to be entirely indestructible, you could just blow up the front anyway and that was intentionally left in.

**Comment by blobbernaut** [comment]
the big issue was that the walls were deconstructable with normal fucking tools. Not sure if this is bug or feature because of that.

**Comment by Kokojos** [comment]
Yeah, Im fairly sure this is not an Issue, it CAN be stolen, but it requires more effort.
