### ISSUE TITLE
the time period for renaming a holoparasite is insanely short

### ISSUE THREAD

**Issue by Spacedong** [HippieStationCode/HippieStation13#2459]
I typed out a name in like 2 seconds and it already said I was stuck with my holoparasite default name, it goes so fast what the fuck

**Comment by Sarcalogo** [comment]
I fixed this in https://github.com/HippieStationCode/HippieStation13/pull/2270

**Comment by JohnGinnane** [comment]
Fixed in https://github.com/HippieStationCode/HippieStation13/pull/2544
