### ISSUE TITLE
Stamina Icons don't represent stamina

### ISSUE THREAD

**Issue by Sarcalogo** [HippieStationCode/HippieStation13#2478]
It shows Stamina + Health, which is exactly what the squiggly line icon already does. There is no way to determine just how much stamina you have.

**Comment by Gandalf2k15** [comment]
ewww

**Comment by Kierany9** [comment]
The squiggly line icon was changed to just show health.

**Comment by Sarcalogo** [comment]
Why does the stamina icon take into account health though? Wouldn't it be better if it just took into account stamina and not health?

**Comment by Kierany9** [comment]
Because stamina on its own doesn't really determine anything, whereas stamina+health not only determines your movement speed, it also tells you how close you are to being knocked down.

**Comment by Sarcalogo** [comment]
Eh alright, I guess that makes sense. A bit of a misnomer to call it a stamina icon then.
