### ISSUE TITLE
Some viruses can't be cured even if you take the right cure

### ISSUE THREAD

**Issue by Sarcalogo** [HippieStationCode/HippieStation13#2479]
Magnitis and the bee virus are one of them. Take the cure listed on health scanner, wait, nothing happens. Other viruses are cured like brainrot. Occurred over multiple rounds.

**Comment by Sarcalogo** [comment]
This may also be an issue with the virus code in general, maybe it's not a particular virus that can't be cured but an error in the actual curing that targets random viruses or something? I don't know.

**Comment by Gandalf2k15** [comment]
Can't recreate. I don't see how this could fuck up but I'll look through the code to see if anything is odd.

**Comment by Sarcalogo** [comment]
Try using a cargo crate.

**Comment by danhibiki** [comment]
Likely wasn't enough to regress the disease beyond 1.

**Comment by Sarcalogo** [comment]
Well for what its worth, it doesn't get cured if you have a custom virus with the symptom that cures other viruses too.

**Comment by danhibiki** [comment]
Did you adminbus the disease in, or create it in game? that would also be an issue with the symptom that we should look into specifically. Any other information you can give us?

**Comment by Sarcalogo** [comment]
I can't give you much more information no. Most of the time when we noticed it occurs, it's in a round where someone spreads a virus through a cargo crate. When me and a few others attempt to cure it, we are sucessful at curing most of them, but even if we take the appropriate cure for one of them (usually magnitis) it doesn't get cured. So I guess something you should consider is that USUALLY it is present with one or two other viruses. Try loading yourself up with 3 cargo viruses and try to cure it after that.

The only thing I can say that may not be clear is that I'm not talking about advanced custom viruses, but viruses from virus crates, and random events.
