### ISSUE TITLE
Emagged borg's laser gun's sprite looks empty but can fire.

### ISSUE THREAD

**Issue by Spacedong** [HippieStationCode/HippieStation13#2481]
You can fire it until blinking red and it still fires unlimited shots. This is because it draws on the cyborg's power cell. However, the sprite never displays infinite ammunition. It goes to blinking red permanently after you fire the default amount of laser shots.

**Comment by JohnGinnane** [comment]
Can you list steps to reproduce?

**Comment by Spacedong** [comment]
>be emagged borg
>fire your laser 
>see blinking red but still be able to fire

just make the sprite be permanently green

**Comment by Gandalf2k15** [comment]
Fixed.
