### ISSUE TITLE
There is no bucket in the off-station permabrig to do botany with.

### ISSUE THREAD

**Issue by Spacedong** [HippieStationCode/HippieStation13#2487]
title

EDIT: also no plant analyzer or plant bags to pick up anything #
EDIT: THERE'S ALSO NO WATER OR SINK, HOW DO YOU DO ANYTHING

**Comment by calibraptor** [comment]
Fixing this. Also there are sinks in the restroom.

**Comment by Gandalf2k15** [comment]
This was fixed
