### ISSUE TITLE
the recent is_type_in_list update broke grinders apparently

### ISSUE THREAD

**Issue by blobbernaut** [HippieStationCode/HippieStation13#2501]
Unconfirmed, haven't experienced this myself this is only based off of what somebody in OOC said and they don't have a github account.

**Comment by GeneralGoose** [comment]
it IS confirmed. 
https://github.com/HippieStationCode/HippieStation13/issues/2535
tested it, none of the items in FOOD/snacks can be put in the grinder.

**Comment by LogJammer** [comment]
Will confirm. Especially onerous given the ill-advised ghettochem nerf. Please fix.

**Comment by Spacedong** [comment]
this works now, close it
