### ISSUE TITLE
player-controlled slimes

### ISSUE THREAD

**Issue by Spacedong** [HippieStationCode/HippieStation13#2510]
they're a complete grey area and nobody knows how to handle them

they move 2x faster than humans, impossible to kill, can travel through vents, and are a general overall nuisance

they either need to be nerfed, removed, or made only available through staff of change during wiz rounds

**Comment by calibraptor** [comment]
>Nerfed
Doable
>Impossible to kill
Use a fire extinguisher
>Removed
Not gonna happen.

**Comment by McHatters** [comment]
we gotta add an 'enter objective' box like Meeseeks. They should be held to the laws that are set by their makers, but without anything as concrete as this all we got to go for is the say logs of the xenobiologists.

**Comment by Kokojos** [comment]
That's a solid idea Mchatters

**Comment by Spacedong** [comment]
you literally cannot use a fire extinguisher, you need like 3 fucking fire extinguishers to take down ONE, then he splits and runs away at sonic speed

**Comment by danhibiki** [comment]
YOu would imagine after around a year of doing issue tickets you'd learn what is and is not a ticket. This is not a valid issue ticket.

**Comment by Nebyab** [comment]
Hey fuckwads. This is for issue reports. "I dislike how things are balanced" is not an issue which falls under the purview of this part of git.

**Comment by McHatters** [comment]
On a sidenote, we should probably add the objective box for any player-summoned mobs. Makes dealing with these issues a lot easier because people will be more inclined to follow a big red message stating their laws rather than the same laws being said by a player.
