### ISSUE TITLE
SILICON BANS ARE BROKEN

### ISSUE THREAD

**Issue by Spacedong** [HippieStationCode/HippieStation13#2531]
FUCK FUCK FUCK SHIT MONG ASS FUCKING FIX IT CHRIST IM GONNA TEAR MY HAIR OUT FUCKING

**Comment by Gandalf2k15** [comment]
shhhh

**Comment by Spacedong** [comment]
they don't leave notes on the person's note list and they have to be given individually through manual banning panel, holy christ

**Comment by Kokojos** [comment]
Unable to reproduce.
