### ISSUE TITLE
Officer beepsky can cuff while both mobs are moving

### ISSUE THREAD

**Issue by blobbernaut** [HippieStationCode/HippieStation13#260]
As a changeling, beepsky was after me, stunned and started his cuff. I adrenaline surge'd up, but it followed me. I had on the CE's advanced magboots and hardsuit and was slightly injured, but this was in 0 gravity. I wasn't cuffed while I got up to run, but it was able to keep up with me and had cuffed me after I moved around 5 tiles away. 

This is a consistency issue. Beepsky can cuff while both it and the mob are moving, which is unlike any other cuffing mechanic.

**Comment by JustinBNewton** [comment]
Confirmed
