### ISSUE TITLE
the horrible delay on manifesting for a parasite means they cannot manifest if the user is moving

### ISSUE THREAD

**Issue by blobbernaut** [HippieStationCode/HippieStation13#2609]
Who added this delay and why? Holoparasites are weak as hell without being forced to wait 8 hours to manifest after they're sent back to the body. If the user is being pulled, the holoparasite literally cannot manifest because they will be pulled out of range before the fake, pointless cast time is finished. 

The cast time should either be removed, or, it should be fixed so that the holoparasite's spawn location isn't fixed, but instead follows the host. That way they can still manifest.

**Comment by Spacedong** [comment]
yeah its so slow for some reason, I can't tell if its intended or bugged, maybe the giant /tg/ fix PR will amend this?

**Comment by Spacedong** [comment]
nvm im stupid what the fuck why does this exist

**Comment by Mithrandalf** [comment]
I've heard this is intentional. Means you can drag the host to hardcounter the holopara.

Even if you removed the manifest animation, you'd still be stuck with your camera locked on the host for like 3 seconds so it wouldn't be MUCH use.

**Comment by blobbernaut** [comment]
That's a horrible mechanic. They're 20tc there should be no intentional
hard counter.

**Comment by Mithrandalf** [comment]
Inclined to agree. However, even removing the manifest animation means your camera is still locked, making it pmuch impossible to fight.

Holoparas suck right now.

**Comment by Spacedong** [comment]
they always sucked

**Comment by GeneralGoose** [comment]
> still not removed

**Comment by Spacedong** [comment]
@generalgoose the PR is up you drongo

**Comment by Spacedong** [comment]
@tdcoolguy300 fixed, close it
