### ISSUE TITLE
Sing beacon doesn't work at all

### ISSUE THREAD

**Issue by blobbernaut** [HippieStationCode/HippieStation13#261]
I created 10 SMES's with upgraded capacitors to power a sing beacon after the engine was destroyed, just to ensure it wouldn't turn off due to lack of power. (Output was 3 million watts)

Sing beacon stayed on, it did not affect the singularity at all. Admins even spawned another to test it again to confirm.

**Comment by blobbernaut** [comment]
This should probably be marked as closed or fixed

**Comment by nalarmg** [comment]
Can someone confirmed it's fixed?
