### ISSUE TITLE
clown hardsuit sprite gives nightmares

### ISSUE THREAD

**Issue by Spacedong** [HippieStationCode/HippieStation13#2642]
looks like something out of a fucking horror movie and I know this wasn't fuckin intentional 

https://vgy.me/wfe5T7.png

**Comment by trifornt-tinfornt** [comment]
Yeah, the sprite is fucking horrible, and horrifying.

**Comment by Mithrandalf** [comment]
So is this literally just that you don't like the sprite?

**Comment by Kokojos** [comment]
Not really an issue, propose a PR if you wish to change it.
