### ISSUE TITLE
[PRIORITY][FUCK][SHIT][TITS][ASS][COCK] BLUESPACE SHELTERS CAN BE USED TO GET TO CENTRAL COMMAND Z-LEVEL

### ISSUE THREAD

**Issue by Spacedong** [HippieStationCode/HippieStation13#2649]
https://vgy.me/2dfQMP.png

>go in a pod > use all your capsules to get there

JUST REMOVE THEM FROM THE GAME HOLY FUCK

**Comment by blobbernaut** [comment]
Not the only way to get there tho

**Comment by ArcLumin** [comment]
Yeah, there's a few, including crystals

And this method requires 5 BS capsules which requires a trip to the gamma derelict, and, when it's fixed, red alert on the station for the 4 other bs capsules

**Comment by GeneralGoose** [comment]
funny meme

**Comment by blobbernaut** [comment]
Honestly if you can get all 5 bluespace capsules I view it like collecting all the dragon balls, you deserve to be able to go to the centcomm level

**Comment by calibraptor** [comment]
Just remove the bluespace capsules, they're gimmicky anyways

**Comment by blobbernaut** [comment]
No I like them and they're useful.

**Comment by ArcLumin** [comment]
I like em too. Plus, once the safe fix is implemented, they'll become far more rare, as red alerts themselves are uncommon

**Comment by McBawbaggings** [comment]
I don't think they're fit for purpose.
The whole point of the escape pods being used for emergency escape during red delta is for people who want to run away during malf/nukies/gangs etc.
You get mining gear and spacesuits to escape the asteroid, you don't need a little autism fort on top.

**Comment by Spacedong** [comment]
even if we remove the secure pod safe bug, its still keeping fuckers from getting a free space suit without going to EVA, I'm all for removing these bastards anyway, nobody uses them except to fuck shit up

**Comment by GeneralGoose** [comment]
i agree with raptor, already said they should be removed until someone makes it so they dont break everything

**Comment by Kokojos** [comment]
removed
