### ISSUE TITLE
random crashes

### ISSUE THREAD

**Issue by TrickyDickRichard** [HippieStationCode/HippieStation13#2681]
randomly i crash. it's usually when i follow someone but it happens for apparently no reason sometimes. this might by a clientside issue but has anyone else been getting them?

**Comment by ArcLumin** [comment]
No issues here. I haven't heard anyone else having such issues either. I'm thinking it's a client side issue.

**Comment by Carbonhell** [comment]
Update your Internet Explorer. It's most likely an issue with a hrefs, a clientside issue.
