### ISSUE TITLE
inflatable shit can be stacked on a tile

### ISSUE THREAD

**Issue by Spacedong** [HippieStationCode/HippieStation13#2700]
https://vgy.me/EBDsk3.png

bad

**Comment by McBawbaggings** [comment]
Dobson outdoes himself once more.

**Comment by GeneralGoose** [comment]
frik

**Comment by banthebantz** [comment]
I did this and was proud. I stacked like two whole boxes worth of inflatable shit on a tile, then stacked a reinforced wall, then a window, then an AI core and finally a bunch of racks and I just sat there like a newly birthed god.

**Comment by Spacedong** [comment]
then you crashed the server :^)

**Comment by McBawbaggings** [comment]
https://github.com/HippieStationCode/HippieStation13/pull/2701 should hopefully fix this/
