### ISSUE TITLE
the new crew monitor is fucking terrible (here's why)

### ISSUE THREAD

**Issue by Spacedong** [HippieStationCode/HippieStation13#2721]
1. Takes so fucking long to update positions and locations. Christ, I was looking for this guy in a location when I realized that the crew monitor didn't refresh so I needed to open it back up again and he was like completely across the map.
   1. No refresh button even if it does glitch out and fail to update. 
   2. The map interface is a laggy piece of shit and I'd like it if we just went back to the old list version instead, or atleast have different modes and z-levels on it like on /vg/.

**Comment by Kierany9** [comment]
not an issue

**Comment by Spacedong** [comment]
its a pretty bad issue

**Comment by ArcLumin** [comment]
You can have a handheld crew monitor open and just keep it on you and it constantly refreshes.

It also gives a map of whatever Z level you're on currently, which you can use in space to find what Z level you're on easily, and where you're at in the Z level

I mean you can do the same with the GPS but hey

**Comment by Pyko1** [comment]
Not sure if the freeze issue was ever fixed with the monitor that made it stop refreshing at all.

**Comment by Spacedong** [comment]
yeah im talking about the handheld, sometimes it refreshes, sometimes you need to close it out and close it back on, I'm talking about how on /vg/ you can manually switch z-level number and view the mining z-level to search for any dead miners as well. Maybe Pyko is right.

**Comment by ArcLumin** [comment]
I haven't noticed any freeze issues, but hey. I agree, a z-level switching would be nice

**Comment by Pyko1** [comment]
seems that the specific issue i was talking was fixed tho.
https://github.com/HippieStationCode/HippieStation13/issues/1721

**Comment by Spacedong** [comment]
i just feel like the update time is random I keep having to re-open the window for it to refresh.

**Comment by JohnGinnane** [comment]
@Spacedong can you see how long it takes to update? Average refresh time? I believe it should be once every 5 seconds, but it could be much slower

**Comment by trifornt-tinfornt** [comment]
Revert the handheld crew monitor. Everything Spacedong says is true, and it's really poorly made.
