### ISSUE TITLE
you need to take off people's masks to expose their heads for surgery

### ISSUE THREAD

**Issue by Spacedong** [HippieStationCode/HippieStation13#2723]
even if their sprite/item only covers the bottom portion of their head or face, it makes no sense

**Comment by ArcLumin** [comment]
Same reason that wearing a normal ass internals mask, even if it's around your fuckin neck, it counts as enough face hiding for shadowling thralls; it won't give the message, and the sprite's subtle when it's around your neck. Also enough that you can't do CPR
