### ISSUE TITLE
nuke-op hardsuits are not burn-resistant

### ISSUE THREAD

**Issue by Spacedong** [HippieStationCode/HippieStation13#2725]
I burned to death from my own flame-rounds using a bulldog shotgun. Why does this exist

**Comment by Hackole** [comment]
Intentional. The advanced syndi hardsuits ARE fireproof, and they cost extra.

**Comment by ArcLumin** [comment]
Don't walk directly into dragonsbreath rounds lad

**Comment by Carbonhell** [comment]
Not an issue.
