### ISSUE TITLE
using welder on kudzu burns your eyes

### ISSUE THREAD

**Issue by Spacedong** [HippieStationCode/HippieStation13#2729]
why

**Comment by JohnGinnane** [comment]
You know welders are very bright?

**Comment by TDcoolguy300** [comment]
Non-issue. Anytime you use a welder for ANYTHING, it will call the proc to check your eyes.

**Comment by GeneralGoose** [comment]
@TDcoolguy300 does it burn your eyes when you attack people? pretty sure it didn't

**Comment by TDcoolguy300** [comment]
Rather, it's a specific proc it calls for welding actions, when you attack people with it, it calls a completely different set of procs.
