### ISSUE TITLE
nanomeds still have morphine instead of sleep toxin

### ISSUE THREAD

**Issue by Spacedong** [HippieStationCode/HippieStation13#2739]
was this missed in the chemistry update or was this intentional? because oldchem always had sleep toxin, then when morphine became the new sleep toxin, it was switched

**Comment by Spacedong** [comment]
EDIT: sleeptoxin AND morphine bottles are available via nanomed, was this inteional or not because if it was ill close this

**Comment by Kierany9** [comment]
Intentional
