### ISSUE TITLE
Post all King of the Disk Issues here

### ISSUE THREAD

**Issue by Kierany9** [HippieStationCode/HippieStation13#2740]
I'll fix any major ones whenever I can.

### Known issues:
None at the moment

### Fixed issues:
- [x] If your uplink menu is open when you get extra TC from hodling the disk, you have to close and reopen it to update the TC amount.
- [x] **Major:** TC generation is broken when the disk is in a backpack.

**Comment by Pyko1** [comment]
On an unreleated note, I can click the [x] to change the state of it!
- [x]
- [x]
- [x]
- [x]
- [x]
- [x]
- [x]
- [x]
- [x]
- [x]
- [x]

**Comment by ArcLumin** [comment]
Considering it's been a month without any reported KotD issues, I'd say it's safe to close this
