### ISSUE TITLE
the double oxygen tank and extended capacity oxygen tank are exactly the same

### ISSUE THREAD

**Issue by Spacedong** [HippieStationCode/HippieStation13#2750]
https://vgy.me/xHH5EC.png

nice job

**Comment by GeneralGoose** [comment]
just the sprites*

**Comment by ArcLumin** [comment]
Normals have 3, extendeds have 6, and doubles have 10

As to why doubles have 10 when they're DOUBLE, dunno

But that's not the question here. Doubles and extendeds aren't exactly the same

**Comment by GeneralGoose** [comment]
who even uses those

**Comment by Mithrandalf** [comment]
I could make a resprite. This is a bugfix I can do.

And as for who uses them, I do. Atmos tech, cooled and pressurised tanks with the output at 17. Hand them out to the crew, become MvP.
