### ISSUE TITLE
Fire extinguishers are fucking terrible at extinguishing people

### ISSUE THREAD

**Issue by blobbernaut** [HippieStationCode/HippieStation13#2761]
why are they so transcendentally awful at extinguishing people? A fire extinguisher should not be worse than just rolling on the floor at putting a person who is on fire out. A fire extinguisher should always put a person who is on fire out, as long as they aren't re-exposed to an ignition source, just like they do to regular fires in the atmosphere.

**Comment by ArcLumin** [comment]
because someone changed extinguisher code to do a very small amount of splashed on turf based chems that actually transfer none of the chems on the target.

**Comment by blobbernaut** [comment]
why do people fuck with these things

**Comment by banthebantz** [comment]
Ye it's so that they can spray other chems but they are pretty fucking awful at both tbh and need a buff. I mean why does a fucking little spray bottle transfer like 10x as much as a fucking fire extinguisher arg!

**Comment by Carbonhell** [comment]
guy who fucked with extinguisher here, the water removes a ton of fire_stacks so unless you're literally covered with napalm you get extinguished with one or MAXIMUM 2 sprays, you need to actually "hit" the guy with the water effect tho so maybe you didn't aim correctly?

**Comment by Carbonhell** [comment]
banthebantz, a spray can spray 10 units all in a single effect and on a single tile,whereas the fire extinguisher can spray up to 3x3 tiles.

**Comment by Kierany9** [comment]
Here's the thing, the way fire extinguishers work is shit. They always cover a 3x3 area if it can fit and you're only hitting a guy with 1/3rd of the water, meaning that you have to be in a corner to actually get hit by more than a tiny puff of water. Also, most fires can be stop-drop-rolled out of with one or two resists anyway, and I'd argue that the big ol' napalm fires need to be able to be actually extinguishable.

**Comment by banthebantz** [comment]
Ye but the amount of reagents they transfer per tile is really shitty, they need a capacity and transfer rate buff.

**Comment by banthebantz** [comment]
Also as a sidenote we need more touch based chems to actually use with it, right now all we really have is miner's salve (nerfed to oblivion), clf3+fuels and acid (nerfed to oblivion).

**Comment by ArcLumin** [comment]
A number of "For fun" chems work with it. For example;
Carpet
Colorful Reagent
Quantum Hair Dye
Barber's Aid
etc.
But yeah, it's a small set of chems that actually work

**Comment by ArcLumin** [comment]
Some shit, like radium, which require a certain amount (Over 3u) to leave a spot won't work in an extinguisher. Which is really too bad, because spraying glowing goo everywhere would be fantastic for anti-shadowlings

**Comment by Carbonhell** [comment]
Code a way to break the valve?So it'll spray like 30 units instead of 10 or whatever but you cannot fix it so it's balanced

**Comment by ArcLumin** [comment]
This has been fixed due to the addition of new chems in extinguishers, close this
