### ISSUE TITLE
There are no cameras in the hallway leading to Brig infirmary or inside the Brig infirmary itself

### ISSUE THREAD

**Issue by Spacedong** [HippieStationCode/HippieStation13#2791]
https://vgy.me/GH55jy.png

**Comment by Pyko1** [comment]
Definitely no reason for no camera coverage there.

**Comment by TheOneAndOnlyCreeperJoe** [comment]
There's already coverage outside of the door to the right and inside the infirmary.

To me it seems like the blind spot is intentional.
