### ISSUE TITLE
shoulder holster goes on your belt

### ISSUE THREAD

**Issue by Spacedong** [HippieStationCode/HippieStation13#2794]
![](http://i.imgur.com/XdkPivg.jpg)

**Comment by McBawbaggings** [comment]
Where else do you want it to go?

**Comment by Spacedong** [comment]
on your shoulder? attached to your jumpsuit?

**Comment by McBawbaggings** [comment]
And then how do you access the contents?

**Comment by Mithrandalf** [comment]
Baystation has some items that are worn as accessories with storage capacity. I'm not a huge fan of how it works, but a shoulder holster that stores a gun when used on it with a quickdraw UI item would be a pretty good solution.

Of course, if anyone is willing to code it.

**Comment by calibraptor** [comment]
It's fine as is

**Comment by Pyko1** [comment]
Maybe we could add extra storage slot's somewhere around the HUD like the spells are, so you can even move em if you want.

**Comment by Pyko1** [comment]
Could be used for all sorts of fancy items like uniform with secret pocket and shit.

**Comment by GeneralGoose** [comment]
i think tg had pockets on jumpsuits or at least wanted to have them
or idk make it so acessories can have effects like adding armor or item slots

**Comment by Pyko1** [comment]
What if we were to remove pocket slots all together, and had somekind new way of adding pocket slots with visual restrictions to same HUD space from other gear.

**Comment by Pyko1** [comment]
ie. armor/holster adds a "pocket" slot with a gun symbol, space suit has a tank symbol.
Big slot has a backpack symbol, smaller slot has a box symbol.

All wearable items can technically have pockets.
And the pocket slots can be opened and closed like backpacks.

**Comment by GeneralGoose** [comment]
you suggest remaking the whole pocket thing for this one feature?

**Comment by Pyko1** [comment]
not jsut for this, but for all cloth items with extra storage.

So instead of 2 static pocket slots we have dynamic pockets that can change depending on shit you wear.

**Comment by Spacedong** [comment]
or just put it on your jumpsuit as accessory and make when you click your jumpsuit it brings up some storage slots like a backpack

**Comment by Spacedong** [comment]
see CM for example
