### ISSUE TITLE
No disposals mail sorters to sec

### ISSUE THREAD

**Issue by Pyko1** [HippieStationCode/HippieStation13#2798]
Yet the destination tags still remain.

**Comment by GeneralGoose** [comment]
raptor?

**Comment by calibraptor** [comment]
Do what now?

**Comment by GeneralGoose** [comment]
i think he meant disposals pipe that sorts items
basically you mark an item to go to HoS office and pipe sends it there

**Comment by Pyko1** [comment]
If the mailing to sec has been removed on purpose, then the destination tagging mail to there should be also removed.

Or you could just stop slacking and add the sorting pipes so the mail works again.

**Comment by Spacedong** [comment]
^

**Comment by TheOneAndOnlyCreeperJoe** [comment]
This was fixed in the map-fix-a-ton.
