### ISSUE TITLE
full length shotguns can fit on armor, making the sawn off shotgun a nearly useless feature

### ISSUE THREAD

**Issue by Spacedong** [HippieStationCode/HippieStation13#2802]
doesn't make any sense, why can I fit a massive riot shotgun or a double barrel on my armor slot, i should have to saw it off atleast

**Comment by Mithrandalf** [comment]
You make a lot of these that aren't bugs.

If you dont have armour, you cant carry it.

**Comment by ArcLumin** [comment]
you can also carry multiple at once of shotguns in your pack, which is pretty useful

**Comment by ArcLumin** [comment]
shoot all your shots, throw the shotgun at a target, pull another out, repeat
