### ISSUE TITLE
mindslave uplinks are OBSCENELY bad

### ISSUE THREAD

**Issue by Spacedong** [HippieStationCode/HippieStation13#2806]
They cost half your traitor uplink, buying two will waste your entire stash. Everyone can see the message that pops up in the chat that you're implanting a guy, AND you need to stand still and WAIT more than 5 seconds to implant a guy. Why isn't it instant like a gang converter at the cost of knocking a guy KO for a few seconds?

**Comment by ArcLumin** [comment]
They're pretty good, to be honest. If you're doing anything like that in public anyways it's sus as fuck. They're hella good, plus it's not hard to stuncuff someone and take their headset

**Comment by Kokojos** [comment]
Grudgeissue.

**Comment by GeneralGoose** [comment]
lol its like holoparasite but you can get 2 of them
and with a gang of 3 you can beat anyone to death and it will be okay because majority is always right, unless people will suspect a rev

**Comment by trifornt-tinfornt** [comment]
@GeneralGoose 
Then again on Goon Station the Captain can also be a traitor, which leads to massive suspicion from the crew and he gets lynched instantly if someone thinks he's up to no good, or he so much as does one shady thing. Mindslaving the Captain wouldn't be very wise over there unless you knew exactly what you were doing.

**Comment by GeneralGoose** [comment]
i've seen some games of traitor captain with 0 suspicion
also here captain dies within first 2 minutes and gets replaced by some random dude

**Comment by Kierany9** [comment]
Mindslaves just need to be cheaper IMO.

**Comment by GeneralGoose** [comment]
no they don't

**Comment by ArcLumin** [comment]
except normal mindslaves wear off after 10~20 min
meanwhile, chaplain can get skeledudes for cheaper than a normal mindslave and not only are they permanent, and completely loyal, they come fully armored and geared

**Comment by GeneralGoose** [comment]
chaplain has a fuckton of other overpowered shit

**Comment by GeneralGoose** [comment]
also you have to find a dead person first that hasn't gone braindead or kill one yourself
oh also they aren't stealthy

**Comment by ArcLumin** [comment]
They can easily change their clothing and blend in with the crew, and they're immune to most damages, but yeah. I can agree, chaplain is a strong job. Traitor ones get reactive lightning armor, necrostones, they naturally have armor, bananas, a hidden murderoom, easy body disposal, a bunch of chaplain only cameraless areas, bibles to hide shit in, null rods, holy water, and relics

**Comment by GeneralGoose** [comment]
so yeah nerf chap instead he's fucking op with his items

**Comment by ArcLumin** [comment]
protip; if you need a body, you can blow a borg, steal it's brain, shove it into a braindead corpse and then necrostone it. You can do the same with monkey-human corpses, and use this to turn people into/out of cats, make a bunch of corpses to absorb as a ling, etc

Especially when it doesn't need to be an active brain for a ling, you can just constantly pass around a brain that was "once used by a player" and absorb all the corpses

**Comment by GeneralGoose** [comment]
i know though it requires effort

**Comment by ArcLumin** [comment]
not much effort required with dismemberment, since you can take off their head, take out their brain with a click, shove a new one in, pop the head back on and succ. rinse, repeat.

Necrostone doesn't make human skeles, exactly. It makes something similar, but more op. Immune to oxy/cold/heat/toxin/bloodloss/pressure/etc.  Noblood, so no dna to clone, but still.

**Comment by ArcLumin** [comment]
Can still revive them a few ways, including debraining them, putting their brain into a new body, and cloning them, or using strange reagent or defib.

**Comment by ArcLumin** [comment]
you can use this to give them an identity of a crew member you killed thats loyal to you and will murder shit at your whim

**Comment by Mithrandalf** [comment]
Make the skelebro equipment cursed. Ez.

**Comment by ArcLumin** [comment]
you can still debrain the skeles to pop them into another body

**Comment by Mithrandalf** [comment]
Cant do that if their helmet is cursed and acid-proof and they're non-dismemberable which they should be.

**Comment by ArcLumin** [comment]
they're dismemberable. They're the parent of the playable skeletons

**Comment by Mithrandalf** [comment]
Fix that.

**Comment by GeneralGoose** [comment]
just fucking make them into simple mobs that don't have brains
