### ISSUE TITLE
There are two Medbay air alarm duplicates 1 tile away from each other.

### ISSUE THREAD

**Issue by Spacedong** [HippieStationCode/HippieStation13#2810]
with the one behind the desk being more hard to get to and generally nobody uses it, dunno why it's there
https://vgy.me/dOAoQE.png

EDIT: there's also 3 alarms that control the treatment center, one in surgery observing room, storage, AND in medbay itself above the IV drips, for some odd reason

**Comment by banthebantz** [comment]
My Little Snowflake, My Little Snowflake,
What is Redundancy all about?
My Little Snowflake, My Little Snowflake
Redundancy is Autism!
(My Little Snowflake)
I used to wonder what Redundancy could be.
(My Little Snowflake)
Until you all shared its Autism with me.
When I was young I was too busy to make any Variables.
Such silliness did not seem worth the effort it expends.
But my little /tg/ coders, you opened up my eyes
And now the truth is crystal clear, as splendid spaghetti code.
And it's such a wonderful surprise.
(My Little Snowflake)
I used to wonder what Redundancy could be.
(My Little Snowflake)
Until you all shared its Autism with me.
When while loops makes me wanna hide, you'll dash to my side,
Autism is never in short supply, once smitten twice exadv1.
For honesty no Snowflake can deny, you are the syntax error of my eye,
A proc that lags everything so horrifically, a common thing to come by
And you all make fun and laughter as easy as trying to compile this shit!
(My Little Snowflake)
I used to wonder what Redundancy could be.
(My Little Snowflake)
Until you all shared its Autism with me.
Our Redundancy's Autism and it's growing all the time.
A new adventure waits for us each day is yours and mine.
We'll make it special every time!
We'll make it special every time!
(My Little Snowflake)
What a wonderful wonder Redundancy brings
(My Little Snowflake)
Do you know you're all my very worst
(Variables!) Variables, you're my very worst
(Variables!) Variables, you're my very worst
(Variables!) Variables, you're my very worst
(Variables!) Variables!

**Comment by GeneralGoose** [comment]
the 2 on the pic are ok i think, they are in 2 different areas, even tho im not sure

**Comment by Pyko1** [comment]
Intended, one is for medbay and the another is for medbay lobby.

**Comment by GeneralGoose** [comment]
told ya

**Comment by Spacedong** [comment]
tested it in-game yesterday, both work for the same area, open this

**Comment by Pyko1** [comment]
Yes they work in same are but are separated by firelocks/doors/distance its intended.
You can have multiple air alarms in the same are with no issue.
Its actually better to have multiple air alarms in large areas or areas with multiple doors.

This is not an issue.

**Comment by Pyko1** [comment]
The air alarm in medbay cant monitor the air composition in medbay lobby due to doors. They scan only the tile in front of them, not the whole area.
