### ISSUE TITLE
security equipment lockers no longer start with batons

### ISSUE THREAD

**Issue by Spacedong** [HippieStationCode/HippieStation13#2812]
why was this changed? seems to have occurred around newbrig update, any idea why?

**Comment by tabsiforu** [comment]
i for one welcome shitcurity getting nerfed

**Comment by danhibiki** [comment]
Probably just falling in line with removing equipment redundancy, which they still have a bit. The only thing this would affect is job change security, which I believe there is some in armory to be distributed.

**Comment by GeneralGoose** [comment]
thats fucking stupid
the point of the lockers, which every single fucking department has, is if someone gets a job change they can go to that department, open the locker and get a whole set of every single piece of clothing and all the items, required items for their new job, in one place
there's ALWAYS *spare* equipment.
haha remove caps spare then, he starts with one right? 
I DARE YOU
I DOUBLE DARE YOU TO REMOVE CAP'S SPARE
and don't forget clown's spare bike horn

**Comment by Pyko1** [comment]
There is only telebatons in armory, if you lose your baton there is no replacement.

**Comment by banthebantz** [comment]
That's dumb.

**Comment by Spacedong** [comment]
yeah seriously add the batons back, there's no spares anywhere on the station, why the fuck did you stealthily remove this @calibraptor or did you just forget

**Comment by Spacedong** [comment]
also can we please just remove the useless bathroom area and move the security wardrobe lockers into the main equipment room please

**Comment by calibraptor** [comment]
Wot, I never fucked with the lockers at all.

**Comment by Spacedong** [comment]
then who the fuck did because it changed on your newbrig PR

**Comment by GeneralGoose** [comment]
there was some PR that removed the batons from the lockers and moved them to sec officers to be a roundstart thing

**Comment by calibraptor** [comment]
I don't know but I do know that you have to actually go into the locker code and change the contents manually, you can't do that via mapping to my knowledge.

**Comment by GeneralGoose** [comment]
tru unless batons were snowflakish-ly mapped in on top of the lockers

**Comment by GeneralGoose** [comment]
i don't see why this doesn't work
unless you mapped in wrong lockers

**Comment by GeneralGoose** [comment]
which actually may be the case because there's a child of secure lockers that just adds in stunbatons
https://github.com/HippieStationCode/HippieStation13/blob/master/code/game/objects/structures/crates_lockers/closets/secure/security.dm#L122

**Comment by GeneralGoose** [comment]
oh well i can't check because git doesn't show the full changes

**Comment by Pyko1** [comment]
They were probably separated so that the departmental sec rooms don't have batons but the main sec does. And calib used the wrong lockers for main sec.

**Comment by Spacedong** [comment]
@calibraptor come on

**Comment by GeneralGoose** [comment]
dood i investigated it 4u and its so ez to fix so do it ;^)

**Comment by tabsiforu** [comment]
are we gonna discuss whether we keep this "bad feature"

**Comment by Kokojos** [comment]
Closing on behalf of neb
