### ISSUE TITLE
Surviving the entire round as AI still leads to being "marooned on [space station name]"

### ISSUE THREAD

**Issue by Spacedong** [HippieStationCode/HippieStation13#2814]
does this count for the "survive alive" objectives for traitor AIs? not sure if its fluff or not considering those objectives

**Comment by Pyko1** [comment]
Now if the objectives dont work thats a bug, but separate from this issue.

**Comment by Kierany9** [comment]
It used to be broken, was fixed here https://github.com/HippieStationCode/HippieStation13/pull/2590
