### ISSUE TITLE
AIR INJECTORS IN SPACE DON'T WORK FUCK

### ISSUE THREAD

**Issue by Spacedong** [HippieStationCode/HippieStation13#2834]
https://vgy.me/A1W55F.png

mainly because any pump or vent in space besides manual valves don't work as they rely on power to run and space as an area doesn't have power. kinda dumb when you think about it, you can't set up atmos shit in space like on /vg/ for cooling plasma using h/e pipes in space or other cool stuff

EDIT: this means the supermatter exhaust injector doesn't work either fuck

**Comment by tabsiforu** [comment]
>playing atmospherics
i bet you're the type of person to have a train set huh

so do we nuke every air injector in space?

**Comment by Spacedong** [comment]
>not playing atmos in a game that was designed for atmospheric simulation

time to stop

**Comment by tabsiforu** [comment]
>implying that SS13 is a simulator of anything but autism

ishiggydiggy

**Comment by GeneralGoose** [comment]
git gud my dude atmos is power

**Comment by blobbernaut** [comment]
atmos is fun though fuck you tabsiforu

**Comment by Pyko1** [comment]
atmos is the deadliest thing on the station if you are a proper atmoswizard.

**Comment by McBawbaggings** [comment]
Atmos work in space provided they're not in an APC area IIRC

**Comment by McBawbaggings** [comment]
Load up the turbine and see it eject plasma on metastation

**Comment by banthebantz** [comment]
You can use H/E pipes in space though, just have the pumps on the station.

**Comment by McBawbaggings** [comment]
![muppet city oscar 2016-08-30 151741](https://cloud.githubusercontent.com/assets/15840795/18092651/fd0cea4a-6ec4-11e6-8fc3-6a04a9466c08.png)

Works fine on metastation. Metastation uses /obj/machinery/atmospherics/components/unary/outlet_injector and our box station uses /obj/machinery/atmospherics/components/unary/outlet_injector/on
