### ISSUE TITLE
the recycler is TOO inefficient, perhaps even broken 

### ISSUE THREAD

**Issue by Spacedong** [HippieStationCode/HippieStation13#2844]
it never seems to make metal and the only thing I've ever gotten out from it was one piece of glass after recycling over 30 objects, what the fuck

**Comment by tabsiforu** [comment]
intended feature, recycling doesn't work irl

**Comment by Pyko1** [comment]
I recall it can prettymuch only recycle things like shards and metal rods. And some rare items that have materials defined in them.

**Comment by ArcLumin** [comment]
yup, it needs mats to be defined in them. Might be a good idea to make it give a small amount of glass and metal on anything that it breaks dependant on the size of the object?

**Comment by Pyko1** [comment]
Or we could add material values to some parent objects.
Just adding material amounts to 20 or so common parent objects would make a huge difference already.

**Comment by Pyko1** [comment]
Also what if there were some huge chem tank where all the chems from disposals are dumped to react together and what not.

**Comment by ArcLumin** [comment]
I'd actually love that. It'd likely remove all reagents from anything that comes out of it, sans iron and silicon, which it converts to iron and glass

**Comment by ArcLumin** [comment]
The chemtank would need to be a special one that was anchored and durable, or else you'd find people stealing it and trying to fill it up with explosives

Also, it'd need to use grindercode to turn shit into reagents as well.

**Comment by Pyko1** [comment]
Yeah it would be stationary tank that is connected to recycler.
And only way to put chems in to it would be the recycler.

**Comment by tabsiforu** [comment]
dump all the chems in a blender and add a paper cup so people can drink from it

**Comment by ArcLumin** [comment]
99% sure they'd fucking die with all the shit that gets poured into the trash

You're literally drinking trashcan slops

**Comment by Pyko1** [comment]
Could turn it in to a massive grog production OP.

**Comment by tabsiforu** [comment]
add in the ability to make prison wine in the toilets

**Comment by Spacedong** [comment]
i like these comments

**Comment by ArcLumin** [comment]
Recycler only takes 25% of the materials in stuff, which is already small

**Comment by Pyko1** [comment]
also effeciency should be at least 66%
