### ISSUE TITLE
Wizard rounds don't end properly.

### ISSUE THREAD

**Issue by Spacedong** [HippieStationCode/HippieStation13#2848]
Once the wizard dies it never mulligans nor ends the round, so its just stuck in a period of extended mode unless wizard had summoned guns causing there to be survivors.

**Comment by Mithrandalf** [comment]
It spawns fresh antags doesnt it

**Comment by Spacedong** [comment]
I just said, mulligan never happens. No, it doesn't.

**Comment by McBawbaggings** [comment]
Mulligan was intentionally disabled IIRC.

**Comment by Alphora** [comment]
Well, I'm willing to fix this, but what's the desired behavior? Immediate round end? Shuttle call? New antags?

**Comment by Kokojos** [comment]
It should trigger Mulligan IMO.

**Comment by Alphora** [comment]
No idea what mulligan is.

**Comment by Mithrandalf** [comment]
she's that chick from that one fighting game

**Comment by Kokojos** [comment]
It automaticly makes new antags if more than 70% of the crew isin't dead. It's activated after a malf AI loses if in the remove blob gamemode if they blob dies early IIRC.

**Comment by Alphora** [comment]
So there's an already-existing proc? Or you're saying that's the behavior we want?

**Comment by Kokojos** [comment]
It's already existing but I think it's more than just a proc. I honestly have no idea where it's stored.

**Comment by McBawbaggings** [comment]
it's a config setting IIRC
I think people are saying wiz rounds should end on wizard death?

**Comment by Alphora** [comment]
I'll find it or make a new one.

**Comment by ArcLumin** [comment]
Don't get it confused with the mulligan chemical

**Comment by ArcLumin** [comment]
Not an issue, please close
