### ISSUE TITLE
RCD makes the wrong windows for the server.

### ISSUE THREAD

**Issue by Spacedong** [HippieStationCode/HippieStation13#2855]
Our server uses full tile windows while the RCD makes 4 single window panes around a grille which only /tg/ uses to my knowledge. I blame lazy porting.

**Comment by ArcLumin** [comment]
We make cheap chink imported knockoff RCD's, duh

**Comment by ArcLumin** [comment]
https://github.com/HippieStationCode/HippieStation13/pull/2876 fixed in this, close this
