### ISSUE TITLE
Meat can appear under the gibber when it spits out meat. 

### ISSUE THREAD

**Issue by Spacedong** [HippieStationCode/HippieStation13#2870]
minor oversight, you can still pick up the meat though, just makes no sense as it spews out from the front of the gibber

**Comment by Pyko1** [comment]
Half tempted to add working as intended, and claim that maybe the meat just sloppily fell of and rolled under it.

**Comment by Spacedong** [comment]
except it happens literally every time and its annoying jesus christ

**Comment by banthebantz** [comment]
The meat should shoot out as a high pressure stream of liquefacted sausages™
