### ISSUE TITLE
meatpies have the wrong sprite

### ISSUE THREAD

**Issue by Spacedong** [HippieStationCode/HippieStation13#2882]
they look like banana cream pies

**Comment by ArcLumin** [comment]
No image? Spacedong, quality, not quantity

**Comment by ArcLumin** [comment]
Just checked, there's two types of meat pies with different sprites and shit.

The meat pie you're looking at is an Australian meat pie, which look very similar to a cream pie. Examine it, it'll say it's imported from Australia

Not an issue

**Comment by danhibiki** [comment]
OOOHHH SHIIIIIIIIIIT

**Comment by Spacedong** [comment]
yes cunt

**Comment by ArcLumin** [comment]
not an issue, close this
