### ISSUE TITLE
bibles don't fucking work anymore.

### ISSUE THREAD

**Issue by Spacedong** [HippieStationCode/HippieStation13#2890]
thanks /tg/

95% of the time you're trying to heal a guy you get this message
https://vgy.me/vseE7b.png

**Comment by ArcLumin** [comment]
It's RNG lad. 60%.

but that message is retarded

**Comment by Spacedong** [comment]
yeah but I liked it when it was either heals or brain damage, not this retarded message that makes no sense at all

**Comment by ArcLumin** [comment]
fixed via https://github.com/HippieStationCode/HippieStation13/pull/2891
