### ISSUE TITLE
Microwaves supposedly can't hold soy sauce

### ISSUE THREAD

**Issue by Spacedong** [HippieStationCode/HippieStation13#2897]
haven't tested it for myself yet but it was reported by a guy who mhelped/ahelped, wasn't there for it

**Comment by McBawbaggings** [comment]
Tested this on my own local server.
Microwave accepted soysauce and successfully made a meat bun.
https://github.com/HippieStationCode/HippieStation13/blob/6392b7b57ceb953b487ca345b4c1394fe2ba6658/code/modules/food%26drinks/recipes/microwave/recipes_pastry.dm#L129

**Comment by Spacedong** [comment]
noice thanks dog
