### ISSUE TITLE
dismemberment sprites are fucky

### ISSUE THREAD

**Issue by Spacedong** [HippieStationCode/HippieStation13#2901]
https://vgy.me/zgNA4y.png

see this image? I'm missing my right arm, but it still shows up on my sprite

**Comment by LufgtHuron** [comment]
Probably related to the fact that if you replace your blown off limbs with robotic ones, the sprite doesn't update and you look like you're without an arm, even though you can use both of them.

**Comment by Spacedong** [comment]
newer issue on this
