### ISSUE TITLE
Slimes cannot attack mechs

### ISSUE THREAD

**Issue by blobbernaut** [HippieStationCode/HippieStation13#2994]
title, pretty self explanatory. Be slime, click a ripley.

**Comment by GuyonBroadway** [comment]
Confirmed, was big slime called "Blue balls", clicked a Ripley and it did nothing.

**Comment by ArcLumin** [comment]
I've been hit by slimed in a ripley before (I think) and took damage. I'll need to test this shit

**Comment by ArcLumin** [comment]
Tested, can confirm

**Comment by Spacedong** [comment]
not an issue, apparently was fixed

**Comment by Spacedong** [comment]
this was fixed
