### ISSUE TITLE
Rodgun anchor not being turned off on movement

### ISSUE THREAD

**Issue by blobbernaut** [HippieStationCode/HippieStation13#302]
I was hit by a rod gun and pinned to a wall. I used a hand tele to escape, but I was still unable to walk. 

This is an issue because it doesn't make sense.

**Comment by JustinBNewton** [comment]
I suggest making it so it rips whatever is holding the person to the wall out and causes a massive amount of brute damage.

**Comment by nalarmg** [comment]
It makes sense code wise - at the moment there's no trigger for making you able to move again if this happens. The easiest way to deal with this is, if an object is embedded/the person is pinned, make them able to move but keep the object embedded. Fairly trivial fix.

**Comment by Chronitonity** [comment]
Couldnt you add a way to "resist" out of being pinned to a wall? the only issue i could think of is that it would interfere with the resist function used by handcuffs/cablecuffs/ect

**Comment by Tomeno** [comment]
you have to rip the rod out as far as I know
