### ISSUE TITLE
stunbatons still missing from sec lockers because calibraptor never used the right locker type when making the map

### ISSUE THREAD

**Issue by Spacedong** [HippieStationCode/HippieStation13#3062]
title

**Comment by Swagile** [comment]
I thought someone nerfed sec lockers because people getting access / caps laser gun to open up a sec locker for a free gg-no-re stun.

**Comment by McBawbaggings** [comment]
Yeah there was a sec change pr, I can't find it though.

**Comment by JohnGinnane** [comment]
We should fix this in rebase now that it can be compiled

**Comment by Swagile** [comment]
note, hos locker and wardens locker still has stun batons

this seems more like a stealth nerf to anyone joining sec via hop since armory has no stun batons but has tasers

**Comment by Pyko1** [comment]
Adding bug as, I recall they were intended to be same as originally, and at no point of the original Map PR was mentioned the nerfing of sec gear, they were just accidentally swapped to the nerfed lockers meant for departmental sec closets.
