### ISSUE TITLE
this area is called Security Maintenance despite not being anywhere near fucking security

### ISSUE THREAD

**Issue by Spacedong** [HippieStationCode/HippieStation13#3063]
https://vgy.me/V4qV3P.png

its in the goddamn public Infirmary near Arrivals, why is it sec access only

**Comment by ArcLumin** [comment]
Used to be a sec checkpoint but mappers miss shit all the time

**Comment by Spacedong** [comment]
*cough* CALIB

**Comment by JohnGinnane** [comment]
This is something we can fix on rebase

**Comment by Swagile** [comment]
On the old version of metastation, this area was actually the security office. It was later changed to a free medical area but the security maint name and permissions remained due to bad mapping while the new sec office was made.
