### ISSUE TITLE
vodka cleans floors without making them wet

### ISSUE THREAD

**Issue by Spacedong** [HippieStationCode/HippieStation13#3072]
you dont even need a recipe, just mass stockpile vodka from the abandoned bar and you have instant 1000u space cleaner, what a joke update do you people even codecheck anymore

**Comment by JohnGinnane** [comment]
https://github.com/HippieStationCode/HippieStation13/blob/master/code/game/objects/items/weapons/mop.dm#L33 likely cause. Vodka doesn't make floors wet (whereas water and holy water do)

**Comment by JohnGinnane** [comment]
Fixed: 
![image](https://cloud.githubusercontent.com/assets/3355198/20818514/fb09efcc-b825-11e6-8b66-10c7998a1719.png)
