### ISSUE TITLE
the recycler door at disposals is still open and anyone who spawns there (and cant take 1 step to right before crossing over) gets sent to the Mail office which is easily escapable if cargo wont open the door for you.

### ISSUE THREAD

**Issue by Spacedong** [HippieStationCode/HippieStation13#3092]

**Comment by Swagile** [comment]
are you unrobust, my dude

everyone spawns with a 5 brute hit and throwforce weapon called the emergency oxygen tank

said window can be broken down and is what happens almost 90% of the time anyone gets stuck there

this is assuming they spawn RIGHT THERE, and they are a new player who doesn't understand game mechanics

**Comment by banthebantz** [comment]
just fart your own arse off and smash the windoor you fucking pleb

**Comment by Spacedong** [comment]
its dumb

**Comment by Pyko1** [comment]
You can easily get past without getting swallowed, and even if you do, you can still easily break out.
And it is very much intended, considering i even made some fixes to make it a little bit easier to get past.

Not an Issue, feel free to make a map PR for headmins to decide.

**Comment by Scinexx** [comment]
Start the conveyor turned off by default when round start

**Comment by Pyko1** [comment]
Anyways, this is all inteded.

And any "fixes" should be considered as features.

**Comment by Swagile** [comment]
salt dong too unrobust to use emergency oxygen tank or super fart and bash his way out with his own butt

10/10 issue, would read again

**Comment by ArcLumin** [comment]
NO ESCAPE, BESIDES THIS FLIMSY PARTITION OF GLASS, HOW WILL I EVER GET PAST IT?

**Comment by Pyko1** [comment]
Could prolly close this as well, but leaving it open for now to see if anyone else sees this as an issue.
