### ISSUE TITLE
you still cant fucking ghost as a mmi and are stuck in a permanent state of hell after you're blown as a borg

### ISSUE THREAD

**Issue by Spacedong** [HippieStationCode/HippieStation13#3094]
this is fucking priority, fix this,  or atleast allow people to ghost out of it and then allow them to come back when their heads get put back into a borg body or mech, christ

**Comment by McBawbaggings** [comment]
I'm pretty sure you can suicide and that works?

**Comment by Swagile** [comment]
you can do this as a brain (from what i remember) and when you get decapitated

this seems to be an isolated issue regarding MMI's
