### ISSUE TITLE
Welding helmets make you blind instead of the old square black thing.

### ISSUE THREAD

**Issue by Spacedong** [HippieStationCode/HippieStation13#3095]

**Comment by Spacedong** [comment]
thiis also leads to you not being able to do anything because you're "blind"

**Comment by JohnGinnane** [comment]
Pics?

**Comment by JohnGinnane** [comment]
This seems like a pretty major bug, was anything changed to do with mask overlays changed recently?

**Comment by Spacedong** [comment]
NEVERMIND IM A NIGGER

**Comment by JohnGinnane** [comment]
![image](https://cloud.githubusercontent.com/assets/3355198/21120503/9d261672-c0bf-11e6-87c7-f9c300470116.png)

**Comment by ArcLumin** [comment]
Yeah, you're a nigger, 10/10

**Comment by Dudeinyourbackyard** [comment]
SUPER BAKA
