### ISSUE TITLE
YOU CAN CREMATE THE NUKE 

### ISSUE THREAD

**Issue by Spacedong** [HippieStationCode/HippieStation13#3105]
# **NO**

**Comment by GuyonBroadway** [comment]
SPACEDONG THIS ROUND IS STILL GOING

**Comment by meteoses** [comment]
Y E S. I so this all the time to counter nuke ops; best and most intended strategy of all time. Saltdong.

**Comment by Spacedong** [comment]
https://vgy.me/gsBCrs.png

**Comment by Scinexx** [comment]
Saw this personally, funny as all hell

**Comment by Spacedong** [comment]
HOW COULD YOU LET THIS HAPPEN

**Comment by Dudeinyourbackyard** [comment]
this game never ceases to amuse in the most spectacular ways

**Comment by blobbernaut** [comment]
llllllllllllol

**Comment by Zadeon** [comment]
Feature

**Comment by Anderbergst** [comment]
Never bring the nuke with you when you raid station for the nuke disk. Leave at the syndie outpost.

**Comment by WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW** [comment]
it was intentional

**Comment by ArcLumin** [comment]
Protip, you can delete it too, or put it in the supermatter. Or the singulo.

**Comment by JohnGinnane** [comment]
Does putting it in singulo remove the singulo?

**Comment by ArcLumin** [comment]
Nope

**Comment by Scinexx** [comment]
Honestly though, if anyone but the nuke ops get there hand on the nuke, it's almost always game over, with the option of spacing it or throwing it in the singularity, or even just hiding it.

**Comment by JohnGinnane** [comment]
This has been around since it was implement years ago and I'm inclined to think it should remain the same. Anyone disagree with that?

**Comment by JohnGinnane** [comment]
Discussed this on slack, closing as it's more fun this way
