### ISSUE TITLE
whos bright idea was it to put this here

### ISSUE THREAD

**Issue by Spacedong** [HippieStationCode/HippieStation13#3121]
https://vgy.me/MDBEpc.png

it should be OUTSIDE the lobby so you can release prisoners into the hallways without having them trapped if you've sealed security off from traitors, nukies, or revs

its dumb

**Comment by McBawbaggings** [comment]
Ride the disposal bin like a boss.

**Comment by Spacedong** [comment]
but thats unnecessary and shouldnt be required
