### ISSUE TITLE
morph corpse is one of the least detailed and worst sprites in the game

### ISSUE THREAD

**Issue by Spacedong** [HippieStationCode/HippieStation13#3122]
https://vgy.me/cnQZQF.png

no shading on the half thats cut off

stray white pixel to the side

**Comment by gumner** [comment]
not sure if this is any better or even worse 
![dead morph](https://cloud.githubusercontent.com/assets/24728932/21450818/4686ca58-c8e1-11e6-864a-47010a8922f6.png)

**Comment by yobob591** [comment]
looks like leaking avocado with shit on top

**Comment by gumner** [comment]
yeah i figured out its too bright,im going to make it a lil darker

**Comment by yobob591** [comment]
probably a good idea

**Comment by gumner** [comment]
not sure if it looks any better ![dead morph](https://cloud.githubusercontent.com/assets/24728932/21451717/44bc8828-c8e8-11e6-86ff-db83fb5ee346.png)

**Comment by gumner** [comment]
i went on and made another morph sprite,but this one looks kinda bad 
![dead morph](https://cloud.githubusercontent.com/assets/24728932/21454962/d4b69ab6-c903-11e6-8ab5-79b899394d58.png)
