### ISSUE TITLE
"Jesus Mace" reskin for null rod looks like a dead space carp

### ISSUE THREAD

**Issue by Spacedong** [HippieStationCode/HippieStation13#3137]
https://vgy.me/uWYf0k.png

was the spriter even self-aware when drawing this? christ, atleast make it black or brown, maces aren't fucking purple, more like carp mace god damn

**Comment by yobob591** [comment]
I thought it was some joke I didnt get

**Comment by dreamcrab** [comment]
umm are you forgetting the jesus fish?

are you guys slow

**Comment by dreamcrab** [comment]
http://www.clipartbest.com/cliparts/nTB/L9x/nTBL9xGTA.png

**Comment by Spacedong** [comment]
i dont get it

**Comment by Spacedong** [comment]
still looks uglyy

**Comment by 2Dollarbill** [comment]
This is why this should stay
https://www.youtube.com/watch?v=_HUf1tjrBwM

**Comment by Pyko1** [comment]
very much intended, closing
