### ISSUE TITLE
[Urgent] AIs cannot click on APCs whose terminals are blocked by static.

### ISSUE THREAD

**Issue by Spacedong** [HippieStationCode/HippieStation13#3152]
This means that any terminal that borders a room but is in a wall backed by maintenance cannot be accessed at all. This issue makes a significant portion of APCs non-accessible to AI's.

**Comment by ArcLumin** [comment]
Seems more of a mapping issue to me.

**Comment by Pyko1** [comment]
Actualyl prolly caused by this https://github.com/HippieStationCode/HippieStation13/pull/3070

**Comment by Pyko1** [comment]
So might be better to fix it with code than moving all the APC's inside their respective rooms from maint.

**Comment by McBawbaggings** [comment]
TD fixed tyhis right
