### ISSUE TITLE
Possible crash bug

### ISSUE THREAD

**Issue by Swagile** [HippieStationCode/HippieStation13#3153]
BoH sing was created in escape before shuttle came and it was wandering around seconds before escape shuttle would arrive. The singuloth was near where the escape shuttle would land in escape and when it hit 0:00 seconds the server crashed. I believe this is because singuloth overlapped with where the shuttle would land hence the game freaked out.

I have no access to the coder logs or whatever it is you guys look through to check for this, but it happened just now on server.

**Comment by ArcLumin** [comment]
99% of the time roubd end crashes are due to issues printing out the round end report.

**Comment by Pyko1** [comment]
Most likely same thing https://github.com/HippieStationCode/HippieStation13/issues/2921

**Comment by ArcLumin** [comment]
Closing because it's likely the same as the previous bug.
