### ISSUE TITLE
Blastco anti-burglar payloads are set in the code to have a density of 0 but are impassable and cannot be walked over in-game

### ISSUE THREAD

**Issue by Spacedong** [HippieStationCode/HippieStation13#3159]
title

**Comment by Pyko1** [comment]
If you are talking about those payloads in corners, i recall they are set to be solid.
You can still enter the blastoco room, right?

**Comment by Pyko1** [comment]
yeah, working as intended.
some of them are mapped to be /obj/machinery/blastco_antiburglar{density = 1}
