### ISSUE TITLE
Vampires can't suck people dry for some odd reason.

### ISSUE THREAD

**Issue by Spacedong** [HippieStationCode/HippieStation13#3165]
Why is the entire vampire gamemode based around nonlethally succing people? You're a vampire and an antag, why do they care about hurting people? I feel like this only hinders the gamemode's potential.

**Comment by McBawbaggings** [comment]
They would potentially turn into ling 2.0

**Comment by yobob591** [comment]
The whole idea of vampire is a nonlethal meme antag since they only occur randomly and arent a mode

**Comment by Spacedong** [comment]
oh ok
i usually just suck blood then kill them anyway

**Comment by Spacedong** [comment]
:shrug:

**Comment by yobob591** [comment]
I wouldnt be against this tbh

**Comment by Kierany9** [comment]
> i usually just suck blood then kill them anyway

you are cancer
