### ISSUE TITLE
ANTI STUNS CAN BE USED INDEFINITELY WITH NO DOWNTIME OR DAMAGE

### ISSUE THREAD

**Issue by blobbernaut** [HippieStationCode/HippieStation13#3176]
seriously fix this you fucking idiots

**Comment by Kierany9** [comment]
meme issues

**Comment by yobob591** [comment]
u fugkin dildods

**Comment by blobbernaut** [comment]
This is not a meme issue you fuck, this is actually bug abuse

**Comment by blobbernaut** [comment]
disable all healing chemicals when it's in your blood

**Comment by trifornt-tinfornt** [comment]
kierany why did you trash antistuns
they were annoying but fine before just make them not helpful with dental implants eeeee

**Comment by Kierany9** [comment]
do not worry my child

soon i shall rise from my three month death and perform miracles once more

im like jesus but 30 times slower

**Comment by banthebantz** [comment]
it's called addiction and overdosing you reatad

**Comment by GeneralGoose** [comment]
i told u guys not to break chem
