### ISSUE TITLE
[HOLY FUCK ALERT THE NAVY] YOU CAN'T THROW MOBS ANYMORE (in very specific certain cases but still holy shit)

### ISSUE THREAD

**Issue by Spacedong** [HippieStationCode/HippieStation13#3188]
# FUCK

**Comment by gumner** [comment]
how the fuck did this happen

**Comment by McBawbaggings** [comment]
waht

**Comment by yobob591** [comment]
WHAT

**Comment by JohnGinnane** [comment]
How

**Comment by ArcLumin** [comment]
Do not panic, this is dong we're talking about. This might not even be 100% true

**Comment by Spacedong** [comment]
this happened to me yesterday and today, both times the person was laying down on the ground either dead or in crit

**Comment by zenek123321** [comment]
it is true

**Comment by McBawbaggings** [comment]
I tested this myself and I could do it fine though.
Very strange.
