### ISSUE TITLE
[Priority] Roundstart cyborg names STILL do not work after months of nobody fixing them

### ISSUE THREAD

**Issue by Spacedong** [HippieStationCode/HippieStation13#3225]
JUST

**Comment by ArcLumin** [comment]
DO IT

**Comment by MethMedic** [comment]
I always wondered why my borg name never worked

**Comment by banthebantz** [comment]
Fix this so I can finally live my life long dream of playing as ' AM on wheels'

**Comment by McBawbaggings** [comment]
I've asked Nalar about the config settings. I think that might be the issue.

**Comment by McBawbaggings** [comment]
Nalar has fixed the config settings.
