### ISSUE TITLE
space heaters' temperatures do not update at all when the '-' or '+' buttons are pressed 

### ISSUE THREAD

**Issue by Spacedong** [HippieStationCode/HippieStation13#3227]
:ok_hand:

**Comment by banthebantz** [comment]
it does but you have to reopen the window

**Comment by Spacedong** [comment]
yeah but its literally every time, it needs to be fixed

**Comment by Pyko1** [comment]
We have this same issue with so many different machines. its an UI bug.

**Comment by GeneralGoose** [comment]
isnt there a proc for updating shit 
its usually put everywhere after you press a button

**Comment by Spacedong** [comment]
@GeneralGoose pretty sure its updateUsrDialog()

**Comment by Spacedong** [comment]
whoever coded space heaters is a NIGGER
