### ISSUE TITLE
Stands and presumably holoparasites can be given fugu glands

### ISSUE THREAD

**Issue by Spacedong** [HippieStationCode/HippieStation13#3245]
for what purpose

**Comment by ArcLumin** [comment]
Holoparas are blacklisted lad

**Comment by Spacedong** [comment]
# BUT STANDS AREN'T

**Comment by ArcLumin** [comment]
So blacklist em

**Comment by KittyKathy** [comment]
Maybe we should leave it in, I mean really what is that gland even used for other than memes(big sentient Ian) and spending a ton of mining points to make a mining creature huge and sentient to wreck the escape shuttle.
Only the person who actually mined and found the stand arrow would have this gland if they bothered to fight the monsters.
Why are holoparasites even blacklisted anyway, is it GAME BREAKING?
Do you need to send in a death squad to kill someone with this?

**Comment by ArcLumin** [comment]
Not particularly, except for standard. Fugu glands give +2 to enviroment smash, meaning standards not only get double melee damage, but also can break rwalls like butter. Not super game breaking but hey.

**Comment by yobob591** [comment]
standard is p shit as is so basically this just makes them legitimate
