### ISSUE TITLE
random rock in space has atmosphere

### ISSUE THREAD

**Issue by TrickyDickRichard** [HippieStationCode/HippieStation13#3247]
it's just a rock in space that has atmosphere for seemingly no reason, it's got a few tiles of asteroid floor to the west of it and it's an ellipse that goes longer vertically. don't know which z-level it's on

**Comment by Spacedong** [comment]
Duplicate of #3246. Close this.

**Comment by TrickyDickRichard** [comment]
AaAAassdsgfjl;'\
