### ISSUE TITLE
ert doesn't even have implants so they can't tell if somebody just stole their shit

### ISSUE THREAD

**Issue by blobbernaut** [HippieStationCode/HippieStation13#3261]
fix

**Comment by Hackole** [comment]
they do start with implants you walnut

**Comment by blobbernaut** [comment]
yeah well fuck you

**Comment by trifornt-tinfornt** [comment]
the story:
I killed him and another guy who was hunting me effortlessly in a 2v1 battle right after I got ambushed by a .357 traitor. I then moved to kill an ERT and took his armor and I.D. Nobody noticed that I was fake until I started a rampage. During this time, he ick ocked mentioning how overpowered the double esword was and how it could reflect tasers, something I had just done with that exact weapon.
This is a saltcomplaint.

**Comment by blobbernaut** [comment]
yeah well fuck you

**Comment by Spacedong** [comment]
close this

**Comment by KittyKathy** [comment]
How about this? ERT/Death Squad starting with micro implants so they can't have most/all of their gear stolen by the murderboner they were sent in to stop?

**Comment by asskek** [comment]
ert gear isnt that good though. 
by the time ert gets there the murderboner will have at least 3 energy guns of their own anyway

**Comment by yobob591** [comment]
ERT? Nah, microbomb implants can damage the station and their gear isn't that good. Now Deathsquad?
Absoultely, I'd even say macrobomb implants but that would likely just cause a cluster of incompetent DS to blow up

**Comment by Swagile** [comment]
is that actually a problem tho

a cluster of DS setting off their macro bombs will at least kill the threat they are sent in to kill no matter how bad they are

**Comment by Spacedong** [comment]
this isn't even an issue, close it

**Comment by Spacedong** [comment]
CLOSE THIS FOR THE LAST TIME

**Comment by Dudeinyourbackyard** [comment]
WHAT IF I CLOSE YOU KID?
