### ISSUE TITLE
[FUCK] ALL SINGLE TILE FACING WINDOWS ARE COLORED CYAN FOR SOME REASON

### ISSUE THREAD

**Issue by Spacedong** [HippieStationCode/HippieStation13#3267]
https://vgy.me/ZEGHTH.png

it seems someone snuck in an undocumented change

**Comment by yobob591** [comment]
is this really an issue

**Comment by JohnGinnane** [comment]
Yes

**Comment by banthebantz** [comment]
blame dongcode

**Comment by JohnGinnane** [comment]
Well spotted

**Comment by Spacedong** [comment]
who did this?

**Comment by yobob591** [comment]
sunflower issue is my favorite tag

**Comment by Spacedong** [comment]
AAAAAAAAAAAAAAAAAAAAAAAA

**Comment by Anderbergst** [comment]
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA

**Comment by Spacedong** [comment]
more proof: 
https://vgy.me/i6ytiu.png
