### ISSUE TITLE
There are 2 z-levels that are completely blank.

### ISSUE THREAD

**Issue by Spacedong** [HippieStationCode/HippieStation13#3271]
z6 and z7 have nothing on them

**Comment by TDcoolguy300** [comment]
Stop, they are template Z-levels

**Comment by ArcLumin** [comment]
thats the fucking point spaecmong

**Comment by asskek** [comment]
hehehehheehehe# _****_

**Comment by asskek** [comment]
#  _**hehehehehehehehehhehehehee**_
