### ISSUE TITLE
ALL INSTANCES OF STRIPPED_INPUT ARE UNSANITIZED

### ISSUE THREAD

**Issue by Spacedong** [HippieStationCode/HippieStation13#3329]
FUCK

**Comment by banthebantz** [comment]
you are unsanitised

**Comment by Pyko1** [comment]
Also most likely.

**Comment by Pyko1** [comment]
But ill just keep this open for now if there is indeed a massive security oversight.

**Comment by Pyko1** [comment]
Hell, ill even give a benefit of the doubt on what Working as Intended label
