### ISSUE TITLE
[FUCK] SPOOKIUM BYPASSES CATBANS

### ISSUE THREAD

**Issue by Spacedong** [HippieStationCode/HippieStation13#3336]
FUCK OFF CODERS WHY'D YOU MERGE THIS

**Comment by GuyonBroadway** [comment]
As does krokadil addiction

**Comment by yobob591** [comment]
spergedong

**Comment by Swagile** [comment]
its ok

skeletons and zombies are now valid

issUE reSVOLED

**Comment by GeneralGoose** [comment]
delete this

**Comment by blobbernaut** [comment]
Behold my stand, ☆ [ F u c k ] ☆

**Comment by ArcLumin** [comment]
You're an idiot spacemong, it doesn't bypass catbans
