### ISSUE TITLE
Stimulant virus is garbage

### ISSUE THREAD

**Issue by blobbernaut** [HippieStationCode/HippieStation13#3339]
What the fuck

**Comment by McBawbaggings** [comment]
The chemical given got changed.

**Comment by banthebantz** [comment]
Yeah it's terrible thanks to morphine

**Comment by blobbernaut** [comment]
yeah and it's not even a fucking stimulant mcbaw

**Comment by blobbernaut** [comment]
false advertising

**Comment by banthebantz** [comment]
I'll see about fixing this don't worry

**Comment by Pyko1** [comment]
Should be fixed by https://github.com/HippieStationCode/HippieStation13/pull/3341
