### ISSUE TITLE
uranium doors don't seem to emit much radiation

### ISSUE THREAD

**Issue by Spacedong** [HippieStationCode/HippieStation13#3350]

**Comment by tortellinitony** [comment]
this isn't an issue jesus christ

**Comment by MethMedic** [comment]
They should emit a fair amount, but in turn reduce the chances of a door being uranium from a door thing

**Comment by banthebantz** [comment]
Unless the uranium is enriched the radioactivity is pretty insignificant especially in the relatively short timescale of a round.

**Comment by ArcLumin** [comment]
its another dong splitting hairs issue
