### ISSUE TITLE
clocks are retarded

### ISSUE THREAD

**Issue by Spacedong** [HippieStationCode/HippieStation13#3368]
shitty sprites that conflict with the artstyle, they're all at different positions, and they appear outside of the room they're supposed to be in because whoever added them to the map didn't fucking offset them

**Comment by gumner** [comment]
LEAVE DUWANG

**Comment by GuyonBroadway** [comment]
Worse still, they don't take the two min lobby time into account so when the shift starts it says its been going on for two minutes.

**Comment by Spacedong** [comment]
what a goddamn tragedy
