### ISSUE TITLE
Blastco still explodes when you buy it

### ISSUE THREAD

**Issue by yobob591** [HippieStationCode/HippieStation13#3372]
Title says it all, buy blastco, go inside, explode horribly.

**Comment by ArcLumin** [comment]
DONGCODE

"IT WORKS" HE SAID

**Comment by Anderbergst** [comment]
i guess he didn't test it real good.

**Comment by tortellinitony** [comment]
http://i.imgur.com/VrxG4SH.png
I can confirm this.

**Comment by Spacedong** [comment]
it was codechecked by a maintainer and they said it was good

**Comment by JohnMcLaime** [comment]
Dungcode

**Comment by gumner** [comment]
DUWANGCODE

**Comment by ArcLumin** [comment]
It got reverted
