### ISSUE TITLE
this area is called "Secure Storage" in areas even though the APC is called MiniSat Maint

### ISSUE THREAD

**Issue by Spacedong** [HippieStationCode/HippieStation13#3396]
![](https://vgy.me/36wm5z.png)

**Comment by yobob591** [comment]
It's probably fixed in the rebase feg if u really want to make a godamn pr instead of wait you can

**Comment by Pyko1** [comment]
Hardly an issue since only mappers or people vareditng turf can see the real area name.
Also rebase coming in so pointless really.

**Comment by QuarianCommando** [comment]
Dong, you mong. Do you not see the tools, materials, and airtank? This is the AI sat's secure storage area.
