### ISSUE TITLE
Singularity/Powernetwork is fucked

### ISSUE THREAD

**Issue by BoltTreasure** [HippieStationCode/HippieStation13#456]
Ever since the latest update the singularity engine is unable to be setup because even with filled tanks and a stage 3 singlo stable it will go to the correct power output to the network for half a second then go to no output for 5 odd seconds. Because of this the station will lose power every round without fail because the super-matter is a hassle to setup and solars can't really power the station.

To reproduce you just need to setup the engine.

**Comment by whitefox08** [comment]
Fixed in #457

**Comment by whitefox08** [comment]
Issue remains  now within powernet.

**Comment by whitefox08** [comment]
Fixed in #484
