### ISSUE TITLE
Kebab

### ISSUE THREAD

**Issue by Pyko1** [HippieStationCode/HippieStation13#512]
Apparently trying to make kebab out of shark meat, corgi meat or pug meat breaks the microwave.

**Comment by TDcoolguy300** [comment]
Bad coding in the recipes DM, i don't believe they fall under the normal meat directory that the kebab uses

**Comment by JustinBNewton** [comment]
Yeah, TG handles meat based on mobs now too, i think we should switch to that system but itll require some recode.

**Comment by Memendia** [comment]
Or just add those meats to the recipe

**Comment by Chnkr** [comment]
> Yeah, TG handles meat based on mobs now too, i think we should switch to that system but itll require some recode.

Just start all over again, grab their repo, port your shitty changes, done.
