### ISSUE TITLE
Getting on mulebot while on the ground

### ISSUE THREAD

**Issue by Pyko1** [HippieStationCode/HippieStation13#513]
If you are stunned or resting, and you pull yourself on mulebot, it will mess your pixel_y.

When you are stunned it makes your pixel_y -6 if it is 0, if it is anythign else it is reseted to 0.
When you get up any value of pixel_y is reseted to 0.

Maybe have it jsut add and subtract 6 from pixel_y instead?

**Comment by JustinBNewton** [comment]
Bad checks in the mounting of mulebots.

**Comment by Carbonhell** [comment]
Fixed in #638
