### ISSUE TITLE
Mining Ripley

### ISSUE THREAD

**Issue by Pyko1** [HippieStationCode/HippieStation13#519]
Was QM, get in mining ripley, togled on internal tank, lights, DNA locked pressed the id upload and maintenance protocol button couple times, noticed i dont have a crate, and ejected.

The ripley vanished and the but cant enter the spot where it was.

![bug](https://cloud.githubusercontent.com/assets/12048747/9640280/918f29e6-51b9-11e5-9aa0-ecd4890bccd5.PNG)
the popup is from the spot where ripley was, no items there.

**Comment by Pyko1** [comment]
nevermind it was just too dark to see it

**Comment by whitefox08** [comment]
:eyes:
