### ISSUE TITLE
Admins and mentor stuff

### ISSUE THREAD

**Issue by Pyko1** [HippieStationCode/HippieStation13#526]
It seems that in latest mentor changes we lost out mentor abilities.

Only options in Mentor tab are Mentorhelp and Mentorwho.
Also tried giving myself mentor access, but didn't change anything.

**Comment by Pyko1** [comment]
We still see the mentor chat tho.

**Comment by Pyko1** [comment]
Or was the mentorchat removed?

**Comment by Pyko1** [comment]
oh apparently its just the msay button that is missing, you can talk manually.

**Comment by nalarmg** [comment]
Msay button was hidden, it's still there and usable though. It's basically like asay, but for mentors and admins.
