### ISSUE TITLE
Ban appeal url after ban

### ISSUE THREAD

**Issue by Pyko1** [HippieStationCode/HippieStation13#544]
It does not work.

It gets redirrected to:
http://www.hippie-station-13.com/viewforum.php?f=8

**Comment by Chronitonity** [comment]
Should go to http://www.hippie-station-13.com/forums/viewforum.php?f=8

its just missing the /fourms/ in between, gr8

**Comment by Pyko1** [comment]
actually its missing www.
First it goes to:
hippie-station-13.com/forums/viewforum.php?f=8
which redirrects it to
http://www.hippie-station-13.com/viewforum.php?f=8

**Comment by Memendia** [comment]
If my shit gets merged I can fix it asap

**Comment by whitefox08** [comment]
Fixed at #546
