### ISSUE TITLE
Chaplain thrallstone text is hard to notice

### ISSUE THREAD

**Issue by blobbernaut** [HippieStationCode/HippieStation13#550]
http://puu.sh/k4O2t/67099c4ba1.png

Alright, I can kind of see this one. It should be bold and red, and the font should be larger. Not blue and the same size as all the other text. 

Alternatively, buying the stone could add both players to cult faction, This would have some interesting interactions with other traitor items.

**Comment by JustinBNewton** [comment]
I think the cult thing needs some discussing. Triggering cult rounds inside of traitor rounds is no bueno, but id like to see the chaplain lead a cult like thing.

**Comment by Chnkr** [comment]
> Triggering cult rounds inside of traitor rounds is no bueno

Setting the `cult` faction does nothing, it's not going to trigger the cult gamemode, jeeez.

**Comment by blobbernaut** [comment]
yeah the little icon just to make it clear they're on a team, since there's just one chaplain
