### ISSUE TITLE
Throwing knife is hilariously bad

### ISSUE THREAD

**Issue by blobbernaut** [HippieStationCode/HippieStation13#560]
The throwing knife's melee attack does 3 brute, which is less than a punch. It stuns for less than the time it takes to remove the knife and throw it again, the bleed damage even if you rip it out is minimal, and funniest of all it does LESS THROW DAMAGE than the syndicate combate knife.

**Comment by Memendia** [comment]
Question.... why was it made so bad in the first place?

**Comment by lcass** [comment]
The point of the knife is to do embed , bleed and stun not immediate damage. The combat knife doesn't stun on hit this stuns on hit no matter what. It was originally more powerful but I was told to debuff it.

**Comment by blobbernaut** [comment]
It does 15 damage, like 0.1 bleed damage AFTER ripping it out,  and the stun is minimal, i tested trying to take it out as soon as it embeds and you can't even take it out before they get up. Plus, you lose the 6tc knife.

The bleed is actually about the same as a staple. Like damn.

**Comment by JustinBNewton** [comment]
![img](https://i.gyazo.com/089bf50ad42ed8cf5be07b977393e011.png) is hilariously bad.

**Comment by JustinBNewton** [comment]
#576
