### ISSUE TITLE
Closing PDA from last round

### ISSUE THREAD

**Issue by Pyko1** [HippieStationCode/HippieStation13#563]
You have to wait for the next round to start and open your new PDA before you can close the PDA window from last round.

**Comment by JustinBNewton** [comment]
Can be fixed by allowing window close in game (ie system based closing) needs testing.

**Comment by Chnkr** [comment]
Not a bug.

**Comment by Chronitonity** [comment]
Unless you have something helpful to comment then you probably shouldn't be commenting amigo.
