### ISSUE TITLE
Atmos issues

### ISSUE THREAD

**Issue by Pyko1** [HippieStationCode/HippieStation13#614]
Half of the engineering not connected.
Xeno not connected.
Aft Primary hallway vent pump not connected.
Engineering airscrubber #2 connected to airsupply line.

Also call it a feature, but many rooms are lacking a proper vents/scrubbers as well.
Such as QM office, chaplain office, superslam medbay, medbay lobby, server room, art supply storage,  dorm rooms and librarians "office" at least, probably even more.

**Comment by Pyko1** [comment]
Fixed in https://github.com/HippieStationCode/HippieStation13/pull/627 if it gets added.

**Comment by whitefox08** [comment]
Fixed in #627
