### ISSUE TITLE
Being forcefed by someone else gives the wrong logs

### ISSUE THREAD

**Issue by Pyko1** [HippieStationCode/HippieStation13#628]
Being fed with it, but the message is.
You attempt to feed the captain's flask to Bix Nood.
You feed the captain's flask to Bix Noo

**Comment by Chronitonity** [comment]
This is a bug with every food object. Being forcefed by someone else gives 
"You attempt to feed X to Yourself" 
You feed "X" to Yourself"

**Comment by Carbonhell** [comment]
I tested with food and it doesn't happen..?It does happen with drinking things through

**Comment by Carbonhell** [comment]
ASAP OH GOD FIXed in #629

**Comment by Carbonhell** [comment]
CLOSE
