### ISSUE TITLE
Valves

### ISSUE THREAD

**Issue by Pyko1** [HippieStationCode/HippieStation13#642]
Some digital and manual valves placed on map appear like normal pipes.

![capture](https://cloud.githubusercontent.com/assets/12048747/9977891/7fcc3a72-5f20-11e5-8196-261c1ee6fd93.PNG)

**Comment by Pyko1** [comment]
Same on map editor.
![capture](https://cloud.githubusercontent.com/assets/12048747/9977896/b49c9ff8-5f20-11e5-8bbe-2bb9c4152284.PNG)

**Comment by Pyko1** [comment]
Also digital valves seem to always vanish when you try to wrench em down.

**Comment by Pyko1** [comment]
Its always the UP-Down valves that appear as pipes, not the Left-Right.

![image](https://cloud.githubusercontent.com/assets/12048747/9978752/4b041862-5f4f-11e5-9b92-e3cbc6f0356e.png)
Broken manual valve.

**Comment by danhibiki** [comment]
Was this fixed with the RPD revert?

**Comment by Pyko1** [comment]
Nope, its still in.
