### ISSUE TITLE
Staffs of healing/admins still don't fix bullets ahhhh

### ISSUE THREAD

**Issue by blobbernaut** [HippieStationCode/HippieStation13#665]
they set the list of entries to be null without actually removing the entries, and the bleeding is based only on the number of entries, not what's in them. So basically, it's even worse than before, because the person cannot have the ghost bullets removed via surgery.

**Comment by blobbernaut** [comment]
can we just ditch the shitty bullet embed mechanic and make it just treatable with gauze even

**Comment by Chronitonity** [comment]
Fix don't remove, its a 20 second surgery even.
