### ISSUE TITLE
Raise dead rune

### ISSUE THREAD

**Issue by Pyko1** [HippieStationCode/HippieStation13#674]
It seems to gib you when drawn.
Not sure, if it activates itself to resurect a ghost following you automatically when drawn.

**Comment by Carbonhell** [comment]
No, you make 2 runes,put a living human on one and a corpse on the other. If you activate it,the living gets gibbed and the ghost on top of the dead body gets put inside said body. If you step on the rune your life force will be taken. Feature,not a bug

**Comment by Pyko1** [comment]
Well, I was instantly gibbed after i finished drawing raise dead rune.
Only other runes i had drawn were sacrifice and convert, and never clicked any of them.

**Comment by Carbonhell** [comment]
Were you standing on any rune that could've been a raise dead rune?

**Comment by Pyko1** [comment]
yes, since i drew it on the floor, under me.

**Comment by Pyko1** [comment]
so someone else had a raise dead rune elsewhere, and he was using it just as i drew mine.

**Comment by Carbonhell** [comment]
cannot really reproduce it myself,seems a really really rare bug. No clue if it is fixable/if it should be.
