### ISSUE TITLE
energy guns do not show ammo count when on the stun setting

### ISSUE THREAD

**Issue by Spacedong** [HippieStationCode/HippieStation13#785]
ag 
![2015-10-07_15-02-07](https://cloud.githubusercontent.com/assets/12958054/10351994/8dacfd36-6d1a-11e5-94b5-44461a3c848e.png)

**Comment by DerptheStewpidGoat** [comment]
Will fix soon

**Comment by Chronitonity** [comment]
Fixed in #787
