### ISSUE TITLE
Security Rifles are missing from Cargo request console.

### ISSUE THREAD

**Issue by Spacedong** [HippieStationCode/HippieStation13#799]
where are they, they disappeared and now my I can't feel /k/ as warden anymore :^(

**Comment by Chronitonity** [comment]
They aren't coming back

**Comment by Spacedong** [comment]
why

**Comment by Chronitonity** [comment]
Real answer is balance wise they are complete shit and take like 10 seconds to get and they don't have firing pins since we scrapped those so anyone can fire them.


They were a bad addition all around and they aren't gonna be on the map or cargo
