### ISSUE TITLE
telescopic baton has a barely see-able sprite in certain places

### ISSUE THREAD

**Issue by Spacedong** [HippieStationCode/HippieStation13#825]
has literally no outline or contrast and looks overall blurry as shit 
fuvk 
![2015-10-09_15-25-35](https://cloud.githubusercontent.com/assets/12958054/10403552/7a383cc6-6e9a-11e5-8e49-8326b74bf9d4.png)
![2015-10-09_15-27-25](https://cloud.githubusercontent.com/assets/12958054/10403554/7e7a21f0-6e9a-11e5-9bfc-adce73e80622.png)

**Comment by Chronitonity** [comment]
fixed in whatever commit cafa made

**Comment by Cafaling** [comment]
I did shit for once :^)
