### ISSUE TITLE
Radiation never comes.

### ISSUE THREAD

**Issue by Spacedong** [HippieStationCode/HippieStation13#863]
The announcement and sound file play but it never comes at all.

**Comment by JustinBNewton** [comment]
Its a random chance to hit you. So you could potentially not get hit at all in the hall.

**Comment by Carbonhello** [comment]
It isn't a station wide pulse anymore,but random pulses across the station. Therefore you may not get hit even if you're not in maint,but maint is 100% safe. Not a bug therefore
