### ISSUE TITLE
Cult floors

### ISSUE THREAD

**Issue by Pyko1** [HippieStationCode/HippieStation13#873]
Made some sweet ass cult floors as artificer, but the end product was surprisingly disappointing.

![capture](https://cloud.githubusercontent.com/assets/12048747/10436145/4823f3c0-712d-11e5-812f-f2ccafef9214.PNG)

**Comment by Pyko1** [comment]
Also while on it.
The spell that summons construct shells, should be renamed from Artificer to Summon: Construct Shell. And also change the Summon Soulstone to Summon: Soulstone.

**Comment by Carbonhello** [comment]
#788 known issue,also on tg, i was trying to fix it but i became busy with other issues,will look into it

**Comment by Carbonhello** [comment]
Please close,there's already an issue regarding this
