### ISSUE TITLE
E-Gun with broken cell

### ISSUE THREAD

**Issue by Pyko1** [HippieStationCode/HippieStation13#889]
Not sure where it came from, but it was wizard round andt there was an E-Gun that had a cell (/obj/item/weapon/stock_parts/cell) with max charge of 50, instead of the default 1000.

**Comment by Carbonhello** [comment]
Was the gun path the standard one or was it something else like a child of it? If you remember

**Comment by Carbonhell** [comment]
Cannot reproduce unless anyone else experienced this bug,armory/spawned eguns look fine

**Comment by blobbernaut** [comment]
if it got emp'd a bunch (used charge book, honk?) emps have a chance to permanently reduce the reliability / maximum charge of a cell in its range.

**Comment by Carbonhell** [comment]
Actually, charge book can charge an egun but its downside is that it reduces the max charge. Not sure if emps have the same effect too but i doubt. may you confirm,pyko?

**Comment by oprayx73** [comment]
emp's drain and take the max cap of battery off

**Comment by Carbonhell** [comment]
well then, close?
