### ISSUE TITLE
1 handed defib, possibly other 2hd items as well

### ISSUE THREAD

**Issue by Pyko1** [HippieStationCode/HippieStation13#908]
You can drop the offhand by using rest, while still keeping the defib in your hand. And it works jsut lke you were using 2 hands to hold it.

**Comment by Pyko1** [comment]
Also it seems you "strip" offhand away from people.

**Comment by Pyko1** [comment]
![capture](https://cloud.githubusercontent.com/assets/12048747/10522522/40cee5e6-737e-11e5-9835-249b2abf9f69.PNG)

**Comment by Pyko1** [comment]
![capture](https://cloud.githubusercontent.com/assets/12048747/10522558/71c040e6-737e-11e5-8ac0-c711766b81cd.PNG)

**Comment by Memendia** [comment]
drop everything while rested?

**Comment by Pyko1** [comment]
I believe the defib paddle is undroppable.
But this was mostly caused with stripping the offhand from a person.

**Comment by Memendia** [comment]
Isn't the offhand a nodrop?
if not why not make it one?

**Comment by Pyko1** [comment]
definitely should be nodrop, but what happens if you drop the mainhand and the offhand is nodrop, check to remove that?

**Comment by Pyko1** [comment]
actually there is already

**Comment by Memendia** [comment]
wat

**Comment by Pyko1** [comment]
I meant that the offhand item gets properly removed if you drop the mainhand, but it already does that anyways.

**Comment by Memendia** [comment]
so making it nodrop is already done or will it be done?
