### ISSUE TITLE
SPESS CARP PLUSHIES DONT MAKE CUTE NOISES ANYMORE 

### ISSUE THREAD

**Issue by Spacedong** [HippieStationCode/HippieStation13#909]
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA

they make a stupid fucking space carp biting noise instead, fix this ASAP oh god

**Comment by blobbernaut** [comment]
gamebreaking

**Comment by Pyko1** [comment]
yes, everything is broken because of this, fix ASAP

**Comment by Cafaling** [comment]
I need this. Please fix.
