### ISSUE TITLE
Cloaks don't give the armor value they state in the code

### ISSUE THREAD

**Issue by blobbernaut** [HippieStationCode/HippieStation13#945]
for example, the captain's cloak has 10 armor for everything. However, the covered parts bit isn't defined so it doesn't apply the armor to anything on the body. It should probably apply to either everything but the head, or chest + arms

**Comment by blobbernaut** [comment]
Easy fix:

add the line
body_parts_covered = CHEST|GROIN|LEGS|FEET|ARMS|HANDS
to line 10 of 
https://github.com/HippieStationCode/HippieStation13/blob/a53993489f1ac0c233d127c5770b6738c1416aa3/code/modules/clothing/cloaks.dm

The cloaks look pretty big and it seems like they should cover everything below the head

**Comment by Carbonhell** [comment]
Fixed in #973  close
