### ISSUE TITLE
full chemistry setup in abandoned lab

### ISSUE THREAD

**Issue by Spacedong** [HippieStationCode/HippieStation13#950]
assistants can now make any grenade or chemical they want e.g. polyacid/lube/explosions for FREE
http://vgy.me/Yi0gSX.png

AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA

**Comment by Chronitonity** [comment]
Feature

**Comment by Spacedong** [comment]
in where you fucker

**Comment by Chronitonity** [comment]
perhaps our fourms
