### ISSUE TITLE
Logs

### ISSUE THREAD

**Issue by Pyko1** [HippieStationCode/HippieStation13#964]
Thrown items are not properly logged.

Also would be nice to have jumpable cordinates on every log entry.

**Comment by TDcoolguy300** [comment]
Might not be possible to add a jump command to the logs, due to it being an array containing simple text and not HTML.

**Comment by TDcoolguy300** [comment]
Meant list, not array.

**Comment by Carbonhell** [comment]
Yeah. I'm working on this but i'll add normal coords, then you can just use Jump to coords to jump on them.
