### ISSUE TITLE
Crap from scrubbers

### ISSUE THREAD

**Issue by Pyko1** [HippieStationCode/HippieStation13#977]
![capture](https://cloud.githubusercontent.com/assets/12048747/10628798/89294c76-77d1-11e5-96f2-0ada013ea14c.PNG)

Not sure what it is, crashed me every time i right clicked it.
All that is on the tile according to alt click is floor.
I believe it was caused by scrubbers back pressure event.

**Comment by Pyko1** [comment]
![capture](https://cloud.githubusercontent.com/assets/12048747/10629395/2e78ddf4-77d7-11e5-89d4-2a99c53e6976.PNG)
Right click crashing again, definitely from, the scrubber backpressure event.

**Comment by Pyko1** [comment]
ADMIN LOG: Foos/() has deleted all (25552) instances of /obj/effect/decal/cleanable/flour.
ADMIN LOG: Pyko/() has deleted all (24811) instances of /obj/effect/decal/cleanable.

At least we had some decals.

**Comment by Memendia** [comment]
fixing this right now by sacrificing my computer to see what chems cause the decals
